
<!-- <div class="disclaimer topical-posts">
	Disclaimer: Cointweets sources data from third parties and does not create the content. Content on the platform is not an offer, solicitation, or financial advice for buying or selling securities or investments.
</div> -->
<div class="main-footer">
	<ul class="footer-nav">
		<li class="footer-nav-item">
			<a href="<?php echo cl_link('terms_of_use'); ?>" data-spa="true">
				<?php echo cl_translate("Terms of use"); ?>
			</a>
		</li>
		<li class="footer-nav-item">
			<a href="<?php echo cl_link('privacy_policy'); ?>" data-spa="true">
				<?php echo cl_translate("Privacy policy"); ?>
			</a>
		</li>
	</ul>

	<?php if (not_empty($cl["config"]["android_app_url"]) || not_empty($cl["config"]["ios_app_url"])): ?>
		<div class="footer-nav-get-apps h-mobile" style="margin-bottom:20px;">
			<?php if (not_empty($cl["config"]["android_app_url"])): ?>
				<a href="<?php echo($cl["config"]["android_app_url"]); ?>" target="_blank">
                <span class="icon home">
						<?php echo cl_ikon('android'); ?>Android App
					</span>
				</a>
			<?php endif; ?>

			<?php if (not_empty($cl["config"]["ios_app_url"])): ?>
				<a href="<?php echo($cl["config"]["ios_app_url"]); ?>" target="_blank">
                <span class="icon home">
						<?php echo cl_ikon('apple2'); ?>iOS App
					</span>
				</a>
			<?php endif; ?>
		</div>
	<?php endif; ?>
</div>
