<div class="right-sb-container sidebar" data-app="right-sidebar">
	<div class="sidebar__inner">
		<div class="sidebar_login">
			<div class="social_login">
				<h2>
					<?php echo cl_translate("New to {@name@}?", array(
						"name" => $cl["config"]["name"]
					)); ?></h2>
				<p><?php echo cl_translate("new_to_desc"); ?></p>
				<div class="social_button">
				
					<?php if (in_array("on", array($cl["config"]["instagram_status"], $cl["config"]["vkontakte_status"], $cl["config"]["discord_status"], $cl["config"]["facebook_oauth"], $cl["config"]["linkedin_oauth"], $cl["config"]["google_oauth"], $cl["config"]["twitter_oauth"]))) : ?>

						<div class="form-group oauth-login-providers">
							<?php if ($cl["config"]["google_oauth"] == "on") : ?>
								<a href="<?php echo cl_link('oauth/google'); ?>" class="social-login-btn google">
									<button class="btn btn-custom main-inline lg btn-block" type="button" style="background-color: #f7faff !important;border-color: #d2e3fc!important;">
										<span class="d-inline-flex flex-wn align-items-center">
											<span class="flex-item btn-icon">
												<?php echo cl_icon('logos/google-logo-2'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate("SignIn with Google"); ?>
											</span>
										</span>
									</button>
								</a>
							<?php endif; ?>
							<?php if ($cl["config"]["facebook_oauth"] == "on") : ?>
								<a href="<?php echo cl_link('oauth/facebook'); ?>" class="social-login-btn facebook">
									<button class="btn btn-custom main-inline lg btn-block" type="button">
										<span class="d-inline-flex flex-wn align-items-center">
											<span class="flex-item btn-icon">
												<?php echo cl_icon('logos/logo-facebook'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate("SignIn with Facebook"); ?>
											</span>
										</span>
									</button>
								</a>
							<?php endif; ?>
							<?php if ($cl["config"]["twitter_oauth"] == "on") : ?>
								<a href="<?php echo cl_link('oauth/twitter'); ?>" class="social-login-btn twitter">
									<button class="btn btn-custom main-inline lg btn-block" type="button">
										<span class="d-inline-flex flex-wn align-items-center">
											<span class="flex-item btn-icon">
												<?php echo cl_icon('logos/logo-twitter'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate("SignIn with Twitter"); ?>
											</span>
										</span>
									</button>
								</a>
							<?php endif; ?>
							<div class="form-cta-link forgot">
								<a data-toggle="collapse" data-target="#collapseLogin" aria-expanded="false" aria-controls="collapseLogin">
									<span class="btn-outline">
										<?php echo cl_icon('more_horiz'); ?>
										<?php echo cl_translate("More Social Login"); ?>
									</span>
								</a>
							</div>
							<div class="collapse" id="collapseLogin">
								<?php if ($cl["config"]["linkedin_oauth"] == "on") : ?>
									<a href="<?php echo cl_link('oauth/linkedin'); ?>" class="social-login-btn linkedin">
										<button class="btn btn-custom main-inline lg btn-block" type="button">
											<span class="d-inline-flex flex-wn align-items-center">
												<span class="flex-item btn-icon">
													<?php echo cl_icon('logos/logo-linkedin'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate("SignIn with LinkedIn"); ?>
												</span>
											</span>
										</button>
									</a>
								<?php endif; ?>
								<?php if ($cl["config"]["discord_status"] == "on") : ?>
									<a href="<?php echo cl_link('oauth/discord'); ?>" class="social-login-btn discord">
										<button class="btn btn-custom main-inline lg btn-block" type="button">
											<span class="d-inline-flex flex-wn align-items-center">
												<span class="flex-item btn-icon">
													<?php echo cl_icon('logos/logo-discord'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate("SignIn with Discord"); ?>
												</span>
											</span>
										</button>
									</a>
								<?php endif; ?>
								<?php if ($cl["config"]["vkontakte_status"] == "on") : ?>
									<a href="<?php echo cl_link('oauth/vkontakte'); ?>" class="social-login-btn vkontakte">
										<button class="btn btn-custom main-inline lg btn-block" type="button">
											<span class="d-inline-flex flex-wn align-items-center">
												<span class="flex-item btn-icon">
													<?php echo cl_icon('logos/logo-vk'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate("SignIn with Vkontakte"); ?>
												</span>
											</span>
										</button>
									</a>
								<?php endif; ?>
								<?php if ($cl["config"]["instagram_status"] == "on") : ?>
									<a href="<?php echo cl_link('oauth/instagram'); ?>" class="social-login-btn instagram">
										<button class="btn btn-custom main-inline lg btn-block" type="button">
											<span class="d-inline-flex flex-wn align-items-center">
												<span class="flex-item btn-icon">
													<?php echo cl_icon('logos/logo-instagram'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate("SignIn with Instagram"); ?>
												</span>
											</span>
										</button>
									</a>
								<?php endif; ?>
							</div>
						</div>
					
					<?php else : ?>
						<button type="button" class="btn btn-custom main-inline lg btn-block" data-toggle="modal" data-target="#loginModal"><?php echo cl_translate("Log in"); ?></button>
		
			<?php endif; ?>
				</div>
				<p><?php echo cl_translate("by_signing"); ?> <a href="<?php echo cl_link('terms_of_use'); ?>"> <?php echo cl_translate("Terms of Use"); ?> </a> <?php echo cl_translate("And"); ?> <a href="<?php echo cl_link('privacy_policy'); ?>"><?php echo cl_translate("Privacy policy"); ?></a>, <?php echo cl_translate("including"); ?> <a href="<?php echo cl_link('cookies_policy'); ?>"><?php echo cl_translate("cookies_policy"); ?> </a>.</p>
			</div>
			<?php echo cl_template('main/footer'); ?>
			<?php if (not_empty($cl["gads_vert"])) : ?>
				<div class="cl-google-ads">
					<?php echo $cl["gads_vert"]; ?>
				</div>
			<?php endif; ?>
		</div>
	</div>
</div>
