<div class="right-sb-container sidebar" data-app="right-sidebar">
	<div class="sidebar__inner">
		<div class="main-search-bar-container">
			<form class="form" id="vue-main-search-app1" v-on:submit="search_onsubmit" autocomplete="off">
				<div class="input-holder">
					<input v-model="search_query" v-on:input="search" type="text" class="form-control"
						placeholder="<?php echo cl_translate("Search for people, hashtags..", array('name' => $cl['config']['name'])); ?>">
					<a href="#">
						<?php echo cl_ikon('search'); ?>
					</a>
					<span class="spinner-icon" v-if="searching">
						<?php echo cl_ikon('spinner-icon'); ?>
					</span>
					<span v-on:click="cancel" class="clear-result" v-else-if="search_result">
						<?php echo cl_ikon('close'); ?>
					</span>
				</div>
				<div class="search-result-holder" v-show="search_result">
					<div class="search-result-body">
						<ul class="result-list" data-an="result"></ul>
					</div>
					<div class="search-result-footer" v-bind:class="{'disabled': (advanced_search != true) }">
						<a v-bind:href="search_page_url" data-spa="true">
							<?php echo cl_translate('Advanced search'); ?>
						</a>
					</div>
				</div>
			</form>
		</div>
		<div class="sidebar_login">
			<div class="social_login">
				<h2>
					<?php echo cl_translate("New to {@name@}?", array(
						"name" => $cl["config"]["name"]
					)); ?></h2>
				<p><?php echo cl_translate("new_to_desc"); ?></p>
				<div class="social_button">

					<?php if (in_array("on", array($cl["config"]["instagram_status"], $cl["config"]["vkontakte_status"], $cl["config"]["discord_status"], $cl["config"]["facebook_oauth"], $cl["config"]["linkedin_oauth"], $cl["config"]["google_oauth"], $cl["config"]["twitter_oauth"]))) : ?>

						<div class="form-group oauth-login-providers">
							<?php if ($cl["config"]["google_oauth"] == "on") : ?>
								<a href="<?php echo cl_link('oauth/google'); ?>" class="social-login-btn google">
									<button class="btn btn-custom main-inline lg btn-block" type="button" style="background-color: #f7faff !important;border-color: #d2e3fc!important;">
										<span class="d-inline-flex flex-wn align-items-center">
											<span class="flex-item btn-icon">
												<?php echo cl_icon('logos/google-logo-2'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate("SignIn with Google"); ?>
											</span>
										</span>
									</button>
								</a>
							<?php endif; ?>
							<?php if ($cl["config"]["facebook_oauth"] == "on") : ?>
								<a href="<?php echo cl_link('oauth/facebook'); ?>" class="social-login-btn facebook">
									<button class="btn btn-custom main-inline lg btn-block" type="button">
										<span class="d-inline-flex flex-wn align-items-center">
											<span class="flex-item btn-icon">
												<?php echo cl_icon('logos/logo-facebook'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate("SignIn with Facebook"); ?>
											</span>
										</span>
									</button>
								</a>
							<?php endif; ?>
							<?php if ($cl["config"]["twitter_oauth"] == "on") : ?>
								<a href="<?php echo cl_link('oauth/twitter'); ?>" class="social-login-btn twitter">
									<button class="btn btn-custom main-inline lg btn-block" type="button">
										<span class="d-inline-flex flex-wn align-items-center">
											<span class="flex-item btn-icon">
												<?php echo cl_icon('logos/logo-twitter'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate("SignIn with Twitter"); ?>
											</span>
										</span>
									</button>
								</a>
							<?php endif; ?>
							<div class="form-cta-link forgot">
								<a data-toggle="collapse" data-target="#collapseLogin" aria-expanded="false" aria-controls="collapseLogin">
									<span class="btn-outline">
										<?php echo cl_icon('more_horiz'); ?>
										<?php echo cl_translate("More Social Login"); ?>
									</span>
								</a>
							</div>
							<div class="collapse" id="collapseLogin">
								<?php if ($cl["config"]["linkedin_oauth"] == "on") : ?>
									<a href="<?php echo cl_link('oauth/linkedin'); ?>" class="social-login-btn linkedin">
										<button class="btn btn-custom main-inline lg btn-block" type="button">
											<span class="d-inline-flex flex-wn align-items-center">
												<span class="flex-item btn-icon">
													<?php echo cl_icon('logos/logo-linkedin'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate("SignIn with LinkedIn"); ?>
												</span>
											</span>
										</button>
									</a>
								<?php endif; ?>
								<?php if ($cl["config"]["discord_status"] == "on") : ?>
									<a href="<?php echo cl_link('oauth/discord'); ?>" class="social-login-btn discord">
										<button class="btn btn-custom main-inline lg btn-block" type="button">
											<span class="d-inline-flex flex-wn align-items-center">
												<span class="flex-item btn-icon">
													<?php echo cl_icon('logos/logo-discord'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate("SignIn with Discord"); ?>
												</span>
											</span>
										</button>
									</a>
								<?php endif; ?>
								<?php if ($cl["config"]["vkontakte_status"] == "on") : ?>
									<a href="<?php echo cl_link('oauth/vkontakte'); ?>" class="social-login-btn vkontakte">
										<button class="btn btn-custom main-inline lg btn-block" type="button">
											<span class="d-inline-flex flex-wn align-items-center">
												<span class="flex-item btn-icon">
													<?php echo cl_icon('logos/logo-vk'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate("SignIn with Vkontakte"); ?>
												</span>
											</span>
										</button>
									</a>
								<?php endif; ?>
								<?php if ($cl["config"]["instagram_status"] == "on") : ?>
									<a href="<?php echo cl_link('oauth/instagram'); ?>" class="social-login-btn instagram">
										<button class="btn btn-custom main-inline lg btn-block" type="button">
											<span class="d-inline-flex flex-wn align-items-center">
												<span class="flex-item btn-icon">
													<?php echo cl_icon('logos/logo-instagram'); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate("SignIn with Instagram"); ?>
												</span>
											</span>
										</button>
									</a>
								<?php endif; ?>
							</div>
						</div>

					<?php else : ?>
						<button type="button" class="btn btn-custom main-inline lg btn-block" data-toggle="modal" data-target="#loginModal"><?php echo cl_translate("Log in"); ?></button>

					<?php endif; ?>
				</div>
				<p><?php echo cl_translate("by_signing"); ?> <a href="<?php echo cl_link('terms_of_use'); ?>"> <?php echo cl_translate("Terms of Use"); ?> </a> <?php echo cl_translate("And"); ?> <a href="<?php echo cl_link('privacy_policy'); ?>"><?php echo cl_translate("Privacy policy"); ?></a>, <?php echo cl_translate("including"); ?> <a href="<?php echo cl_link('cookies_policy'); ?>"><?php echo cl_translate("cookies_policy"); ?> </a>.</p>
			</div>

			<!-- Edited by Kevin -->
			<?php
			/*
			if (not_empty($cl["gads_vert"])) : ?>
				<div class="cl-google-ads">
					<?php echo $cl["gads_vert"]; ?>
				</div>
			<?php endif; 
			*/
			?>

		</div>
		<div class="topical-posts">
			<div class="topical-posts__header">
				<h4><?php echo cl_translate("hot_symbols_for_you"); ?></h4>
			</div>
			<div class="spinner-container" style="display: none;">
				<div class="spinner"></div>
			</div>
			<div class="topical-posts__body" id="topical-posts-body">
				<?php
				$count = 0;
				global $db;
				foreach ($cl['hot_symbols'] as $row):
					if ($count >= 5) break;
					$symbol = $row['symbol'];
					$db        = $db->where('username', $symbol);
					$symbol_data = $db->getOne(T_SYMBOLS, 'avatar');
					if (empty($symbol_data)) { // Check if data is found
						continue;
					}
					$symbol_data['avatar']       = cl_get_media($symbol_data['avatar']);
					$count++;
				?>
					<div class="topical-posts__item">
						<a class="htag" href="<?php echo cl_link(cl_strf("symbol/%s", ($row['symbol']))); ?>">
							<img src="<?php echo $symbol_data['avatar']; ?>" style="height: 17px; border-radius:50%; margin-right: 2px;" alt="">
							<b>$</b>
							<strong><?php echo ($row['symbol']); ?></strong>
							<span><?php echo ($row['total']); ?> <?php echo cl_translate("Posts"); ?></span>
						</a>
						<span> <a href="<?php echo ($row['url']); ?>" class="icon" data-spa="true">
								<?php echo cl_ikon('pub-more'); ?>
							</a></span>
					</div>
				<?php endforeach; ?>
			</div>
			<?php if (count($cl['hot_symbols']) > 5): ?>
				<div class="topical-posts__footer">
					<a href="<?php echo cl_link("symbols"); ?>" data-spa="true">
						<?php echo cl_translate("Show more"); ?>
					</a>
				</div>
			<?php endif ?>
		</div>
		<div class="topical-posts">
			<div class="topical-posts__header">
				<h4>
					<?php echo cl_translate("hot_topics_for_you"); ?>
				</h4>
			</div>
			<?php if (not_empty($cl['hot_topics'])): ?>
				<div class="topical-posts__body">
					<?php $limited_topics = array_slice($cl['hot_topics'], 0, 5); ?>
					<?php foreach ($limited_topics as $row): ?>
						<div class="topical-posts__item">
							<a class="htag" href="<?php echo ($row['url']); ?>" data-spa="true">
								<b>#</b>
								<strong>
									<?php echo ($row['tag']); ?>
								</strong>
								<span><?php echo ($row['total']); ?> <?php echo cl_translate("Posts"); ?></span>
							</a>
							<span> <a href="<?php echo ($row['url']); ?>" class="icon" data-spa="true">
									<?php echo cl_ikon('pub-more'); ?>
								</a></span>
						</div>
					<?php endforeach; ?>
				</div>
				<?php if (count($cl['hot_topics']) > 5): ?>
					<div class="topical-posts__footer">
						<a href="<?php echo cl_link("trending"); ?>" data-spa="true">
							<?php echo cl_translate("Show more"); ?>
						</a>
					</div>
				<?php endif ?>
			<?php else: ?>
				<div class="topical-posts__placeholder">
					<?php echo cl_translate("Here will be a (#hashtag) list of the most relevant topics and events"); ?>
				</div>
			<?php endif; ?>
		</div>
		<div class="site_rule"><?php echo cl_template('main/footer'); ?></div>
		
	</div>
</div>
<script>
	new Vue({
		el: "#vue-main-search-app1",
		data: {
			searching: false,
			search_query: "",
			advanced_search: false,
			search_result: false
		},
		computed: {
			search_page_url: function() {
				if (this.search_query.length > 2) {
					var search_htags_url = "<?php echo cl_link('search/htags?q={0}'); ?>";
					var search_users_url = "<?php echo cl_link('search/people?q={0}'); ?>";
					var search_symbols_url = "<?php echo cl_link('search/symbols?q={0}'); ?>";
					this.advanced_search = true;

					if (this.search_query.charAt(0) == '#') {
						return search_htags_url.format(this.search_query.replace('#', ''));
					} else if (this.search_query.charAt(0) == '$') {
						return search_symbols_url.format(this.search_query.replace('$', ''));
					} else {
						return search_users_url.format(this.search_query);
					}
				} else {
					this.advanced_search = false;
					return "javascript:void(0);";
				}
			},
			query_type: function() {
				if (this.search_query.charAt(0) == '#') {
					return 'htags';
				} else if (this.search_query.charAt(0) == '$') {
					return 'symbols';
				} else {
					return 'users';
				}
			}
		},
		methods: {
			search_onsubmit: function(e = false) {
				e.preventDefault();
				this.search();
			},
			search: function() {
				if (this.search_query.length > 1) {
					var _app_ = this;
					delay(function() {
						$.ajax({
							url: '<?php echo cl_link('native_api/main/search'); ?>',
							type: 'GET',
							dataType: 'json',
							data: {
								query: _app_.search_query.replace(/^[#\$]/, ''), // Remove # or $ at the beginning
								type: _app_.query_type
							},
							beforeSend: function() {
								_app_.searching = true;
							}
						}).done(function(data) {
							_app_.search_result = true;
							$(_app_.$el).find('[data-an="result"]').html($(data.html));
						}).always(function() {
							_app_.searching = false;
						});
					}, 800);
				} else this.search_result = false;
			},
			cancel: function() {
				var _app_ = this;
				_app_.searching = false;
				_app_.search_query = "";
				_app_.advanced_search = false;
				_app_.search_result = false;

				$(_app_.$el).find('[data-an="result"]').empty('');
			}
		}
	});
</script>