<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div style="display: flex; flex-direction: column; height: 100%; gap: 20px">
			<div style="border-radius: 10px;">
				<div class="cp h-mobile" style="margin-bottom: 10px; margin-left:25px;">
					<a href="<?php echo cl_link("/"); ?>" style="align-items:center;">
						<img src="{%config site_logo%}" alt="Logo">
						<span class="ml11">
							<span class="text-wrapper">
								<span class="line line1"></span> 
								<span style="font-family:sans-serif" class="letters">{%config name%}</span>
							</span>
						</span>
					</a>
				</div>
				<div class="user-info h-laptop">
					<div class="left_account">
						
						<h6>Account Info</h6>
						<a href="#" onclick="SMColibri.toggleSB();" class="b_close"> <svg viewBox="0 0 24 24" aria-hidden="true"
								class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-z80fyv r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-19wmn03">
								<g>
									<path
										d="M10.59 12L4.54 5.96l1.42-1.42L12 10.59l6.04-6.05 1.42 1.42L13.41 12l6.05 6.04-1.42 1.42L12 13.41l-6.04 6.05-1.42-1.42L10.59 12z">
									</path>
								</g>
							</svg></a>
					</div>
					<div class="mobile_menu" style="display:flex;">
						<div class="avatar">
							<img src="<?php echo ($me['avatar']); ?>" alt="Avatar">
						</div>
						<div class="uname">
							<h5 style="margin-bottom: 0px;">
								<span class="user-name-holder">
									<?php echo ($me['name']); ?>
								</span>
								<p class="<?php if ($cl['li']['owner']['verified'] == '1') {
									echo ('verified-badge');
								} ?>" style="display:inline-block;"></p>
							</h5>
							<a href="<?php echo ($me['url']); ?>" data-spa="true">
								@<?php echo ($me['username']); ?>
							</a>
						</div>
					</div>
				</div>
				<div class="account-stats h-laptop">
					<div class="stat-holder">
						<?php if (not_empty($me['following'])): ?>
							<a href="<?php echo (cl_strf('%s/following', $cl['me']['url'])); ?>" data-spa="true">
								<b data-an="total-following">
									<?php echo cl_number($me['following']); ?>
								</b>
								<span>
									<?php echo cl_translate('Following'); ?>
								</span>
							</a>
						<?php else: ?>
							<b data-an="total-following">
								<?php echo cl_number($me['following']); ?>
							</b>
							<span>
								<?php echo cl_translate('Following'); ?>
							</span>
						<?php endif; ?>
					</div>
					<div class="stat-holder">
						<?php if (not_empty($me['followers'])): ?>
							<a href="<?php echo (cl_strf('%s/followers', $cl['me']['url'])); ?>" data-spa="true">
								<b data-an="total-followers">
									<?php echo cl_number($me['followers']); ?>
								</b>
								<span>
									<?php echo cl_translate('Followers'); ?>
								</span>
							</a>
						<?php else: ?>
							<b data-an="total-followers">
								<?php echo cl_number($me['followers']); ?>
							</b>
							<span>
								<?php echo cl_translate('Followers'); ?>
							</span>
						<?php endif; ?>
					</div>
				</div>
				<div class="sidebar-v-nav-wrapper">
					<ul class="sidebar-v-nav">
						<li data-navitem="home" onclick="window.location.href='/./'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'home') {	/* edited by kevin change into button with full width */
							echo ('active');
						} ?>">
							<span class="icon home">
								<?php echo cl_ikon('home'); ?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link('./'); ?>">
									<?php echo cl_translate('Home'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="explore" onclick="window.location.href='<?php echo cl_link('explore'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'explore') {	/* edited by kevin change into button with full width */
							echo ('active');
						} ?>">
							<span class="icon">
								<?php echo cl_ikon('explore'); ?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link("explore"); ?>">
									<?php echo cl_translate('search'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="notifications" onclick="window.location.href='<?php echo cl_link('notifications'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'notifications') {	/* edited by kevin change into button with full width */
							echo ('active');
						} ?>">
							<span class="icon">
								<?php echo cl_ikon('bell-h'); ?>
							</span>

							<span class="nav-item-holder">
								<a href="<?php echo cl_link("notifications"); ?>">
									<?php if(fetch_or_get($me['new_notifs']) > 0) { ?>  			<!-- edited by kevin notification only valid -->
										<span class="info-indicators" data-an="new-notifs">
											<?php echo fetch_or_get($me['new_notifs']); ?>
										</span>
									<?php } ?>														<!-- edited by kevin notification only valid -->
										<?php echo cl_translate('Notifications'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="chat" onclick="window.location.href='<?php echo cl_link('chats'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'chat') {	/* edited by kevin change into button with full width */
							echo ('active');
						} ?>">
							<span class="icon">
								<?php echo cl_ikon('envelope-h'); ?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link("chats"); ?>">
									<?php if(fetch_or_get($me['new_messages']) > 0) { ?>		<!-- edited by kevin notification only valid -->
										<span class="info-indicators" data-an="new-messages">
											<?php echo fetch_or_get($me['new_messages']); ?>
										</span>
									<?php } ?>													<!-- edited by kevin notification only valid -->
									<?php echo cl_translate('Messages'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="bookmarks" onclick="window.location.href='<?php echo cl_link('bookmarks'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'bookmarks') {	/* edited by kevin change into button with full width */
							echo ('active');
						} ?>">
							<span class="icon">
								<?php echo cl_ikon('bookmark'); ?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link("bookmarks"); ?>">
									<?php echo cl_translate('Bookmarks'); ?>
								</a>
							</span>
						</li>
						<?php if ($cl['config']['blue_account_system_status'] == 'off'): ?>
							<li data-navitem="trending" onclick="window.location.href='<?php echo cl_link('trending'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'trending') {	/* edited by kevin change into button with full width */
								echo ('active');
							} ?>">
								<span class="icon">
									<?php echo cl_ikon('activity'); ?>
								</span>
								<span class="nav-item-holder">
									<a href="<?php echo cl_link('trending'); ?>" data-spa="true">
										<?php echo cl_translate('actual'); ?>
									</a>
								</span>
							</li>
						<?php endif; ?>
						<!-- Blue Account -->
						<?php if ($cl['config']['blue_account_system_status'] == 'on'): ?>
							<?php if ($me["is_blue"] == 1): ?>
								<li data-navitem="trending" onclick="window.location.href='<?php echo cl_link('trending'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'trending') {	/* edited by kevin change into button with full width */
									echo ('active');
								} ?>">
									<span class="icon">
										<?php echo cl_ikon('activity'); ?>
									</span>
									<span class="nav-item-holder">
										<a href="<?php echo cl_link('trending'); ?>" data-spa="true">
											<?php echo cl_translate('actual'); ?>
										</a>
									</span>
								</li>
							<?php else: ?>
								<li data-navitem="blue_account" onclick="window.location.href='<?php echo cl_link('blue_account'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'blue_account') {	/* edited by kevin change into button with full width */
									echo ('active');
								} ?>">

									<span class="icon">
										<svg viewBox="0 0 24 24" aria-hidden="true"
											class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-lwhw9o r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-cnnz9e">
											<g>
												<path
													d="M15.704 8.99c.457-.05.891-.17 1.296-.35-.302.45-.685.84-1.125 1.15.004.1.006.19.006.29 0 2.94-2.269 6.32-6.421 6.32-1.274 0-2.46-.37-3.459-1 .177.02.357.03.539.03 1.057 0 2.03-.35 2.803-.95-.988-.02-1.821-.66-2.109-1.54.138.03.28.04.425.04.206 0 .405-.03.595-.08-1.033-.2-1.811-1.1-1.811-2.18v-.03c.305.17.652.27 1.023.28-.606-.4-1.004-1.08-1.004-1.85 0-.4.111-.78.305-1.11 1.113 1.34 2.775 2.22 4.652 2.32-.038-.17-.058-.33-.058-.51 0-1.23 1.01-2.22 2.256-2.22.649 0 1.235.27 1.647.7.514-.1.997-.28 1.433-.54-.168.52-.526.96-.992 1.23zM2 21h15c3.038 0 5.5-2.46 5.5-5.5 0-1.4-.524-2.68-1.385-3.65-.08-.09-.089-.22-.023-.32.574-.87.908-1.91.908-3.03C22 5.46 19.538 3 16.5 3H2v18zM16.5 5C18.433 5 20 6.57 20 8.5c0 1.01-.43 1.93-1.12 2.57-.468.43-.414 1.19.111 1.55.914.63 1.509 1.69 1.509 2.88 0 1.93-1.567 3.5-3.5 3.5H4V5h12.5z">
												</path>
											</g>
										</svg>
									</span>
									<span class="nav-item-holder">
										<a href="<?php echo cl_link("blue_account"); ?>" data-spa="true">
											{%config name%} <?php echo cl_translate('Blue'); ?>
										</a>
									</span>
								</li>
							<?php endif; ?>
						<?php endif; ?>
						<li data-navitem="profile" onclick="window.location.href='<?php echo ($me['url']); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'profile' && ($cl['prof_user']['id'] == $me['id'])) {	/* edited by kevin change into button with full width */
							echo ('active');
						} ?>">
							<span class="icon">
								<?php echo cl_ikon('user'); ?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo ($me["url"]); ?>">
									<?php echo cl_translate('Profile'); ?>
								</a>
							</span>
						</li>
						<li class="sidebar-v-nav-item">
							<span class="icon">
								<?php echo cl_ikon('more'); ?>
							</span>
							<span class="nav-item-holder dropdown" style="width:100%">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="width:100%; display:block">
									<?php echo cl_translate('More'); ?>
								</a>
								<div class="dropdown-menu dropdown-icons">
									<?php if (not_empty($cl['is_admin'])): ?>
										<a class="dropdown-item" href="<?php echo cl_link("admin_panel"); ?>" target="_blank">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('chart'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Control panel'); ?>
											</span>
										</a>
									<?php endif; ?>
									<?php if ($cl['config']['advertising_system'] == 'on'): ?>
										<a class="dropdown-item" href="<?php echo cl_link("wallet"); ?>" data-spa="true">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('credit-card'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Wallet'); ?> <b class="wallet">(
													<?php echo cl_money($me['wallet']); ?>)
												</b>
											</span>
										</a>

										<a class="dropdown-item" href="<?php echo cl_link("ads"); ?>" data-spa="true">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('feed'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Advertising'); ?>
											</span>
										</a>
									<?php endif; ?>
									<?php if ($cl['config']['affiliates_system'] == 'on'): ?>
										<a class="dropdown-item" href="<?php echo cl_link("affiliates"); ?>" data-spa="true">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('support-alt'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Affiliates'); ?>
											</span>
										</a>
									<?php endif; ?>
									<!-- Blue Account  -->
									<?php if ($cl['config']['blue_account_system_status'] == 'on'): ?>
										<?php if ($me["is_blue"] == 1): ?>
											<a class="dropdown-item" href="<?php echo cl_link("blue_features"); ?>"
												data-navitem="blue_features">

												<span class="flex-item dropdown-item-icon">
													<svg viewBox="0 0 24 24" aria-hidden="true"
														class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-lwhw9o r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-cnnz9e">
														<g>
															<path
																d="M15.704 8.99c.457-.05.891-.17 1.296-.35-.302.45-.685.84-1.125 1.15.004.1.006.19.006.29 0 2.94-2.269 6.32-6.421 6.32-1.274 0-2.46-.37-3.459-1 .177.02.357.03.539.03 1.057 0 2.03-.35 2.803-.95-.988-.02-1.821-.66-2.109-1.54.138.03.28.04.425.04.206 0 .405-.03.595-.08-1.033-.2-1.811-1.1-1.811-2.18v-.03c.305.17.652.27 1.023.28-.606-.4-1.004-1.08-1.004-1.85 0-.4.111-.78.305-1.11 1.113 1.34 2.775 2.22 4.652 2.32-.038-.17-.058-.33-.058-.51 0-1.23 1.01-2.22 2.256-2.22.649 0 1.235.27 1.647.7.514-.1.997-.28 1.433-.54-.168.52-.526.96-.992 1.23zM2 21h15c3.038 0 5.5-2.46 5.5-5.5 0-1.4-.524-2.68-1.385-3.65-.08-.09-.089-.22-.023-.32.574-.87.908-1.91.908-3.03C22 5.46 19.538 3 16.5 3H2v18zM16.5 5C18.433 5 20 6.57 20 8.5c0 1.01-.43 1.93-1.12 2.57-.468.43-.414 1.19.111 1.55.914.63 1.509 1.69 1.509 2.88 0 1.93-1.567 3.5-3.5 3.5H4V5h12.5z">
															</path>
														</g>
													</svg>
												</span>
												<span class="flex-item">

													<?php echo cl_translate('Blue features'); ?>

												</span>
											</a>
										<?php else: ?>
											<a class="dropdown-item" href="<?php echo cl_link('trending'); ?>" data-spa="true"
												data-navitem="trending">

												<span class="flex-item dropdown-item-icon">
													<svg viewBox="0 0 24 24" aria-hidden="true"
														class="r-1kihuf0 r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1472mwg r-mbgqwd r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-lrsllp"
														data-testid="icon">
														<g>
															<path
																d="M3 4.5C3 3.12 4.12 2 5.5 2h13C19.88 2 21 3.12 21 4.5v15c0 1.38-1.12 2.5-2.5 2.5h-13C4.12 22 3 20.88 3 19.5v-15zM5.5 4c-.28 0-.5.22-.5.5v15c0 .28.22.5.5.5h13c.28 0 .5-.22.5-.5v-15c0-.28-.22-.5-.5-.5h-13zM16 10H8V8h8v2zm-8 2h8v2H8v-2z">
															</path>
														</g>
													</svg>
												</span>
												<span class="flex-item">

													<?php echo cl_translate('actual'); ?>

												</span>
											</a>
										<?php endif; ?>
									<?php endif; ?>
									<?php if ($cl['config']['prem_account_system_status'] == 'on'): ?>
										<?php if ($me["is_premium"] == 1): ?>
											<a class="dropdown-item" href="<?php echo cl_link("premium_features"); ?>"
												data-navitem="premium_features">

												<span class="flex-item dropdown-item-icon">
													<svg viewBox="0 0 24 24" aria-hidden="true"
														class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"
														data-testid="icon">
														<g>
															<path
																d="M5 22H2v-3c0-1.654 1.346-3 3-3s3 1.346 3 3-1.346 3-3 3zm-1-2h1c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1v1zm7.594 1.282l-.336-1.145c-.271-.923-.664-1.807-1.166-2.627-.452-.736-.992-1.421-1.607-2.036-.626-.625-1.322-1.173-2.069-1.627-.821-.499-1.706-.888-2.63-1.157l-1.151-.335L5.312 7h5.192c.613-.636 2.015-2.077 2.758-2.744C15.673 2.09 20.704 2.003 20.918 2l1.025-.013-.013 1.025c-.003.213-.09 5.245-2.256 7.656-.643.715-2.004 2.043-2.671 2.688v5.239l-5.407 2.688h-.002zm.64-4.046c.207.396.393.802.557 1.217l2.21-1.099v-2.333l-2.768 2.214zm-3.839-4.468c.531.391 1.034.823 1.503 1.292.459.459.883.951 1.267 1.471l4.104-3.284c.269-.257 2.169-2.084 2.916-2.915 1.084-1.208 1.531-3.667 1.681-5.269-1.602.149-4.061.596-5.268 1.68-.832.748-2.658 2.647-2.916 2.916l-3.287 4.109zM5.47 11.154c.414.163.819.347 1.214.551l2.165-2.706H6.548l-1.077 2.154z">
															</path>
														</g>
													</svg>
												</span>
												<span class="flex-item">

													<?php echo cl_translate('Premium features'); ?>

												</span>
											</a>
										<?php else: ?>
											<a class="dropdown-item" href="<?php echo cl_link("premium_account"); ?>" data-spa="true"
												data-navitem="premium_account">

												<span class="flex-item dropdown-item-icon">
													<svg viewBox="0 0 24 24" aria-hidden="true"
														class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"
														data-testid="icon">
														<g>
															<path
																d="M5 22H2v-3c0-1.654 1.346-3 3-3s3 1.346 3 3-1.346 3-3 3zm-1-2h1c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1v1zm7.594 1.282l-.336-1.145c-.271-.923-.664-1.807-1.166-2.627-.452-.736-.992-1.421-1.607-2.036-.626-.625-1.322-1.173-2.069-1.627-.821-.499-1.706-.888-2.63-1.157l-1.151-.335L5.312 7h5.192c.613-.636 2.015-2.077 2.758-2.744C15.673 2.09 20.704 2.003 20.918 2l1.025-.013-.013 1.025c-.003.213-.09 5.245-2.256 7.656-.643.715-2.004 2.043-2.671 2.688v5.239l-5.407 2.688h-.002zm.64-4.046c.207.396.393.802.557 1.217l2.21-1.099v-2.333l-2.768 2.214zm-3.839-4.468c.531.391 1.034.823 1.503 1.292.459.459.883.951 1.267 1.471l4.104-3.284c.269-.257 2.169-2.084 2.916-2.915 1.084-1.208 1.531-3.667 1.681-5.269-1.602.149-4.061.596-5.268 1.68-.832.748-2.658 2.647-2.916 2.916l-3.287 4.109zM5.47 11.154c.414.163.819.347 1.214.551l2.165-2.706H6.548l-1.077 2.154z">
															</path>
														</g>
													</svg>
												</span>
												<span class="flex-item">
													<?php echo cl_translate('Premium account'); ?>
												</span>
											</a>
										<?php endif; ?>
									<?php endif; ?>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="<?php echo cl_link("settings"); ?>" data-spa="true">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('settings'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Profile settings'); ?>
										</span>
									</a>
									<a class="dropdown-item" href="<?php echo cl_link("faqs"); ?>">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('help'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Help center'); ?>
										</span>
									</a>
									<a class="dropdown-item" href="javascript:void(0);" onclick="SMColibri.display_settings();">
										<span class="flex-item dropdown-item-icon">
											<div role="presentation" class="css-1dbjc4n"><svg viewBox="0 0 24 24"
													aria-hidden="true"
													class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr">
													<g>
														<path
															d="M15.692 11.205l6.383-7.216c.45-.45.45-1.18 0-1.628-.45-.45-1.178-.45-1.627 0l-7.232 6.402s.782.106 1.595.93c.548.558.882 1.51.882 1.51z">
														</path>
														<path
															d="M17.45 22.28H3.673c-1.148 0-2.083-.946-2.083-2.11V7.926c0-1.165.934-2.112 2.082-2.112h5.836c.414 0 .75.336.75.75s-.336.75-.75.75H3.672c-.32 0-.583.274-.583.612V20.17c0 .336.26.61.582.61h13.78c.32 0 .583-.273.583-.61v-6.28c0-.415.336-.75.75-.75s.75.335.75.75v6.28c0 1.163-.934 2.11-2.084 2.11z">
														</path>
													</g>
												</svg><svg viewBox="0 0 24 24" aria-hidden="true"
													class="r-1cvl2hr r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1d2f490 r-1b7u577 r-dnmrzs r-u8s1d r-1plcrui r-ipm5af r-lrvibr">
													<g>
														<path
															d="M8.18 16.99c-.19.154-.476.032-.504-.21-.137-1.214-.234-4.053 1.483-5.943.908-1 3.02-1.52 4.475-.198s1.14 3.473.23 4.473c-2.07 2.15-3.428.058-5.686 1.878z">
														</path>
													</g>
												</svg></div>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Display'); ?>
										</span>
									</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="<?php echo cl_link("logout"); ?>">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('exit'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Logout'); ?>
										</span>
									</a>
								</div>
							</span>
						</li>
					</ul>
				</div>
				<div class="mobile-sb-footer">
					<?php echo cl_template('main/footer'); ?>
				</div>
				<a href="#" data-toggle="modal" data-target="#add_new_post">
					<div class="tweet h-laptop" style="position: fixed; float: right; right: 20px; bottom: 60px;"> <span
							class="icon">
							<svg viewBox="0 0 24 24" aria-hidden="true"
								class="r-jwli3a r-4qtqp9 r-yyyyoo r-1472mwg r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-lrsllp">
								<g>
									<path
										d="M23 3c-6.62-.1-10.38 2.421-13.05 6.03C7.29 12.61 6 17.331 6 22h2c0-1.007.07-2.012.19-3H12c4.1 0 7.48-3.082 7.94-7.054C22.79 10.147 23.17 6.359 23 3zm-7 8h-1.5v2H16c.63-.016 1.2-.08 1.72-.188C16.95 15.24 14.68 17 12 17H8.55c.57-2.512 1.57-4.851 3-6.78 2.16-2.912 5.29-4.911 9.45-5.187C20.95 8.079 19.9 11 16 11zM4 9V6H1V4h3V1h2v3h3v2H6v3H4z">
									</path>
								</g>
							</svg>
						</span></div>
				</a>
				<div class="publish-post-btn">
					<button class="btn btn-custom main-inline lg home btn-block" data-toggle="modal"
						data-target="#add_new_post">
						<?php echo cl_translate('New post'); ?>
					</button>
				</div>
			</div>
			<!-- <div style="background-color: var(--smc-main-bg-color); border-radius: 10px; flex: 1;">
			</div> -->
		</div>
		<div class="user-info h-mobile" style="margin-left: 25px; position: fixed; bottom: 15px; flex-direction: row; background-color: var(--smc-main-bg-color); border-radius: 10px; padding: 14px 0px 14px 14px;">
			<div class="avatar">
				<img src="<?php echo ($me['avatar']); ?>" alt="Avatar">
			</div>
			<div class="uname">
				<h5 style="margin-bottom: 0px; font-size:15px; font-weight: 700;">
					<span class="user-name-holder">
						<?php echo ($me['name']); ?>
					</span>
					<p class="<?php if ($me['verified'] == '1') {
						echo ('verified-badge');
					} ?>" style="display:inline-block;"></p>
				</h5>
				<a href="<?php echo ($me['url']); ?>" data-spa="true" style="opacity: 0.7;">
					@<?php echo ($me['username']); ?>
				</a>
				<span class="dropdown">
					<a href="#" class="profile-toggle" data-toggle="dropdown">
						<?php echo cl_ikon("three-dots"); ?>
					</a>
					<div class="dropdown-menu dropdown-icons profile">
						<h5 style="text-align: center; margin-top: 20px; margin-bottom:0px;">
							<span class="user-name-holder <?php if ($me['verified'] == '1') {
								echo ('verified-badge');
							} ?>">
								<?php echo ($me['name']); ?>
							</span>
						</h5>
						<h5 style="text-align: center; margin-bottom: 10px;">
							<a href="<?php echo ($me['url']); ?>" data-spa="true">
								@<?php echo ($me['username']); ?>
							</a>
						</h5>
						<a class="dropdown-item" href="javascript:void(0);" onclick="SMColibri.display_settings();">
							<span class="flex-item dropdown-item-icon">
								<?php echo cl_ikon('display'); ?>
							</span>
							<span class="flex-item">
								<?php echo cl_translate('Display'); ?>
							</span>
						</a>
						<!-- Premium Account -->
						<?php if ($cl['config']['prem_account_system_status'] == 'on'): ?>
							<?php if ($me["is_premium"] == 1): ?>
								<a class="dropdown-item" href="<?php echo cl_link("premium_features"); ?>"
									data-navitem="premium_features">
									<span class="flex-item dropdown-item-icon">
										<svg viewBox="0 0 24 24" aria-hidden="true"
											class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"
											data-testid="icon">
											<g>
												<path
													d="M5 22H2v-3c0-1.654 1.346-3 3-3s3 1.346 3 3-1.346 3-3 3zm-1-2h1c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1v1zm7.594 1.282l-.336-1.145c-.271-.923-.664-1.807-1.166-2.627-.452-.736-.992-1.421-1.607-2.036-.626-.625-1.322-1.173-2.069-1.627-.821-.499-1.706-.888-2.63-1.157l-1.151-.335L5.312 7h5.192c.613-.636 2.015-2.077 2.758-2.744C15.673 2.09 20.704 2.003 20.918 2l1.025-.013-.013 1.025c-.003.213-.09 5.245-2.256 7.656-.643.715-2.004 2.043-2.671 2.688v5.239l-5.407 2.688h-.002zm.64-4.046c.207.396.393.802.557 1.217l2.21-1.099v-2.333l-2.768 2.214zm-3.839-4.468c.531.391 1.034.823 1.503 1.292.459.459.883.951 1.267 1.471l4.104-3.284c.269-.257 2.169-2.084 2.916-2.915 1.084-1.208 1.531-3.667 1.681-5.269-1.602.149-4.061.596-5.268 1.68-.832.748-2.658 2.647-2.916 2.916l-3.287 4.109zM5.47 11.154c.414.163.819.347 1.214.551l2.165-2.706H6.548l-1.077 2.154z">
												</path>
											</g>
										</svg>
									</span>
									<span class="flex-item">

										<?php echo cl_translate('Premium features'); ?>

									</span>
								</a>
							<?php else: ?>
								<a class="dropdown-item" href="<?php echo cl_link("premium_account"); ?>" data-spa="true"
									data-navitem="premium_account">

									<span class="flex-item dropdown-item-icon">
										<svg viewBox="0 0 24 24" aria-hidden="true"
											class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"
											data-testid="icon">
											<g>
												<path
													d="M5 22H2v-3c0-1.654 1.346-3 3-3s3 1.346 3 3-1.346 3-3 3zm-1-2h1c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1v1zm7.594 1.282l-.336-1.145c-.271-.923-.664-1.807-1.166-2.627-.452-.736-.992-1.421-1.607-2.036-.626-.625-1.322-1.173-2.069-1.627-.821-.499-1.706-.888-2.63-1.157l-1.151-.335L5.312 7h5.192c.613-.636 2.015-2.077 2.758-2.744C15.673 2.09 20.704 2.003 20.918 2l1.025-.013-.013 1.025c-.003.213-.09 5.245-2.256 7.656-.643.715-2.004 2.043-2.671 2.688v5.239l-5.407 2.688h-.002zm.64-4.046c.207.396.393.802.557 1.217l2.21-1.099v-2.333l-2.768 2.214zm-3.839-4.468c.531.391 1.034.823 1.503 1.292.459.459.883.951 1.267 1.471l4.104-3.284c.269-.257 2.169-2.084 2.916-2.915 1.084-1.208 1.531-3.667 1.681-5.269-1.602.149-4.061.596-5.268 1.68-.832.748-2.658 2.647-2.916 2.916l-3.287 4.109zM5.47 11.154c.414.163.819.347 1.214.551l2.165-2.706H6.548l-1.077 2.154z">
												</path>
											</g>
										</svg>
									</span>
									<span class="flex-item">

										<?php echo cl_translate('Premium account'); ?>

									</span>
								</a>
							<?php endif; ?>
						<?php endif; ?>

						<a class="dropdown-item" href="<?php echo cl_link("settings"); ?>" data-spa="true">
							<span class="flex-item dropdown-item-icon">
								<?php echo cl_ikon('settings'); ?>
							</span>
							<span class="flex-item">
								<?php echo cl_translate('Profile settings'); ?>
							</span>
						</a>
						<a class="dropdown-item" href="<?php echo cl_link("logout"); ?>">
							<span class="flex-item dropdown-item-icon">
								<?php echo cl_ikon('exit'); ?>
							</span>
							<span class="flex-item">
								<?php echo cl_translate('Logout'); ?>
							</span>
						</a>
						<div class="account-stats">
							<div class="stat-holder">
								<a href="<?php echo ($me["url"]); ?>" data-spa="true">
									<b data-an="total-posts">
										<?php echo cl_number($me['posts']); ?>
									</b>
									<span>
										<?php echo cl_translate('Posts'); ?>
									</span>
								</a>
							</div>
							<div class="stat-holder">
								<?php if (not_empty($me['following'])): ?>
									<a href="<?php echo (cl_strf('%s/following', $cl['me']['url'])); ?>" data-spa="true">
										<b data-an="total-following">
											<?php echo cl_number($me['following']); ?>
										</b>
										<span>
											<?php echo cl_translate('Following'); ?>
										</span>
									</a>
								<?php else: ?>
									<b data-an="total-following">
										<?php echo cl_number($me['following']); ?>
									</b>
									<span>
										<?php echo cl_translate('Following'); ?>
									</span>
								<?php endif; ?>
							</div>
							<div class="stat-holder">
								<?php if (not_empty($me['followers'])): ?>
									<a href="<?php echo (cl_strf('%s/followers', $cl['me']['url'])); ?>" data-spa="true">
										<b data-an="total-followers">
											<?php echo cl_number($me['followers']); ?>
										</b>
										<span>
											<?php echo cl_translate('Followers'); ?>
										</span>
									</a>
								<?php else: ?>
									<b data-an="total-followers">
										<?php echo cl_number($me['followers']); ?>
									</b>
									<span>
										<?php echo cl_translate('Followers'); ?>
									</span>
								<?php endif; ?>
							</div>
						</div>
					</div>
				</span>
			</div>
		</div>

	</div>
	<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
			<?php echo cl_template('main/bottom_navbar'); ?>
		<?php endif; ?>
</div>

<style>
	.topical-posts-custom {
  color: var(--smc-main-text-color-2);
  width: 260px;
  overflow: hidden;
  display: block;
  margin-bottom: 5px;
  border: 0px solid var(--smc-main-border-color);
  background-color: var(--smc-main-bg-color-2);
  padding-top: 5px;
  padding-left: 15px;
  padding-right: 15px;
  padding-bottom: 10px;
  border-radius: 16px;
}
.test_content_break{
	word-break: break-all;
}
.left-extra-square{
  height: 80px;
  color: var(--smc-main-text-color-2);
  width: 260px;
  overflow: hidden;
  display: block;
  margin-bottom: 5px;
  border: 0px solid var(--smc-main-border-color);
  background-color: var(--smc-main-bg-color-2);
  padding-left: 15px;
  padding-right: 15px;
  padding-bottom: 10px;
  border-radius: 16px;
	
}
.nav-custom-style{

    padding: 13px 0px 11px 10px;
    /* border: 1px solid; */
    margin-left: -9px;
    background-color: var(--smc-main-bg-color);
    border-radius: 10px;
    position: fixed;
    bottom: 15px;
    flex-direction: row;

}

</style>