<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div class="cp h-mobile" style="margin-bottom: 10px;">
			<a href="<?php echo cl_link("/"); ?>" style="align-items:center;">
				<img src="{%config site_logo%}" alt="Logo">
				<span class="ml11">
					<span class="text-wrapper">
						<span class="line line1"></span> 
						<span style="font-family:sans-serif" class="letters">{%config name%}</span>
					</span>
				</span>
			</a>
		</div>
		<div class="user-info h-laptop">
			<div class="left_account">
				<div class="logo">
					<img src="{%config site_logo%}" alt="Logo">
				</div>
			</div>
			<div class="mobile_menu" style="display:flex;" style="cursor: pointer;">
				<div class="uname">
					<h2>Join Crypto Community</h2>
					<button class="left-login blue" data-toggle="modal" data-target="#signupModal">Sign up</button>
					<button class="left-login" data-toggle="modal" data-target="#loginModal">Sign in</button>
				</div>
			</div>
		</div>
		<hr/>
		<div class="sidebar-v-nav-wrapper">
			<ul class="sidebar-v-nav">
				<li data-navitem="home" onclick="window.location.href='/./'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'feed') {
																											echo ('active');
																										} ?>" style="cursor: pointer;">
					<span class="icon home">
						<?php
							echo cl_ikon('home');
						?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link('./'); ?>">
							<?php echo cl_translate('Home'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="explore" onclick="window.location.href='<?php echo cl_link('explore'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'explore') {
																																			echo ('active');
																																		} ?>" style="cursor: pointer;">
					<span class="icon">
						<?php
							echo cl_ikon('explore');
						?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link("explore"); ?>">
							<?php echo cl_translate('Explore'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="coins" onclick="window.location.href='<?php echo cl_link('coins'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'coins') {	/* edited by kevin change into button with full width */
					echo ('active');
				} ?>">
					<span class="icon">
						<?php
						// Check if the current page is 'connections' to use the active icon
						if ($cl['pn'] == 'coins') {
							echo cl_ikon('coins_active');
						} else {
							echo cl_ikon('coins');
						}
						?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link("coins"); ?>">
							<?php echo cl_translate('Coins'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="search" class="sidebar-v-nav-item" data-toggle = "modal" data-target = "#searchbox-dialog" >
					<span class="icon">
						<?php
							echo cl_ikon('search-m');
						?>
					</span>
					<span class="nav-item-holder">
						<a href="#">
							Search
						</a>
					</span>
				</li>
			</ul>
		</div>
		<div class="mobile-sb-footer ">
			<?php echo cl_template('main/footer'); ?>
		</div>
		<div class="bottom-fixed-btn-part bg-origin">
			<div class="under-login">
				<button class="left-login blue" data-toggle="modal" data-target="#signupModal">Sign up</button>
				<button class="left-login" data-toggle="modal" data-target="#loginModal">Sign in</button>
			</div>
		</div>
	</div>
</div>
<div class="guest_bottom">
	<div class="r-o96wvk"></div>
	<div class="guest_login">
		<div class="login_txt">
			<span style="display: flex; align-items: center;">
				<img class="icon" src="{%config site_logo%}" alt="" style="display: block; height: 50px;  border: 0;">
				<span>
					<h1><?php echo cl_translate("Cointweets"); ?></h1>
				</span>
			</span>

		</div>
		<div class="login_btn">
			<button class="left-login blue" data-toggle="modal" data-target="#signupModal">Sign up</button>
			<button class="left-login" data-toggle="modal" data-target="#loginModal">Sign in</button>
		</div>
	</div>
</div>

<?php echo cl_template('main/bottom_navbar'); ?>

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>				
				<img class="mx-auto h-20 mr-4" src="{%config site_logo%}" alt="Logo" class="logo_login">				
				<div class="close unvisible">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/login'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- Sign Up Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>				
				<img class="mx-auto h-20 mr-4" src="{%config site_logo%}" alt="Logo" class="logo_login">				
				<div class="close unvisible">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/register'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- Forgot Modal -->
<div class="modal fade" id="forgotModal" tabindex="-1" aria-labelledby="forgotModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/reset_password'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<?php echo cl_template('auth/scripts/app_master_script'); ?>
<style>
	.letters {
		font-family: sans-serif;
	}
</style>
<style>
	body main.main-content-container div.main-content-container-inner div.left-sb-container div.sidebar__inner div.mobile-sb-footer div.main-footer ul.footer-nav {
		margin-top: 17px;
	}
	body button.btn-custom.lg.home {
		margin-left: 0 !important;
	}
</style>