<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div class="cp h-mobile" style="margin-bottom: 10px; margin-left:25px;">
			<a href="<?php echo cl_link("/"); ?>" style="align-items:center;">
				<img src="{%config site_logo%}" alt="Logo">
				<span class="ml11">
					<span class="text-wrapper">
						<span class="line line1"></span> 
						<span style="font-family:sans-serif" class="letters">{%config name%}</span>
					</span>
				</span>
			</a>
		</div>
		<div class="user-info h-laptop">
			<div class="left_account">
				<h6>Account Info</h6>
				<a href="#" onclick="SMColibri.toggleSB();" class="b_close">
					<svg viewBox="0 0 24 24" aria-hidden="true" class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-z80fyv r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-19wmn03">
						<g>
							<path
								d="M10.59 12L4.54 5.96l1.42-1.42L12 10.59l6.04-6.05 1.42 1.42L13.41 12l6.05 6.04-1.42 1.42L12 13.41l-6.04 6.05-1.42-1.42L10.59 12z">
							</path>
						</g>
					</svg>
				</a>
			</div>
			<div class="mobile_menu" style="display:flex;" data-toggle="modal" data-target="#loginModal" style="cursor: pointer;">
				<div class="avatar">
					<img src="{%config site_logo%}" alt="Logo">
				</div>
				<div class="uname" data-toggle="modal">
					<h5 style="margin-bottom: 0px;">
						<span class="user-name-holder">
							Your Profile
						</span>
					</h5>
					<a data-spa="true" data-toggle="modal" data-target="#loginModal" style="cursor: pointer;">
						@account
					</a>
				</div>
			</div>
		</div>
		<div class="sidebar-v-nav-wrapper">
			<ul class="sidebar-v-nav">
				<li data-navitem="home" onclick="window.location.href='/./'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'feed') {	echo ('active'); } ?>" style="cursor: pointer;">
					<span class="icon home">
						<?php echo cl_ikon('home'); ?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link('./'); ?>">
							<?php echo cl_translate('Home'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="explore" onclick="window.location.href='<?php echo cl_link('explore'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'explore') { echo ('active'); } ?>" style="cursor: pointer;">
					<span class="icon">
						<?php echo cl_ikon('explore'); ?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link("explore"); ?>">
							<?php echo cl_translate('Explore'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="profile" onclick="" class="sidebar-v-nav-item" data-toggle="modal" data-target="#loginModal" style="cursor: pointer;">
					<span class="icon">
						<?php echo cl_ikon('user'); ?>
					</span>
					<span class="nav-item-holder">
						<a>
							<?php echo cl_translate('Profile'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="profile" onclick="" class="sidebar-v-nav-item" data-toggle="modal" data-target="#loginModal"  style="cursor: pointer;">
					<span class="icon">
						<?php echo cl_ikon('more'); ?>
					</span>
					<span class="nav-item-holder">
						<a>
							<?php echo cl_translate('More'); ?>
						</a>
					</span>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="guest_bottom">
	<div class="r-o96wvk"></div>
	<div class="guest_login">
		<div class="login_txt">
			<span style="display: flex; align-items: center;">
				<img class="icon" src="{%config site_logo%}" alt="" height="50" width="60" style="margin-right:26px; display: block; height: auto;  border: 0;">
				<span>
					<h1><?php echo cl_translate("dont_miss"); ?></h1>
					<h6><?php echo cl_translate("dont_miss_desc", array(
							"site_name" => $cl["config"]["name"]
						)); ?></h6>
				</span>
			</span>

		</div>
		<div class="login_btn">
			<button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#loginModal"><?php echo cl_translate("Log in"); ?></button>
			<button type="button" class="btn btn-light" data-toggle="modal" data-target="#signupModal"><?php echo cl_translate("Sign up"); ?></button>


		</div>
	</div>
</div>
<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/login'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- Sign Up Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/register'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- Forgot Modal -->
<div class="modal fade" id="forgotModal" tabindex="-1" aria-labelledby="forgotModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/reset_password'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<?php echo cl_template('auth/scripts/app_master_script'); ?>
<style>
	.letters{
		font-family: sans-serif;
	}
</style>