<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div style="display: flex; flex-direction: column; height: 100%;">
			<div style="border-radius: 10px;">
				<div class="cp h-mobile" style="margin-bottom: 10px; margin-left:25px;">
					<a href="<?php echo cl_link("/"); ?>" style="align-items:center;">
						<img src="{%config site_logo%}" alt="Logo">
						<span class="ml11">
							<span class="text-wrapper">
								<span class="line line1"></span>
								<span style="font-family:sans-serif" class="letters">{%config name%}</span>
							</span>
						</span>
					</a>
				</div>
				<div class="user-info h-laptop">
					<div class="left_account">

						<h6>Account Info</h6>
						<a href="#" onclick="SMColibri.toggleSB();" class="b_close"> <svg viewBox="0 0 24 24" aria-hidden="true"
								class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-z80fyv r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-19wmn03">
								<g>
									<path
										d="M10.59 12L4.54 5.96l1.42-1.42L12 10.59l6.04-6.05 1.42 1.42L13.41 12l6.05 6.04-1.42 1.42L12 13.41l-6.04 6.05-1.42-1.42L10.59 12z">
									</path>
								</g>
							</svg></a>
					</div>
					<div class="mobile_menu" style="display:flex;">
						<div class="avatar">
							<img src="<?php echo ($me['avatar']); ?>" alt="Avatar">
						</div>
						<div class="uname">
							<h5 style="margin-bottom: 0px;">
								<span class="user-name-holder">
									<?php echo ($me['name']); ?>
								</span>
								<p class="<?php if (isset($cl['li']['owner']['verified']) && $cl['li']['owner']['verified'] == '1') {
												echo ('verified-badge');
											} ?>" style="display:inline-block;"></p>
							</h5>
							<a href="<?php echo ($me['url']); ?>" data-spa="true">
								@<?php echo ($me['username']); ?>
							</a>
						</div>
					</div>
				</div>
				<div class="account-stats h-laptop">
					<div class="stat-holder">
						<?php if (not_empty($me['following'])): ?>
							<a href="<?php echo (cl_strf('%s/following', $cl['me']['url'])); ?>" data-spa="true">
								<b data-an="total-following">
									<?php echo cl_number($me['following']); ?>
								</b>
								<span>
									<?php echo cl_translate('Following'); ?>
								</span>
							</a>
						<?php else: ?>
							<b data-an="total-following">
								<?php echo cl_number($me['following']); ?>
							</b>
							<span>
								<?php echo cl_translate('Following'); ?>
							</span>
						<?php endif; ?>
					</div>
					<div class="stat-holder">
						<?php if (not_empty($me['followers'])): ?>
							<a href="<?php echo (cl_strf('%s/followers', $cl['me']['url'])); ?>" data-spa="true">
								<b data-an="total-followers">
									<?php echo cl_number($me['followers']); ?>
								</b>
								<span>
									<?php echo cl_translate('Followers'); ?>
								</span>
							</a>
						<?php else: ?>
							<b data-an="total-followers">
								<?php echo cl_number($me['followers']); ?>
							</b>
							<span>
								<?php echo cl_translate('Followers'); ?>
							</span>
						<?php endif; ?>
					</div>
				</div>
				<div class="sidebar-v-nav-wrapper">
					<ul class="sidebar-v-nav">
						<li data-navitem="home" onclick="window.location.href='/./'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'home') {	/* edited by kevin change into button with full width */
																													echo ('active');
																												} ?>">
							<span class="icon home">
								<?php
								// Check if the current page is 'connections' to use the active icon
								if ($cl['pn'] == 'home') {
									echo cl_ikon('home_active');
								} else {
									echo cl_ikon('home');
								}
								?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link('./'); ?>">
									<?php echo cl_translate('Home'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="explore" onclick="window.location.href='<?php echo cl_link('explore'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'explore') {	/* edited by kevin change into button with full width */
																																					echo ('active');
																																				} ?>">
							<span class="icon">
								<?php
								// Check if the current page is 'connections' to use the active icon
								if ($cl['pn'] == 'explore') {
									echo cl_ikon('explore_active');
								} else {
									echo cl_ikon('explore');
								}
								?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link("explore"); ?>">
									<?php echo cl_translate('search'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="coins" onclick="window.location.href='<?php echo cl_link('coins'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'coins') {	/* edited by kevin change into button with full width */
																																				echo ('active');
																																			} ?>">
							<span class="icon">
								<?php
								// Check if the current page is 'connections' to use the active icon
								if ($cl['pn'] == 'coins') {
									echo cl_ikon('coins_active');
								} else {
									echo cl_ikon('coins');
								}
								?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link("coins"); ?>">
									<?php echo cl_translate('Coins'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="notifications" onclick="window.location.href='<?php echo cl_link('notifications'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'notifications') {	/* edited by kevin change into button with full width */
																																								echo ('active');
																																							} ?>">
							<span class="icon">
								<?php
								// Check if the current page is 'connections' to use the active icon
								if ($cl['pn'] == 'notifications') {
									echo cl_ikon('bell_h_active');
								} else {
									echo cl_ikon('bell_h');
								}
								?>
							</span>

							<span class="nav-item-holder">
								<a href="<?php echo cl_link("notifications"); ?>">
									<?php if (fetch_or_get($me['new_notifs']) > 0) { ?> <!-- edited by kevin notification only valid -->
										<span class="info-indicators" data-an="new-notifs">
											<?php echo fetch_or_get($me['new_notifs']); ?>
										</span>
									<?php } ?> <!-- edited by kevin notification only valid -->
									<?php echo cl_translate('Notifications'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="chat" onclick="window.location.href='<?php echo cl_link('chats'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'chat') {	/* edited by kevin change into button with full width */
																																				echo ('active');
																																			} ?>">
							<span class="icon msg_icon">
								<?php
								// Check if the current page is 'connections' to use the active icon
								if ($cl['pn'] == 'chat') {
									echo cl_ikon('envelope-h_active');
								} else {
									echo cl_ikon('envelope-h');
								}
								?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link("chats"); ?>">
									<?php if (fetch_or_get($me['new_messages']) > 0) { ?> <!-- edited by kevin notification only valid -->
										<span class="info-indicators" data-an="new-messages">
											<?php echo fetch_or_get($me['new_messages']); ?>
										</span>
									<?php } ?> <!-- edited by kevin notification only valid -->
									<?php echo cl_translate('Messages'); ?>
								</a>
							</span>
						</li>
						<?php if ($cl['config']['blue_account_system_status'] == 'off'): ?>
							<li data-navitem="trending" onclick="window.location.href='<?php echo ($me['url']); ?>/watching'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'connections') {	/* edited by kevin change into button with full width */
																																							echo ('active');
																																						} ?>">
								<span class="icon watchlist_icon">
									<?php
									// Check if the current page is 'connections' to use the active icon
									if ($cl['pn'] == 'connections') {
										echo cl_ikon('watchlist_active');
									} else {
										echo cl_ikon('watchlist');
									}
									?>
								</span>
								<span class="nav-item-holder">
									<a href="<?php echo ($me['url']); ?>/watching" data-spa="true">
										Watchlist
									</a>
								</span>
							</li>
						<?php endif; ?>
						<!-- Blue Account -->
						<?php if ($cl['config']['blue_account_system_status'] == 'on'): ?>
							<?php if ($me["is_blue"] == 1): ?>
								<li data-navitem="trending" onclick="window.location.href='<?php echo ($me['url']); ?>/watching'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'connections') {	/* edited by kevin change into button with full width */
																																								echo ('active');
																																							} ?>">
									<span class="icon">
										<svg style="width: 1.0009765625em; height: 1em;vertical-align: middle;fill: currentColor;overflow: hidden;" viewBox="0 0 1025 1024" version="1.1" xmlns="http://www.w3.org/2000/svg">
											<path d="M858.3 80.5H387.8c-40.4-43.2-135.4-67-188.8-67-94.9 0-175.7 70.5-188.8 164.3-5.6 16-8.3 31.3-8.3 46.7V828c0 98.7 80.3 179.1 179.1 179.1h695.4c82 0 148.7-66.7 148.7-148.7v-611c0-92.1-74.8-166.9-166.8-166.9z m0 30.4c60 0 110.5 39.2 128.7 93.2H628.8l-183.4-93.2h412.9z m136.5 747.4c0 65.3-53.1 118.4-118.4 118.4H181C99 976.8 32.2 910 32.2 828V224.5c0-12.3 2.3-24.7 7-38l0.8-3.2c10.5-79.4 78.7-139.4 159-139.4 56.2 0 142.8 26.7 170 61.2l4.6 5.8h2.6l242.2 120.3h374.8c0.6 5.3 1.6 10.6 1.6 16.1v611z" fill=""></path>
											<path d="M203 840h790.7v27.8H203zM110.2 840h30.3v30.3h-30.3zM368.1 580.1l-20.3 111.2c-1.9 10.7 2.3 21.3 11 27.8 8.8 6.5 20.1 7.4 29.8 2.5l98.7-51.6 99.5 53.6c4.3 2.3 8.9 3.4 13.5 3.4 5.7 0 11.5-1.8 16.4-5.3 8.8-6.3 13.3-16.8 11.6-27.6l-18.6-109.8 81.8-78c7.8-7.5 10.7-18.6 7.5-29-3.3-10.4-12-17.8-22.7-19.5l-110.2-16.3-49-101.9c-4.7-9.8-14.4-15.9-25.2-16.1-9.7-0.5-20.7 5.8-25.6 15.5l-49.6 99.7-112 15.1c-10.7 1.5-19.6 8.8-23.1 19.1s-0.8 21.4 6.9 29.1l79.6 78.1z m52.7-111.2c9.2-1.2 17.2-6.9 21.5-15.3l49.2-97.2 47.2 98.3c4.1 8.4 12 14.3 21.2 15.7l107.7 16.8-78.8 75.2c-6.7 6.4-9.9 15.7-8.4 25l18.5 108.3-97.2-52.4c-4.2-2.3-8.8-3.4-13.4-3.4-4.4 0-8.9 1-13 3.1l-97 49.7 19.6-107.3c1.7-9.2-1.3-18.6-7.9-25.1l-77.2-76.9 108-14.5z" fill=""></path>
										</svg>
									</span>
									<span class="nav-item-holder">
										<a href="<?php echo ($me['url']); ?>/watching" data-spa="true">
											Watchlist
										</a>
									</span>
								</li>
							<?php else: ?>
								<li data-navitem="blue_account" onclick="window.location.href='<?php echo cl_link('blue_account'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'blue_account') {	/* edited by kevin change into button with full width */
																																										echo ('active');
																																									} ?>">

									<span class="icon">
										<svg viewBox="0 0 24 24" aria-hidden="true"
											class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-lwhw9o r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-cnnz9e">
											<g>
												<path
													d="M15.704 8.99c.457-.05.891-.17 1.296-.35-.302.45-.685.84-1.125 1.15.004.1.006.19.006.29 0 2.94-2.269 6.32-6.421 6.32-1.274 0-2.46-.37-3.459-1 .177.02.357.03.539.03 1.057 0 2.03-.35 2.803-.95-.988-.02-1.821-.66-2.109-1.54.138.03.28.04.425.04.206 0 .405-.03.595-.08-1.033-.2-1.811-1.1-1.811-2.18v-.03c.305.17.652.27 1.023.28-.606-.4-1.004-1.08-1.004-1.85 0-.4.111-.78.305-1.11 1.113 1.34 2.775 2.22 4.652 2.32-.038-.17-.058-.33-.058-.51 0-1.23 1.01-2.22 2.256-2.22.649 0 1.235.27 1.647.7.514-.1.997-.28 1.433-.54-.168.52-.526.96-.992 1.23zM2 21h15c3.038 0 5.5-2.46 5.5-5.5 0-1.4-.524-2.68-1.385-3.65-.08-.09-.089-.22-.023-.32.574-.87.908-1.91.908-3.03C22 5.46 19.538 3 16.5 3H2v18zM16.5 5C18.433 5 20 6.57 20 8.5c0 1.01-.43 1.93-1.12 2.57-.468.43-.414 1.19.111 1.55.914.63 1.509 1.69 1.509 2.88 0 1.93-1.567 3.5-3.5 3.5H4V5h12.5z">
												</path>
											</g>
										</svg>
									</span>
									<span class="nav-item-holder">
										<a href="<?php echo cl_link("blue_account"); ?>" data-spa="true">
											{%config name%} <?php echo cl_translate('Blue'); ?>
										</a>
									</span>
								</li>
							<?php endif; ?>
						<?php endif; ?>
						<li data-navitem="bookmarks" onclick="window.location.href='<?php echo cl_link('bookmarks'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'bookmarks') {	/* edited by kevin change into button with full width */
																																						echo ('active');
																																					} ?>">
							<span style="fill: var(--smc-main-text-color);" class="icon">
								<?php
								// Check if the current page is 'connections' to use the active icon
								if ($cl['pn'] == 'bookmarks') {
									echo cl_ikon('bookmark_active');
								} else {
									echo cl_ikon('bookmark');
								}
								?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo cl_link("bookmarks"); ?>">
									<?php echo cl_translate('Bookmarks'); ?>
								</a>
							</span>
						</li>
						<li data-navitem="profile" onclick="window.location.href='<?php echo ($me['url']); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'profile' && ($cl['prof_user']['id'] == $me['id'])) {	/* edited by kevin change into button with full width */
																																				echo ('active');
																																			} ?>">
							<span style="fill: var(--smc-main-text-color);" class="icon">
								<?php
								// Check if the current page is 'connections' to use the active icon
								if ($cl['pn'] == 'profile' && ($cl['prof_user']['id'] == $me['id'])) {
									echo cl_ikon('user_active');
								} else {
									echo cl_ikon('user');
								}
								?>
							</span>
							<span class="nav-item-holder">
								<a href="<?php echo ($me["url"]); ?>">
									<?php echo cl_translate('Profile'); ?>
								</a>
							</span>
						</li>
						<li class="sidebar-v-nav-item">
							<span class="icon">
								<?php echo cl_ikon('more'); ?>
							</span>
							<span class="nav-item-holder dropdown" style="width:100%">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="width:100%; display:block">
									<?php echo cl_translate('More'); ?>
								</a>
								<div class="dropdown-menu dropdown-icons">
									<?php if (not_empty($cl['is_admin'])): ?>
										<a class="dropdown-item" href="<?php echo cl_link("admin_panel"); ?>" target="_blank">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('chart'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Control panel'); ?>
											</span>
										</a>
									<?php endif; ?>
									<?php if ($cl['config']['advertising_system'] == 'on'): ?>
										<a class="dropdown-item" href="<?php echo cl_link("wallet"); ?>" data-spa="true">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('credit-card'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Wallet'); ?> <b class="wallet">(
													<?php echo cl_money($me['wallet']); ?>)
												</b>
											</span>
										</a>
										<a class="dropdown-item" href="<?php echo cl_link("ads"); ?>" data-spa="true">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('feed'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Advertising'); ?>
											</span>
										</a>
									<?php endif; ?>
									<?php if ($cl['config']['affiliates_system'] == 'on'): ?>
										<a class="dropdown-item" href="<?php echo cl_link("affiliates"); ?>" data-spa="true">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('support-alt'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Affiliates'); ?>
											</span>
										</a>
									<?php endif; ?>
									<!-- Blue Account  -->
									<?php if ($cl['config']['blue_account_system_status'] == 'on'): ?>
										<?php if ($me["is_blue"] == 1): ?>
											<a class="dropdown-item" href="<?php echo cl_link("blue_features"); ?>"
												data-navitem="blue_features">
												<span class="flex-item dropdown-item-icon">
													<svg viewBox="0 0 24 24" aria-hidden="true"
														class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-lwhw9o r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-cnnz9e">
														<g>
															<path
																d="M15.704 8.99c.457-.05.891-.17 1.296-.35-.302.45-.685.84-1.125 1.15.004.1.006.19.006.29 0 2.94-2.269 6.32-6.421 6.32-1.274 0-2.46-.37-3.459-1 .177.02.357.03.539.03 1.057 0 2.03-.35 2.803-.95-.988-.02-1.821-.66-2.109-1.54.138.03.28.04.425.04.206 0 .405-.03.595-.08-1.033-.2-1.811-1.1-1.811-2.18v-.03c.305.17.652.27 1.023.28-.606-.4-1.004-1.08-1.004-1.85 0-.4.111-.78.305-1.11 1.113 1.34 2.775 2.22 4.652 2.32-.038-.17-.058-.33-.058-.51 0-1.23 1.01-2.22 2.256-2.22.649 0 1.235.27 1.647.7.514-.1.997-.28 1.433-.54-.168.52-.526.96-.992 1.23zM2 21h15c3.038 0 5.5-2.46 5.5-5.5 0-1.4-.524-2.68-1.385-3.65-.08-.09-.089-.22-.023-.32.574-.87.908-1.91.908-3.03C22 5.46 19.538 3 16.5 3H2v18zM16.5 5C18.433 5 20 6.57 20 8.5c0 1.01-.43 1.93-1.12 2.57-.468.43-.414 1.19.111 1.55.914.63 1.509 1.69 1.509 2.88 0 1.93-1.567 3.5-3.5 3.5H4V5h12.5z">
															</path>
														</g>
													</svg>
												</span>
												<span class="flex-item">
													<?php echo cl_translate('Blue features'); ?>
												</span>
											</a>
										<?php else: ?>
											<a class="dropdown-item" href="<?php echo ($me['url']); ?>/watching" data-spa="true" data-navitem="watchings">
												<span class="flex-item dropdown-item-icon">
													<svg viewBox="0 0 24 24" aria-hidden="true"
														class="r-1kihuf0 r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1472mwg r-mbgqwd r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-lrsllp"
														data-testid="icon">
														<g>
															<path
																d="M3 4.5C3 3.12 4.12 2 5.5 2h13C19.88 2 21 3.12 21 4.5v15c0 1.38-1.12 2.5-2.5 2.5h-13C4.12 22 3 20.88 3 19.5v-15zM5.5 4c-.28 0-.5.22-.5.5v15c0 .28.22.5.5.5h13c.28 0 .5-.22.5-.5v-15c0-.28-.22-.5-.5-.5h-13zM16 10H8V8h8v2zm-8 2h8v2H8v-2z">
															</path>
														</g>
													</svg>
												</span>
												<span class="flex-item">
													Watchlist
												</span>
											</a>
										<?php endif; ?>
									<?php endif; ?>
									<?php if ($cl['config']['prem_account_system_status'] == 'on'): ?>
										<?php if ($me["is_premium"] == 1): ?>
											<a class="dropdown-item" href="<?php echo cl_link("premium_features"); ?>"
												data-navitem="premium_features">

												<span class="flex-item dropdown-item-icon">
													<svg viewBox="0 0 24 24" aria-hidden="true"
														class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"
														data-testid="icon">
														<g>
															<path
																d="M5 22H2v-3c0-1.654 1.346-3 3-3s3 1.346 3 3-1.346 3-3 3zm-1-2h1c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1v1zm7.594 1.282l-.336-1.145c-.271-.923-.664-1.807-1.166-2.627-.452-.736-.992-1.421-1.607-2.036-.626-.625-1.322-1.173-2.069-1.627-.821-.499-1.706-.888-2.63-1.157l-1.151-.335L5.312 7h5.192c.613-.636 2.015-2.077 2.758-2.744C15.673 2.09 20.704 2.003 20.918 2l1.025-.013-.013 1.025c-.003.213-.09 5.245-2.256 7.656-.643.715-2.004 2.043-2.671 2.688v5.239l-5.407 2.688h-.002zm.64-4.046c.207.396.393.802.557 1.217l2.21-1.099v-2.333l-2.768 2.214zm-3.839-4.468c.531.391 1.034.823 1.503 1.292.459.459.883.951 1.267 1.471l4.104-3.284c.269-.257 2.169-2.084 2.916-2.915 1.084-1.208 1.531-3.667 1.681-5.269-1.602.149-4.061.596-5.268 1.68-.832.748-2.658 2.647-2.916 2.916l-3.287 4.109zM5.47 11.154c.414.163.819.347 1.214.551l2.165-2.706H6.548l-1.077 2.154z">
															</path>
														</g>
													</svg>
												</span>
												<span class="flex-item">

													<?php echo cl_translate('Premium features'); ?>

												</span>
											</a>
										<?php else: ?>
											<a class="dropdown-item" href="<?php echo cl_link("premium_account"); ?>" data-spa="true"
												data-navitem="premium_account">

												<span class="flex-item dropdown-item-icon">
													<svg viewBox="0 0 24 24" aria-hidden="true"
														class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"
														data-testid="icon">
														<g>
															<path
																d="M5 22H2v-3c0-1.654 1.346-3 3-3s3 1.346 3 3-1.346 3-3 3zm-1-2h1c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1v1zm7.594 1.282l-.336-1.145c-.271-.923-.664-1.807-1.166-2.627-.452-.736-.992-1.421-1.607-2.036-.626-.625-1.322-1.173-2.069-1.627-.821-.499-1.706-.888-2.63-1.157l-1.151-.335L5.312 7h5.192c.613-.636 2.015-2.077 2.758-2.744C15.673 2.09 20.704 2.003 20.918 2l1.025-.013-.013 1.025c-.003.213-.09 5.245-2.256 7.656-.643.715-2.004 2.043-2.671 2.688v5.239l-5.407 2.688h-.002zm.64-4.046c.207.396.393.802.557 1.217l2.21-1.099v-2.333l-2.768 2.214zm-3.839-4.468c.531.391 1.034.823 1.503 1.292.459.459.883.951 1.267 1.471l4.104-3.284c.269-.257 2.169-2.084 2.916-2.915 1.084-1.208 1.531-3.667 1.681-5.269-1.602.149-4.061.596-5.268 1.68-.832.748-2.658 2.647-2.916 2.916l-3.287 4.109zM5.47 11.154c.414.163.819.347 1.214.551l2.165-2.706H6.548l-1.077 2.154z">
															</path>
														</g>
													</svg>
												</span>
												<span class="flex-item">
													<?php echo cl_translate('Premium account'); ?>
												</span>
											</a>
										<?php endif; ?>
									<?php endif; ?>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="<?php echo cl_link("settings"); ?>" data-spa="true">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('settings'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Profile settings'); ?>
										</span>
									</a>
									<a class="dropdown-item" href="<?php echo cl_link("faqs"); ?>">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('help'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Help center'); ?>
										</span>
									</a>
									<a class="dropdown-item" href="javascript:void(0);" onclick="SMColibri.display_settings();">
										<span class="flex-item dropdown-item-icon">
											<div role="presentation" class="css-1dbjc4n"><svg viewBox="0 0 24 24"
													aria-hidden="true"
													class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr">
													<g>
														<path
															d="M15.692 11.205l6.383-7.216c.45-.45.45-1.18 0-1.628-.45-.45-1.178-.45-1.627 0l-7.232 6.402s.782.106 1.595.93c.548.558.882 1.51.882 1.51z">
														</path>
														<path
															d="M17.45 22.28H3.673c-1.148 0-2.083-.946-2.083-2.11V7.926c0-1.165.934-2.112 2.082-2.112h5.836c.414 0 .75.336.75.75s-.336.75-.75.75H3.672c-.32 0-.583.274-.583.612V20.17c0 .336.26.61.582.61h13.78c.32 0 .583-.273.583-.61v-6.28c0-.415.336-.75.75-.75s.75.335.75.75v6.28c0 1.163-.934 2.11-2.084 2.11z">
														</path>
													</g>
												</svg><svg viewBox="0 0 24 24" aria-hidden="true"
													class="r-1cvl2hr r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1d2f490 r-1b7u577 r-dnmrzs r-u8s1d r-1plcrui r-ipm5af r-lrvibr">
													<g>
														<path
															d="M8.18 16.99c-.19.154-.476.032-.504-.21-.137-1.214-.234-4.053 1.483-5.943.908-1 3.02-1.52 4.475-.198s1.14 3.473.23 4.473c-2.07 2.15-3.428.058-5.686 1.878z">
														</path>
													</g>
												</svg></div>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Display'); ?>
										</span>
									</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="<?php echo cl_link("logout"); ?>">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('exit'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Logout'); ?>
										</span>
									</a>
								</div>
							</span>
						</li>
					</ul>
				</div>
				<div class="mobile-sb-footer">
					<?php echo cl_template('main/footer'); ?>
				</div>
				<a href="#" data-toggle="modal" data-target="#add_new_post">
					<div class="tweet h-laptop" style="position: fixed; float: right; right: 20px; bottom: 60px;"> 
						<span class="icon opacity-80">
							<img src="/themes/default/statics/img/new_post.png" alt="">
						</span>
					</div>
				</a>
				<div class="publish-post-btn">
					<button class="btn btn-custom main-inline lg home btn-block" data-toggle="modal"
						data-target="#add_new_post">
						<?php echo cl_translate('New post'); ?>
					</button>
				</div>
			</div>
			<div class="disclaimer topical-posts">
				Cointweets sources data from third parties and does not create the content. Content on the platform is not an offer, solicitation, or financial advice for buying or selling securities or investments.
			</div>
		</div>
		
		<div class="user-info h-mobile" style="margin-left: 16px; position: fixed; bottom: 15px; flex-direction: row; background-color: var(--smc-main-bg-color); border-radius: 10px; padding: 14px 0px 14px 14px;">
			<div class="avatar">
				<img src="<?php echo ($me['avatar']); ?>" alt="Avatar">
			</div>
			<div class="uname">
				<h5 style="margin-bottom: 0px; font-size:15px; font-weight: 700;">
					<span class="user-name-holder">
						<?php echo ($me['name']); ?>
					</span>
					<p class="<?php if ($me['verified'] == '1') {
									echo ('verified-badge');
								} ?>" style="display:inline-block;"></p>
				</h5>
				<a href="<?php echo ($me['url']); ?>" data-spa="true" style="opacity: 0.7;">
					@<?php echo ($me['username']); ?>
				</a>
				<span class="dropdown">
					<a href="#" class="profile-toggle" data-toggle="dropdown">
						<?php echo cl_ikon("three-dots"); ?>
					</a>
					<div class="dropdown-menu dropdown-icons profile">
						<h5 style="text-align: center; margin-top: 20px; margin-bottom:0px;">
							<span class="user-name-holder <?php if ($me['verified'] == '1') {
																echo ('verified-badge');
															} ?>">
								<?php echo ($me['name']); ?>
							</span>
						</h5>
						<h5 style="text-align: center; margin-bottom: 10px;">
							<a href="<?php echo ($me['url']); ?>" data-spa="true">
								@<?php echo ($me['username']); ?>
							</a>
						</h5>
						<a class="dropdown-item" href="javascript:void(0);" onclick="SMColibri.display_settings();">
							<span class="flex-item dropdown-item-icon">
								<?php echo cl_ikon('display'); ?>
							</span>
							<span class="flex-item">
								<?php echo cl_translate('Display'); ?>
							</span>
						</a>
						<!-- Premium Account -->
						<?php if ($cl['config']['prem_account_system_status'] == 'on'): ?>
							<?php if ($me["is_premium"] == 1): ?>
								<a class="dropdown-item" href="<?php echo cl_link("premium_features"); ?>"
									data-navitem="premium_features">
									<span class="flex-item dropdown-item-icon">
										<svg viewBox="0 0 24 24" aria-hidden="true"
											class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"
											data-testid="icon">
											<g>
												<path
													d="M5 22H2v-3c0-1.654 1.346-3 3-3s3 1.346 3 3-1.346 3-3 3zm-1-2h1c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1v1zm7.594 1.282l-.336-1.145c-.271-.923-.664-1.807-1.166-2.627-.452-.736-.992-1.421-1.607-2.036-.626-.625-1.322-1.173-2.069-1.627-.821-.499-1.706-.888-2.63-1.157l-1.151-.335L5.312 7h5.192c.613-.636 2.015-2.077 2.758-2.744C15.673 2.09 20.704 2.003 20.918 2l1.025-.013-.013 1.025c-.003.213-.09 5.245-2.256 7.656-.643.715-2.004 2.043-2.671 2.688v5.239l-5.407 2.688h-.002zm.64-4.046c.207.396.393.802.557 1.217l2.21-1.099v-2.333l-2.768 2.214zm-3.839-4.468c.531.391 1.034.823 1.503 1.292.459.459.883.951 1.267 1.471l4.104-3.284c.269-.257 2.169-2.084 2.916-2.915 1.084-1.208 1.531-3.667 1.681-5.269-1.602.149-4.061.596-5.268 1.68-.832.748-2.658 2.647-2.916 2.916l-3.287 4.109zM5.47 11.154c.414.163.819.347 1.214.551l2.165-2.706H6.548l-1.077 2.154z">
												</path>
											</g>
										</svg>
									</span>
									<span class="flex-item">

										<?php echo cl_translate('Premium features'); ?>

									</span>
								</a>
							<?php else: ?>
								<a class="dropdown-item" href="<?php echo cl_link("premium_account"); ?>" data-spa="true"
									data-navitem="premium_account">

									<span class="flex-item dropdown-item-icon">
										<svg viewBox="0 0 24 24" aria-hidden="true"
											class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-1b7u577 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr"
											data-testid="icon">
											<g>
												<path
													d="M5 22H2v-3c0-1.654 1.346-3 3-3s3 1.346 3 3-1.346 3-3 3zm-1-2h1c.551 0 1-.449 1-1s-.449-1-1-1-1 .449-1 1v1zm7.594 1.282l-.336-1.145c-.271-.923-.664-1.807-1.166-2.627-.452-.736-.992-1.421-1.607-2.036-.626-.625-1.322-1.173-2.069-1.627-.821-.499-1.706-.888-2.63-1.157l-1.151-.335L5.312 7h5.192c.613-.636 2.015-2.077 2.758-2.744C15.673 2.09 20.704 2.003 20.918 2l1.025-.013-.013 1.025c-.003.213-.09 5.245-2.256 7.656-.643.715-2.004 2.043-2.671 2.688v5.239l-5.407 2.688h-.002zm.64-4.046c.207.396.393.802.557 1.217l2.21-1.099v-2.333l-2.768 2.214zm-3.839-4.468c.531.391 1.034.823 1.503 1.292.459.459.883.951 1.267 1.471l4.104-3.284c.269-.257 2.169-2.084 2.916-2.915 1.084-1.208 1.531-3.667 1.681-5.269-1.602.149-4.061.596-5.268 1.68-.832.748-2.658 2.647-2.916 2.916l-3.287 4.109zM5.47 11.154c.414.163.819.347 1.214.551l2.165-2.706H6.548l-1.077 2.154z">
												</path>
											</g>
										</svg>
									</span>
									<span class="flex-item">

										<?php echo cl_translate('Premium account'); ?>

									</span>
								</a>
							<?php endif; ?>
						<?php endif; ?>

						<a class="dropdown-item" href="<?php echo cl_link("settings"); ?>" data-spa="true">
							<span class="flex-item dropdown-item-icon">
								<?php echo cl_ikon('settings'); ?>
							</span>
							<span class="flex-item">
								<?php echo cl_translate('Profile settings'); ?>
							</span>
						</a>
						<a class="dropdown-item" href="<?php echo cl_link("logout"); ?>">
							<span class="flex-item dropdown-item-icon">
								<?php echo cl_ikon('exit'); ?>
							</span>
							<span class="flex-item">
								<?php echo cl_translate('Logout'); ?>
							</span>
						</a>
						<div class="account-stats">
							<div class="stat-holder">
								<a href="<?php echo ($me["url"]); ?>" data-spa="true">
									<b data-an="total-posts">
										<?php echo cl_number($me['posts']); ?>
									</b>
									<span>
										<?php echo cl_translate('Posts'); ?>
									</span>
								</a>
							</div>
							<div class="stat-holder">
								<?php if (not_empty($me['following'])): ?>
									<a href="<?php echo (cl_strf('%s/following', $cl['me']['url'])); ?>" data-spa="true">
										<b data-an="total-following">
											<?php echo cl_number($me['following']); ?>
										</b>
										<span>
											<?php echo cl_translate('Following'); ?>
										</span>
									</a>
								<?php else: ?>
									<b data-an="total-following">
										<?php echo cl_number($me['following']); ?>
									</b>
									<span>
										<?php echo cl_translate('Following'); ?>
									</span>
								<?php endif; ?>
							</div>
							<div class="stat-holder">
								<?php if (not_empty($me['followers'])): ?>
									<a href="<?php echo (cl_strf('%s/followers', $cl['me']['url'])); ?>" data-spa="true">
										<b data-an="total-followers">
											<?php echo cl_number($me['followers']); ?>
										</b>
										<span>
											<?php echo cl_translate('Followers'); ?>
										</span>
									</a>
								<?php else: ?>
									<b data-an="total-followers">
										<?php echo cl_number($me['followers']); ?>
									</b>
									<span>
										<?php echo cl_translate('Followers'); ?>
									</span>
								<?php endif; ?>
							</div>
						</div>
					</div>
				</span>
			</div>
		</div>
	</div>
</div>

<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
	<?php echo cl_template('main/bottom_navbar'); ?>
<?php endif; ?>

<style>
	.topical-posts-custom {
		color: var(--smc-main-text-color-2);
		width: 260px;
		overflow: hidden;
		display: block;
		margin-bottom: 5px;
		border: 0px solid var(--smc-main-border-color);
		background-color: var(--smc-main-bg-color-2);
		padding-top: 5px;
		padding-left: 15px;
		padding-right: 15px;
		padding-bottom: 10px;
		border-radius: 16px;
	}

	.test_content_break {
		word-break: break-all;
	}

	.left-extra-square {
		height: 80px;
		color: var(--smc-main-text-color-2);
		width: 260px;
		overflow: hidden;
		display: block;
		margin-bottom: 5px;
		border: 0px solid var(--smc-main-border-color);
		background-color: var(--smc-main-bg-color-2);
		padding-left: 15px;
		padding-right: 15px;
		padding-bottom: 10px;
		border-radius: 16px;

	}

	.nav-custom-style {

		padding: 13px 0px 11px 10px;
		/* border: 1px solid; */
		margin-left: -9px;
		background-color: var(--smc-main-bg-color);
		border-radius: 10px;
		position: fixed;
		bottom: 15px;
		flex-direction: row;

	}
</style>