<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div class="cp h-mobile" style="margin-bottom: 10px; margin-left:25px;">
			<a href="<?php echo cl_link("/"); ?>">
				<img src="{%config site_logo%}" alt="Logo">
				<h1 class="ml11">
					<span class="text-wrapper">
						<span class="line line1"></span>
						<span class="letters">{%config name%}</span>
					</span>
				</h1>
			</a>
		</div>
		<div class="sidebar-v-nav-wrapper">
			<ul class="sidebar-v-nav">
				<li data-navitem="home" onclick="window.location.href='/./'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'feed') {	echo ('active'); } ?>" style="cursor: pointer;">
					<span class="icon home">
						<?php echo cl_ikon('home'); ?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link('./'); ?>">
							<?php echo cl_translate('Home'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="explore" onclick="window.location.href='<?php echo cl_link('explore'); ?>'" class="sidebar-v-nav-item <?php if ($cl['pn'] == 'explore') { echo ('active'); } ?>" style="cursor: pointer;">
					<span class="icon">
						<?php echo cl_ikon('explore'); ?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link("explore"); ?>" >
							<?php echo cl_translate('Explore'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="profile" onclick="" class="sidebar-v-nav-item" data-toggle="modal" data-target="#loginModal" style="cursor: pointer;">
					<span class="icon">
						<?php echo cl_ikon('user'); ?>
					</span>
					<span class="nav-item-holder">
						<a>
							<?php echo cl_translate('Profile'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="profile" onclick="" class="sidebar-v-nav-item" data-toggle="modal" data-target="#loginModal"  style="cursor: pointer;">
					<span class="icon">
						<?php echo cl_ikon('more'); ?>
					</span>
					<span class="nav-item-holder">
						<a>
							<?php echo cl_translate('More'); ?>
						</a>
					</span>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="guest_bottom">
	<div class="r-o96wvk"></div>
	<div class="guest_login">
		<div class="login_txt">
			<h1><?php echo cl_translate("Keep up with the crypto"); ?></h1>
			<h6><?php echo cl_translate("dont_miss_desc", array(
						"site_name" => $cl["config"]["name"]
					)); ?></h6>
		</div>
		<div class="login_btn">
			<button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#loginModal"><?php echo cl_translate("Log in"); ?></button>
			<button type="button" class="btn btn-light" data-toggle="modal" data-target="#signupModal"><?php echo cl_translate("Sign up"); ?></button>


		</div>
	</div>
</div>
<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/login'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- Sign Up Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/register'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<!-- Forgot Modal -->
<div class="modal fade" id="forgotModal" tabindex="-1" aria-labelledby="forgotModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="close">
					<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
				</div>
				<img src="{%config site_logo%}" alt="Logo" class="logo_login">

			</div>
			<div class="modal-body">
				<div class="guest-welcome">
					<div class="login-form">
						<?php echo cl_template('auth/reset_password'); ?>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
<?php echo cl_template('auth/scripts/app_master_script'); ?>



