<div class="timeline-container">
	<div class="timeline-header" data-el="tl-header">
		<div class="timeline-header__botline">
			<div class="lp">
				<div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
					<span class="go-back" onclick="SMColibri.go_back();">
						<?php echo cl_ikon('arrow-left'); ?>
					</span>
					<a href="<?php echo cl_link("settings/premium"); ?>" data-spa="true">
						<?php echo cl_translate("Premium features"); ?>
					</a>
				</div>
			</div>
			<div class="cp">

			</div>
			<div class="rp">

			</div>
		</div>
	</div>
	<div class="profile-settings">
		<div class="icon2">
			<img src="{%config theme_url%}/statics/img/loyalty-card.png">
		</div>
		<div class="profile-settings__title">
			<h4>
				<?php echo cl_translate("Premium user account settings"); ?>
			</h4>
		</div>

		<div class="profile-settings__content profile-settings__content_no-padding">
			<div class="settings-form">
				<div class="blue_desc">
					<!-- Download Video -->
					<span>
						<?php echo cl_icon('file_download'); ?>
						<?php echo cl_translate('Download video, audio'); ?>
					</span>
					<p class="help">
						<?php echo cl_translate("You can download videos, audios"); ?>
					</p>
					</hr>
					<!-- Download document -->
					<span>
						<?php echo cl_icon('file_download'); ?>
						<?php echo cl_translate('Download document'); ?>
					</span>
					<p class="help">
						<?php echo cl_translate("You can download document"); ?>
					</p>
				</div>
				<form class="form" id="cl-premium-features-vue-app" v-on:submit="submit_form($event)">
					<div class="form-group no-mb">
						<div class="form-toggle">
							<div class="form-toggle__lp">
								<?php echo cl_icon("hide_image"); ?>
							</div>
							<div class="form-toggle__mp">
								<span class="form-toggle__title">
									<?php echo cl_translate("Hide native ads"); ?>
								</span>
								<span class="form-toggle__desc">
									<?php echo cl_translate("Remove native user ads from my timeline"); ?>
								</span>
							</div>
							<div class="form-toggle__rp">
								<div class="form-check">
									<input name="disable_native_ads" type="checkbox" class="form-check-input" <?php if (not_empty($me["premium_settings"]["disable_native_ads"])) {
										echo ("checked");
									} ?>>
								</div>
							</div>
						</div>
					</div>
					<div class="form-group no-mb">
						<div class="form-toggle">
							<div class="form-toggle__lp">
								<?php echo cl_icon("disabled_visible"); ?>
							</div>
							<div class="form-toggle__mp">
								<span class="form-toggle__title">
									<?php echo cl_translate("Hide AdSense ads"); ?>
								</span>
								<span class="form-toggle__desc">
									<?php echo cl_translate("Remove AdSense (Google Ads, etc..) ads from my timeline and sidebars"); ?>
								</span>
							</div>
							<div class="form-toggle__rp">
								<div class="form-check">
									<input name="disable_adsense_ads" type="checkbox" class="form-check-input" <?php if (not_empty($me["premium_settings"]["disable_adsense_ads"])) {
										echo ("checked");
									} ?>>
								</div>
							</div>
						</div>
					</div>
					<div class="form-group padding-x-offset" v-if="unsuccessful_attempt">
						<div class="invalid-main-feedback">
							<?php echo cl_translate("Something went wrong while trying to save your changes, please try again later"); ?>
						</div>
					</div>
					<div class="form-group padding-x-offset" v-else>
						<div class="form-info-label">
							<?php echo cl_translate("Check the box of ads that you do not want to see on your account (Disabling ads speeds up content loading)"); ?>
						</div>
					</div>
					<input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>"
						name="hash">
					<div class="form-group padding-x-offset no-mb">
						<button v-if="submitting != true" type="submit" class="btn btn-block btn-custom main-inline lg">
							<?php echo cl_translate("Save changes"); ?>
						</button>
						<button v-else disabled="true" type="button" class="btn btn-block btn-custom main-inline lg">
							<?php echo cl_translate("Please wait"); ?>
						</button>
					</div>
				</form>
				<div class="blue_feat">
					<div class="profile-settings">

						<h5>
							<?php echo cl_translate("confirmation_funds_in_the_amount_of_will_b", array("price" => cl_html_el("strong", cl_money($cl["config"]["premium_account_mprice"])), "end_date" => cl_html_el("strong", date("d/m/Y", ($me["premium_ex_date"]))))); ?>
						</h5>

					</div>
				</div>
			</div>
		</div>
	</div>

	<script>
		"use strict";

		$(document).ready(function ($) {
			Vue.use(window.vuelidate.default);
			var VueValids = window.validators;

			new Vue({
				el: "#cl-premium-features-vue-app",
				data: {
					submitting: false,
					unsuccessful_attempt: false
				},
				methods: {
					submit_form: function (_self = null) {
						_self.preventDefault();

						var _app_ = this;

						$(_self.target).ajaxSubmit({
							url: "<?php echo cl_link("native_api/settings/save_premium_features_settings"); ?>",
							type: 'POST',
							dataType: 'json',
							beforeSend: function () {
								_app_.submitting = true;
								_app_.unsuccessful_attempt = false;
							},
							success: function (data) {
								if (data.status == 200) {
									cl_bs_notify("<?php echo cl_translate("Your changes has been successfully saved!"); ?>");
								}
								else {
									_app_.unsuccessful_attempt = true;
								}
							},
							complete: function () {
								_app_.submitting = false;
							}
						});
					}
				}
			});
		});
	</script>
</div>
<style>
	div.icon2 img {
		width: 200px;
		height: auto;
		margin-bottom: 20px;
	}

	body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-placeholder div.icon2 {
		line-height: 0px;
		margin-bottom: 35px;
		width: 100%;
		text-align: center;
	}

	.profile-settings {
		text-align: center;
		margin: 20px;
	}

	.profile-settings__content {
		text-align: left;
	}

	.blue_feat {
		width: auto;
		overflow: hidden;
		display: flex;
		border: 0px solid var(--smc-main-border-color);
		background-color: var(--smc-main-bg-color-2);
		border-radius: 16px;
		text-align: center;
		margin-top: 20px;
	}

	.blue_desc .help {
		text-align: left !important;
		margin-left: 40px !important;
		color: var(--cl-secondary-text-color);
		font-size: 14px;
	}

	.blue_desc {
		margin-left: 10px;
	}

	.blue_desc span {
		color: var(--cl-primary-text-color);
		font-weight: 700;
		font-size: 14px;
	}

	.blue_desc span svg {
		margin-right: 12px;

		position: relative;
		max-width: 100%;
		height: 1.25em;
		fill: currentcolor;
		display: inline-block;
		color: var(--cl-secondary-text-color);
		fill: currentcolor;
		font-size: 18px;
	}
</style>