<div class="cp-app-container" data-app="account-verification">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3> <?php echo cl_translate('Account Verification'); ?></h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>"> <i data-feather="home"></i></a></li>
                        <li class="breadcrumb-item"> <?php echo cl_translate('Account Verification'); ?></li>

                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card" id="vue-cpanel-account-verification-app" data-an="info-content">
                    <div class="card-header">
                        <h5>
                            <?php echo cl_translate('Account Verification requests'); ?> - <label class="badge badge-primary">({{total_requests}})</label>
                        </h5>
                    </div>

                    <div class="body" style="padding: 15px;">
                        <div class="regular-table">
                            <table class="table table-hover no-mb">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>
                                            <?php echo cl_translate('Username'); ?>
                                        </th>
                                        <th>
                                            <?php echo cl_translate('E-mail address'); ?>
                                        </th>
                                        <th>
                                            <?php echo cl_translate('Last seen'); ?>
                                        </th>

                                        <th>
                                            <?php echo cl_translate('Status'); ?>
                                        </th>
                                        <th>
                                            <?php echo cl_translate('Requested at'); ?>
                                        </th>
                                        <th>
                                            <?php echo cl_translate('Action'); ?>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody data-an="requests-list">
                                    <?php if (not_empty($cl['requests'])) : ?>
                                        <?php foreach ($cl['requests'] as $cl['li']) : ?>
                                            <?php echo cl_template('cpanel/assets/account_verification/includes/list_item'); ?>
                                        <?php endforeach; ?>
                                    <?php else : ?>
                                        <tr>
                                            <td colspan="7">
                                                <div class="empty-table">
                                                    <span class="icon">
                                                        <i class="material-icons">check_circle_outline</i>
                                                    </span>
                                                    <h4><?php echo ('No requests found'); ?></h4>
                                                    <p>
                                                        <?php echo ('It looks like there are no account verification requests in your database yet. All account verification requests will be displayed here.'); ?>
                                                    </p>
                                                </div>
                                            </td>
                                        </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>

                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_prev_ctrl}" v-on:click="paginate('up')" href="javascript:void(0);" class="paginate_button prev">
                                <i class="material-icons">chevron_left</i>
                            </a>

                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_next_ctrl}" v-on:click="paginate('down')" href="javascript:void(0);" class="paginate_button next">
                                <i class="material-icons">chevron_right</i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php echo cl_template('cpanel/assets/account_verification/scripts/app_master_script'); ?>