<div class="modal popup-ticket-modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                <?php echo cl_translate('popup_report'); ?>
                </h5>
                <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="user-info">
                    <div class="avatar">
                        <img src="<?php echo($cl['rep_data']['avatar']); ?>" alt="Avatar">
                    </div>
                    <div class="uname">
                        <h5><?php echo($cl['rep_data']['name']); ?></h5>
                        <a><?php echo($cl['rep_data']['email']); ?></a>
                    </div>
                </div>
                <div class="text-message">
                    <h5> <?php echo cl_translate('popup_report'); ?>:</h5>
                    <p>
                        <?php if (not_empty($cl['rep_data']['comment'])): ?>
                            <?php echo $cl['rep_data']['comment']; ?>
                        <?php else: ?>
                            <?php echo cl_translate('report_not_coments'); ?>
                        <?php endif; ?>
                    </p>
                </div>
            </div>
            <div class="modal-footer">
            <button class="btn btn-primary" type="button" data-bs-dismiss="modal"> <?php echo cl_translate('close'); ?></button>
                   
            </div>
        </div>
    </div>
</div>