<form class="form"  autocomplete="off">
	<div class="form-title">
		<h2>
			<?php echo cl_translate("Oh, sorry."); ?>
		</h2>
		<p>
			<?php echo cl_translate("User registration is temporarily unavailable. <br> However, you can log in if you have previously registered. <br> If you have any questions, please contact the site administration or check back shortly"); ?>
		</p>
	</div>
	<div class="form-group">
		<label>
			<?php echo cl_translate("Username"); ?>
		</label>
        <input name="uname" disabled="true" type="text" class="form-control" placeholder="<?php echo cl_translate("Choose your username"); ?>">
    </div>
	<div class="form-group">
        <label>
        	<?php echo cl_translate("Email address"); ?>
        </label>
        <input name="email" disabled="true" type="email" class="form-control" placeholder="<?php echo cl_translate("Enter your email address"); ?>">
    </div>
	<div class="form-group">
        <label>
        	<?php echo cl_translate("Password"); ?>
        </label>
        <div class="password-ctrl">
        	<input name="password" disabled="true" class="form-control" placeholder="<?php echo cl_translate("Create a password for your account"); ?>">
        	<button class="password-ctrl" type="button">
				<span>
					<?php echo cl_ikon("eye-closed"); ?>
				</span>
			</button>
        </div>
    </div>
	<div class="form-group">
        <label>
        	<?php echo cl_translate("Confirm the password"); ?>
        </label>
        <div class="password-ctrl">
        	<input name="conf_pass" disabled="true" class="form-control" placeholder="<?php echo cl_translate("Confirm the password"); ?>">
        	<button class="password-ctrl" type="button">
				<span>
					<?php echo cl_ikon("eye-closed"); ?>
				</span>
			</button>
        </div>
    </div>
	<div class="form-group">
		<div class="tos-agree">
			<div class="form-check">
				<input class="form-check-input" type="checkbox" value="" id="tos-agree" disabled="true">
				<label class="form-check-label" for="tos-agree">
					<span>
						<?php echo cl_translate("By continuing, you agree to {@site_name@}",array(
							"site_name" => $cl["config"]["name"]
						)); ?>
					</span>
					<br>
					<a href="<?php echo cl_link('terms_of_use'); ?>"><?php echo cl_translate("Terms of Use"); ?></a> <?php echo cl_translate("And"); ?>	<a href="<?php echo cl_link('privacy_policy'); ?>"><?php echo cl_translate("Privacy policy"); ?></a>
				</label>
			</div>
		</div>
	</div>
	<div class="form-group">
		<button class="btn btn-custom main-inline lg btn-block" disabled="true">
			<?php echo cl_translate("Sign up"); ?>
		</button>
	</div>
	<?php if (in_array("on", array($cl["config"]["instagram_status"], $cl["config"]["vkontakte_status"], $cl["config"]["discord_status"], $cl["config"]["facebook_oauth"], $cl["config"]["linkedin_oauth"], $cl["config"]["google_oauth"], $cl["config"]["twitter_oauth"]))) : ?>
		<div class="form-group">
			<div class="login-or-signup">
				<span>
					<?php echo cl_translate("or"); ?>
				</span>
			</div>
		</div>
		<div class="form-group oauth-login-providers">
			<?php if ($cl["config"]["google_oauth"] == "on") : ?>
				<a href="<?php echo cl_link('oauth/google'); ?>" class="social-login-btn google">
					<button class="btn btn-custom main-inline lg btn-block" type="button">
						<span class="d-inline-flex flex-wn align-items-center">
							<span class="flex-item btn-icon">
								<?php echo cl_ikon('google-logo-2'); ?>
							</span>
							<span class="flex-item">
								<?php echo cl_translate("SignIn with Google"); ?>
							</span>
						</span>
					</button>
				</a>
			<?php endif; ?>
			<div class="form-cta-link forgot">
				<a data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
					<span class="btn-outline">
						<?php echo cl_ikon('pub-more'); ?>
						<?php echo cl_translate("More Social Login"); ?>
					</span>
				</a>
			</div>
			<div class="collapse" id="collapseExample">

				<?php if ($cl["config"]["facebook_oauth"] == "on") : ?>
					<a href="<?php echo cl_link('oauth/facebook'); ?>" class="social-login-btn facebook">
						<button class="btn btn-custom main-inline lg btn-block" type="button">
							<span class="d-inline-flex flex-wn align-items-center">
								<span class="flex-item btn-icon">
									<?php echo cl_ikon('logos/logo-facebook'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate("SignIn with Facebook"); ?>
								</span>
							</span>
						</button>
					</a>
				<?php endif; ?>
				<?php if ($cl["config"]["twitter_oauth"] == "on") : ?>
					<a href="<?php echo cl_link('oauth/twitter'); ?>" class="social-login-btn twitter">
						<button class="btn btn-custom main-inline lg btn-block" type="button">
							<span class="d-inline-flex flex-wn align-items-center">
								<span class="flex-item btn-icon">
									<?php echo cl_ikon('logos/logo-twitter'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate("SignIn with Twitter"); ?>
								</span>
							</span>
						</button>
					</a>
				<?php endif; ?>

				<?php if ($cl["config"]["linkedin_oauth"] == "on") : ?>
					<a href="<?php echo cl_link('oauth/linkedin'); ?>" class="social-login-btn linkedin">
						<button class="btn btn-custom main-inline lg btn-block" type="button">
							<span class="d-inline-flex flex-wn align-items-center">
								<span class="flex-item btn-icon">
									<?php echo cl_icon('logos/logo-linkedin'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate("SignIn with LinkedIn"); ?>
								</span>
							</span>
						</button>
					</a>
				<?php endif; ?>
				<?php if ($cl["config"]["discord_status"] == "on") : ?>
					<a href="<?php echo cl_link('oauth/discord'); ?>" class="social-login-btn discord">
						<button class="btn btn-custom main-inline lg btn-block" type="button">
							<span class="d-inline-flex flex-wn align-items-center">
								<span class="flex-item btn-icon">
									<?php echo cl_icon('logos/logo-discord'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate("SignIn with Discord"); ?>
								</span>
							</span>
						</button>
					</a>
				<?php endif; ?>
				<?php if ($cl["config"]["vkontakte_status"] == "on") : ?>
					<a href="<?php echo cl_link('oauth/vkontakte'); ?>" class="social-login-btn vkontakte">
						<button class="btn btn-custom main-inline lg btn-block" type="button">
							<span class="d-inline-flex flex-wn align-items-center">
								<span class="flex-item btn-icon">
									<?php echo cl_icon('logos/logo-vk'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate("SignIn with Vkontakte"); ?>
								</span>
							</span>
						</button>
					</a>
				<?php endif; ?>
				<?php if ($cl["config"]["instagram_status"] == "on") : ?>
					<a href="<?php echo cl_link('oauth/instagram'); ?>" class="social-login-btn instagram">
						<button class="btn btn-custom main-inline lg btn-block" type="button">
							<span class="d-inline-flex flex-wn align-items-center">
								<span class="flex-item btn-icon">
									<?php echo cl_icon('logos/logo-instagram'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate("SignIn with Instagram"); ?>
								</span>
							</span>
						</button>
					</a>
				<?php endif; ?>
			</div>
		</div>
	<?php endif; ?>
	<div class="form-group no-mb">
		<div class="form-cta-link">
			<span>
				<?php echo cl_translate("Already have an account?"); ?>
			</span>
			<a href="<?php echo cl_link('guest'); ?>">
				<?php echo cl_translate("Login"); ?>
			</a>
		</div>
	</div>
</form>

<?php if (not_empty($cl["invite_code"]) && empty($cl["invite_code_status"])): ?>
	<script>
		jQuery(document).ready(function($) {
			setTimeout(function() {
				cl_bs_notify("<?php echo cl_translate("The invitation link you are using is invalid or has expired."); ?>", 5000, "danger");
			}, 1000);
		});
	</script>
<?php endif; ?>