<div class="timeline-placeholder">
	<div class="icon">
		<div class="icon__bg">
			<?php echo cl_icon('toggle_off'); ?>
		</div>
	</div>

	<div class="pl-message">
		<h4>
			<?php echo cl_translate("This profile is disabled"); ?>
		</h4>
		<p>
			<?php echo cl_translate("This account has been disabled by the administration for violating the rules. If you have any questions about this, please contact our support team."); ?>
		</p>	
	</div>
	<div class="c2action-single">
		<a href="<?php echo cl_link('/'); ?>">
			<button class="btn btn-custom main-outline lg">
				<?php echo cl_translate("Go to the homepage"); ?>
			</button>
		</a>
	</div>
</div>