
<div class="h-laptop">
	<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
		<div class="mobile-bottom-navbar-inner">
			<div class="avatar-menu">
				<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
			</div>
		</div>
	</div>
</div>

<div class="timeline-container" data-app="homepage">
	<div class="timeline-header symbol_header" data-el="tl-header">
		<?php echo cl_template('common/bot_line'); ?>
		<div>
			<ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
				<li  role="presentation">
					<a class="nav-link active home_nav_btn" id="trending-tab" data-toggle="tab" href="#trending" role="tab"	aria-controls="trending" aria-selected="true">
						<?php echo cl_translate("Top"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
				<li  role="presentation">
					<a class="nav-link home_nav_btn" id="latest-tab" data-toggle="tab" href="#latest" role="tab"	aria-controls="latest" aria-selected="true">
						<?php echo cl_translate("Latest"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
				<li  role="presentation">
					<a class="nav-link home_nav_btn" id="following-tab" data-toggle="tab" href="#following" role="tab" aria-controls="following" aria-selected="true">
						<?php echo cl_translate("Following"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
				<li  role="presentation">
					<a class="nav-link home_nav_btn" id="watching-tab" data-toggle="tab" href="#watching" role="tab" aria-controls="watching" aria-selected="true">
						<?php echo cl_translate("watchings"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="tab-content" id="myTabContent">
		<div class="tab-pane fade show active" id="trending" role="tabpanel" aria-labelledby="trending-tab">
			<?php if (not_empty($cl["feed_trending"])): ?>
				<div class="timeline-posts-container">
					<div class="timeline-posts-ls" data-an="entry-list">
						<?php foreach ($cl["feed_trending"] as $cl['li']): ?>
								<?php echo cl_template('timeline/post'); ?>
						<?php endforeach; ?>
					</div>
					<?php if (count($cl["feed_trending"]) == 30): ?>
							<div class="timeline-data-loader">
								<button class="btn btn-custom main-outline lg" data-an="load-more">
									<?php echo cl_translate("Show more"); ?>
								</button>
							</div>
					<?php endif; ?>
				</div>
			<?php else: ?>
				<div class="timeline-placeholder">
					<div class="icon">
						<div class="icon__bg">
							<?php echo cl_icon('feed'); ?>
						</div>
					</div>
					<div class="pl-message">
						<h4>
							<?php echo cl_translate("No data to display yet!"); ?>
						</h4>
						<p>
							<?php echo cl_translate("It looks like the site has no content to display yet. All featured posts will be displayed on this page"); ?>
						</p>
					</div>
				</div>
			<?php endif; ?>
		</div>
		<div class="tab-pane fade" id="latest" role="tabpanel" aria-labelledby="latest-tab">
			<div class="timeline-posts-container" style="margin-top: 0px;">
				<?php if (not_empty($cl["feed_latest"])): ?>
					<div class="timeline-posts-ls" data-an="entry-list">
						<?php foreach ($cl["feed_latest"] as $cl["li"]): ?>
							<?php echo cl_template('timeline/post'); ?>
						<?php endforeach; ?>
					</div>
					<?php if (is_array($cl["feed_latest"]) && count($cl["feed_latest"]) == 30): ?>
						<div class="timeline-data-loader">
							<button class="btn btn-custom main-outline lg" data-an="load-more">
								<?php echo cl_translate("Show more"); ?>
							</button>
						</div>
					<?php endif; ?>
				<?php else: ?>
					<div class="timeline-placeholder">
						<div class="icon">
							<div class="icon__bg">
								<?php echo cl_icon('feed'); ?>
							</div>
						</div>
						<div class="pl-message">
							<h4>
								<?php echo cl_translate("No data to display yet!"); ?>
							</h4>
							<p>
								<?php echo cl_translate("It looks like the site has no content to display yet. All featured posts will be displayed on this page"); ?>
							</p>
						</div>
					</div>
				<?php endif; ?>
			</div>
		</div>
		<div class="tab-pane fade" id="following" role="tabpanel" aria-labelledby="following-tab">
			<div class="timeline-placeholder">
				<div class="icon">
					<div class="icon__bg">
						<?php echo cl_icon('feed'); ?>
					</div>
				</div>
				<div class="pl-message">
					<h4>
						<?php echo cl_translate("Follow users!"); ?>
				</h4>
					<p>
						<?php echo cl_translate("Follow users on Cointweets to see their posts here"); ?>
					</p>
				</div>
				<div class="c2action-single">
					<button class="btn btn-custom main-outline lg" data-toggle="modal" data-target="#loginModal">
						<?php echo cl_translate("Add users"); ?>
					</button>
				</div>
			</div>
		</div>
		<div class="tab-pane fade" id="watching" role="tabpanel" aria-labelledby="watching-tab">
			<div class="timeline-placeholder">
				<div class="icon">
					<div class="icon__bg">
						<?php echo cl_icon('feed'); ?>
					</div>
				</div>
				<div class="pl-message">
					<h4>
						<?php echo cl_translate("Add coins!"); ?>
				</h4>
					<p>
						<?php echo cl_translate("Add more coins to your watchlist to see popular posts about them here"); ?>
					</p>
				</div>
				<div class="c2action-single">
					<button class="btn btn-custom main-outline lg" data-toggle="modal" data-target="#loginModal">
						<?php echo cl_translate("Add coins"); ?>
					</button>
				</div>
			</div>
		</div>
	</div>
	<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
		<div class="h-laptop">
			<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
				<div class="mobile-bottom-navbar-inner">
					<div class="avatar-menu">
						<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
					</div>

				</div>
			</div>
		</div>
	<?php endif; ?>

	<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
	<?php echo cl_template("home/scripts/app_master_script"); ?>
	<?php echo cl_template('feed/scripts/app_master_script'); ?>
</div>
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css" rel="stylesheet" />
<!-- MDB -->
<style>
	body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-header {
		height: 107px;
		/* background-color: var(--smc-main-bg-color-3); header opacity background*/
		backdrop-filter: blur(12px);
	}

	.timeline-header__botline {
		border-bottom: 1px solid var(--smc-main-bg-color-2);
		display: flex;
		justify-content: space-between;
		width: 100%;
		align-items: center;
		padding-left: 16px;
		padding-right: 16px;
	}

	.nav-fill .nav-item .nav-link,
	.nav-justified .nav-item .nav-link {
		width: auto;
		text-decoration: none;
		text-transform: none;
		color: var(--smc-main-text-color-lighten-5);
		font-weight: 500;
		font-size: 18px;
	}
	.nav-tabs .nav-link {
		color: var(--smc-main-text-color-2);
	}
	.nav-tabs .nav-item.show .nav-link,
	.nav-tabs .nav-link.active {
		color: var(--smc-main-text-color);
		border-bottom-color: var(--smc-main-border-color);
		border-bottom-width: 0px;
		font-weight: 700;
		background: transparent;
	}

	.nav-tabs .nav-item.show .nav-link,
	.nav-tabs .nav-link.active div.css-1dbjc4n {
		background-color: rgb(29, 155, 240);
		height: 4px;
		width: 28px;
		border-radius: 9999px;
		text-align: center;
		display: block;
		position: relative;
		bottom: 0;
		margin-left: auto;
		margin-right: auto;
		margin-top: 12px;
		margin-bottom: -7px;
	}
	.left-push-nav{
		display: inline-flex;
	}
	.nav-tabs .nav-link:hover {
		background-color: inherit;
		border: 0px !important;
		border-color: transparent !important;
		transition: none !important;
	}
	.home_nav_btn{
		color: var(--smc-main-text-color-2);
		font-size: 18px !important;
		text-transform: none !important;
	}
	.nav-tabs .nav-link {
		padding:10px 10px 12px 4px !important;
	}
</style>
<script>
	// Initialise Carousel
	const cardSlider = new Carousel(document.querySelector("#cardSlider"), {
		Dots: false,
		itemtsToShow : 5,
	})
	const cardSlider2 = new Carousel(document.querySelector("#cardSlider2"), {
		Dots: false,
		itemtsToShow : 5,							/* edited by kevin to make watching work (button to slide) 2024.9.15*/
	})
	const cardSlider3 = new Carousel(document.querySelector("#cardSlider3"), {		/* edited by kevin to make watching work (button to slide) 2024.9.15*/
		Dots: false,
	})
</script>
<script src="https://cdn.tailwindcss.com"></script>
<script>
	"use strict";

	var offset = 30;

	jQuery(document).ready(function ($) {
		var _app = $('div[data-app="homepage"]');
		var feed_ls = _app.find('[data-an="entry-list"]');

		_app.find('button[data-an="load-more"]').on('click', function (event) {
			event.preventDefault();

			var _self = $(this);


			$.ajax({
				url: "<?php echo cl_link("native_api/home/load_more"); ?>",
				type: 'GET',
				dataType: 'json',
				data: {
					offset: offset,
				},
				beforeSend: function () {
					_self.attr('disabled', 'true').text("<?php echo cl_translate("Please wait"); ?>");
				}
			}).done(function (data) {
				if (data.status == 200) {
					feed_ls.append(data.html);

					_self.removeAttr('disabled').text("<?php echo cl_translate("Show more"); ?>");

					offset += 30;
				}

				else {
					_self.text("<?php echo cl_translate("That is all for now!"); ?>");
				}
			});
		});
	});
</script>