
<div class="cp-app-container" data-app="banktrans-receipts">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3> <?php echo cl_translate('Bank transfers'); ?></h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>"> <i data-feather="home"></i></a></li>
                        <li class="breadcrumb-item"> <?php echo cl_translate('Bank transfers'); ?></li>

                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                          <div class="card" id="vue-cpanel-banktrans-receipts-app" data-an="info-content">
                    <div class="card-header">
                        <h5>
                        <?php echo cl_translate('Wallet replenishment requests by bank transfers'); ?>
                     - ({{total_requests}})
                    </h5>
                </div>
                <div class="body" style="padding: 15px;">
                    <div class="regular-table">
                    <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>
                                        ID
                                    </th>
                                    <th>
                                    <?php echo cl_translate('Username'); ?>
                                    </th>
                                    <th>
                                    <?php echo cl_translate('Amount'); ?>
                                    </th>
                                    <th>
                                    <?php echo cl_translate('Currency'); ?>
                                    </th>
                                    <th>
                                    <?php echo cl_translate('Transferred at'); ?>
                                    </th>
                                    <th>
                                    <?php echo cl_translate('Action'); ?>
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-an="requests-list">
                                <?php if (not_empty($cl['requests'])): ?>
                                    <?php foreach ($cl['requests'] as $cl['li']): ?>
                                        <?php echo cl_template('cpanel/assets/banktrans_receipts/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="6">
                                            <div class="empty-table">
                                                <span class="icon">
                                                    <?php echo cl_ikon("feed"); ?>
                                                </span>
                                                <h4><?php echo cl_translate('No requests found'); ?></h4>
                                                <p>
                                                <?php echo cl_translate('no_requests_desc'); ?>
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                        <div class="table-pagination">
                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_prev_ctrl}" v-on:click="paginate('up')" href="javascript:void(0);" class="pagination-ctrls prev">
                                <?php echo cl_ikon("chevron-left"); ?>
                            </a>
                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_next_ctrl}" v-on:click="paginate('down')" href="javascript:void(0);" class="pagination-ctrls next">
                                <?php echo cl_ikon("chevron-right"); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/banktrans_receipts/scripts/app_master_script'); ?>