<link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
<div class="timeline-container">
    <div class="">
        <div class="timeline-header" data-el="tl-header">
            <div class="timeline-header__botline">
                <div class="lp">
                    <div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
                        <div>
                            <span class="go-back" onclick="SMColibri.go_back();">
                                <?php echo cl_ikon('arrow-left'); ?>
                            </span>
                        </div>
                        <div>
                            <a href="<?php echo cl_link("settings"); ?>" data-spa="true">
                                <?php echo cl_translate("General page settings"); ?>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="cp">

                </div>
                <div class="rp">

                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <?php

        $symbol_id = fetch_or_get($_GET["symbol_id"], false);
        $symbol_username = fetch_or_get($_GET["symbol_username"], false);

        if ($_SERVER["REQUEST_METHOD"] == "POST") {
            if (isset($_POST["symbol_id"])) {
                $symbol_id = $_POST["symbol_id"];


                if (isset($_FILES['avatar']) && not_empty($_FILES['avatar']['tmp_name'])) {

                    echo "<div class='px-4 bg-green-200 rounded-md py-2'><p class='text-green-600 px-2'>Avatar uploaded successfully</p></div>";
                }


                if (isset($_FILES['cover']) && not_empty($_FILES['cover']['tmp_name'])) {

                    echo "<div class='px-4 bg-green-200 rounded-md py-2'><p class='text-green-600 px-2'>Cover uploaded successfully</p></div>";
                } else {

                    if (isset($_POST["name"]) && isset($_POST["raw_sname"]) && isset($_POST["email"]) && isset($_POST["about"]) && isset($_POST["country"]) && isset($_POST["website"]) && isset($_POST["city"])) {
                        $data = array(
                            "fname" => $_POST["name"],
                            "username" => $_POST["raw_sname"],
                            "email" => $_POST["email"],
                            "about" => $_POST["about"],
                            "country_id" => $_POST["country"],
                            "website" => $_POST["website"],
                            "city" => $_POST["city"]
                        );


                        if (cl_update_symbol_data($symbol_id, $data)) {
                            echo "<div class='px-4 bg-green-200 rounded-md py-2'><p class='text-green-600 px-2'>Page data has been successfully updated</p></div>";
                        } else {
                            echo "<p class='text-red-600'>An error occurred while updating page data.</p>";
                        }
                    } else {

                        echo "";
                    }
                }
            } else {

                echo "";
            }
        }
        ?>
        <form method="post" action="" class="px-3 py-3">
            <input type="hidden" name="symbol_id" value="<?php echo $cl['symbol']['id']; ?>">
            <div class="mb-6">
                <label for="name"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("title_page"); ?></label>
                <input type="text" name="name" id="name"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    value="<?php echo $cl['symbol']['name']; ?>"
                    placeholder="<?php echo cl_translate("Enter username"); ?>">
            </div>
            <div class="mb-6">
                <label for="raw_sname"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("symbols"); ?></label>
                <input type="text" name="raw_sname" id="raw_sname"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    value="<?php echo $cl['symbol']['raw_sname']; ?>">
            </div>
            <div class="mb-6">
                <label for="email"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("email"); ?></label>
                <input type="email" name="email" id="email"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    value="<?php echo $cl['symbol']['email']; ?>"
                    placeholder="<?php echo cl_translate("Enter email"); ?>">
            </div>
            <div class="mb-6">
                <label for="website"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("website_url_address"); ?></label>
                <input type="text" name="website" id="website"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    value="<?php echo $cl['symbol']['website']; ?>"
                    placeholder="<?php echo cl_translate("Enter website"); ?>">
            </div>
            <div class="mb-6">
                <label for="about"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("about_us"); ?></label>
                <textarea name="about" id="about"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    placeholder="<?php echo cl_translate("Enter about"); ?>"><?php echo $cl['symbol']['about']; ?></textarea>
            </div>
            <div class="mb-6">
                <label for="city"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("your_city"); ?></label>
                <input type="text" name="city" id="city"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    value="<?php echo $cl['symbol']['city']; ?>"
                    placeholder="<?php echo cl_translate("enter_your_city_name"); ?>">
            </div>
            <div class="mb-6">
                <label for="country"
                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("choose_your_country"); ?></label>
                <select name="country" id="country"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    <?php foreach ($cl['countries'] as $country_id => $country_name): ?>
                        <option value="<?php echo $country_id; ?>" <?php if ($country_id == $cl['symbol']['country_id'])
                                                                        echo "selected"; ?>><?php echo $country_name; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="flex w-full justify-end">
                <button type="submit"
                    class="text-white bg-gray-800 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-xl text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><?php echo cl_translate("save_changes"); ?></button>
            </div>
        </form>
        <form method="post" action="" class="px-3 py-3">
    <div id="qa-container">
        <div class="qa-item mb-1">
            <label for="city" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                Add some questions and answers
            </label>
            <input name="city[]" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                   placeholder="Enter your question">
        </div>
        <div class="mb-2">
            <textarea name="answer[]" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                      placeholder="Enter your answer"></textarea>
        </div>
    </div>

    <button type="button" class="flex items-center p-2" id="add-more">
        <img class="w-6" src="/themes/default/statics/img/plus.svg" alt="">
        <span class="ml-2">Add more</span>
    </button>

    <div class="flex w-full justify-end">
        <button type="submit"
                class="text-white bg-gray-800 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-xl text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
            <?php echo cl_translate("save_changes"); ?>
        </button>
    </div>
</form>

        <div class="flex flex-col w-full mb-3 mt-5 items-center bg-gray-100 rounded-lg border border-gray-200">
            <img src="<?php echo $cl['symbol']['avatar']; ?>" class="w-16 h-16 mt-4 rounded-full" />
            <div class="flex justify-center items-center py-2">
                <img src="<?php echo $cl['symbol']['avatar']; ?>" class="w-5 h-5  rounded-full" />
                <div>$<?php echo $cl['symbol']['username']; ?></div>
            </div>
            <form method="post" action="" class="px-3 py-3 flex flex-col w-full" enctype="multipart/form-data">
                <input type="hidden" name="symbol_id" value="<?php echo $cl['symbol']['id']; ?>">
                <div class="mb-6">
                    <label for="avatar"
                        class="block mb-2  text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("Upload Symbol Avatar and Favicon"); ?></label>
                    <div class="bg-gray-50 border border-gray-300 px-3 rounded-lg">
                        <input type="file" name="avatar" id="avatar" accept="image/*"
                            class=" text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    </div>
                </div>
                <div class="flex w-full justify-end">
                    <button type="submit"
                        class="text-white bg-gray-800 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-xl text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><?php echo cl_translate("save_changes"); ?></button>
                </div>
            </form>
        </div>
        <!-- <div class="flex flex-col w-full items-center bg-gray-100 rounded-lg border border-gray-200">
            <div class="py-2">
                <img src="<?php echo $cl['symbol']['avatar']; ?>" class="w-16 h-16 rounded-full" />
            </div>
            <form method="post" action="" class="px-3 py-3 flex flex-col w-full" enctype="multipart/form-data">
                <input type="hidden" name="symbol_id" value="<?php echo $cl['symbol']['id']; ?>">
                <div class="mb-6">
                    <label for="avatar"
                        class="block mb-2  text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("upload_avatar"); ?></label>
                    <div class="bg-gray-50 border border-gray-300 px-3 rounded-lg">
                        <input type="file" name="avatar" id="avatar" accept="image/*"
                            class=" text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    </div>
                </div>
                <div class="flex w-full justify-end">
                    <button type="submit"
                        class="text-white bg-gray-800 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-xl text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><?php echo cl_translate("save_changes"); ?></button>
                </div>
            </form>
        </div> -->
        <!-- <div class="flex flex-col my-3 w-full items-center bg-gray-100 rounded-lg border border-gray-200">
            <div class="p-2">
                <img src="<?php echo $cl['symbol']['cover']; ?>" class="w-auto h-auto max-h-[150px] rounded-lg " />
            </div>
            <form method="post" action="" enctype="multipart/form-data" class="px-3 py-3  flex flex-col w-full">
                <input type="hidden" name="symbol_id" value="<?php echo $cl['symbol']['id']; ?>">
                <div class="mb-6">
                    <label for="cover"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"><?php echo cl_translate("upload_cover"); ?></label>
                    <div class="bg-gray-50 border border-gray-300 px-3 rounded-lg">
                        <input type="file" name="cover" id="cover" accept="image/*"
                            class=" text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    </div>
                </div>
                <div class="flex w-full justify-end">
                    <button type="submit"
                        class="text-white bg-gray-800 hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-xl text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><?php echo cl_translate("save_changes"); ?></button>
                </div>
            </form>
        </div> -->
    </div>
</div>
