<!-- <div v-show="(query_result == '1')" class="timeline-hashtags-container">
	<div class="timeline-hashtags-ls" data-an="entry-list">
		php tags moved into below pars
	</div>
</div> -->

<div  v-show="(query_result == '1')" class="timeline-users-container">
    <div class="timeline-user-ls" data-an="entry-list">
		<?php if (not_empty($cl["query_result"])): ?>
			<?php foreach ($cl["query_result"] as $cl['li']): ?>
				<?php echo cl_template('explore/includes/li/page_li'); ?>		<!-- edited by kevin to show symbols in user style -->
			<?php endforeach; ?>
		<?php endif; ?>
    </div>
</div>
