<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
	<div class="h-laptop">
		<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
			<div class="mobile-bottom-navbar-inner">
				<div class="avatar-menu">
					<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
				</div>

			</div>
		</div>
	</div>
<?php endif; ?>
<div class="timeline-container" data-app="symbols">
	<div class="timeline-header symbol_header" data-el="tl-header">
		<?php echo cl_template('common/bot_line'); ?>
		<div class="lp" style="display: inline-flex; align-items:center; padding-top:10px;">
			<div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
				<span class="go-back" onclick="SMColibri.go_back();">
					<?php echo cl_ikon('arrow-left'); ?>
				</span>
				<a href="<?php echo cl_link('symbols'); ?>" data-spa="true">
					<?php echo cl_translate("hot_topics_symbol"); ?>
				</a>
			</div>
		</div>
	</div>
	<?php if (not_empty($cl["hsymbols"])): ?>
		<div class="timeline-hashtags-container">
			<div class="timeline-hashtags-ls" data-an="hashtags-list">
				<?php foreach ($cl["hsymbols"] as $cl['li']): ?>
					<?php echo cl_template('symbols/includes/list_item'); ?>
				<?php endforeach; ?>
			</div>
		</div>
		<?php if (count($cl["hsymbols"]) >= 29): ?>
			<div class="timeline-data-loader">
				<button class="btn btn-custom main-outline lg" data-an="load-more">
					<?php echo cl_translate("Show more"); ?>
				</button>
			</div>
			<?php echo cl_template('symbols/scripts/app_master_script'); ?>
		<?php endif; ?>
	<?php else: ?>
		<div class="timeline-placeholder">
			<div class="icon">
				<div class="icon__bg">
					<?php echo cl_icon('whatshot'); ?>
				</div>
			</div>
			<div class="pl-message">
				<h4>
					<?php echo cl_translate("No topics to display"); ?>
				</h4>
				<p>
					<?php echo cl_translate("Here will be (#symbols) a list with navigation on the most relevant topics and events, which will allow you to quickly find media content on the topics you need!"); ?>
				</p>
			</div>
			<div class="c2action-single">
				<a href="<?php echo cl_link('/'); ?>" data-spa="true">
					<button class="btn btn-custom main-outline lg">
						<?php echo cl_translate("Go to the homepage"); ?>
					</button>
				</a>
			</div>
		</div>
	<?php endif; ?>
	
</div>

<script src="https://cdn.tailwindcss.com"></script>