 <div class="container-fluid">
      <div class="row">         
        <div class="col-12 p-0">
          <div>
            <div class="theme-form">                     
              <div class="wizard-4" id="wizard">                       
                <ul>
                  <li><a class="logo text-start ps-0" href="index.html"><img class="img-fluid for-light" src="assets/images/logo/login.png" alt="looginpage" style="height: 70px;"><img class="img-fluid for-dark" src="../assets/images/logo/logo_dark.png" alt="looginpage"></a></li>
                  <li><a href=""  class="selected">
                      <h4>1</h4>
                      <h5>Terms of use</h5><small>License Agreement</small></a></li>
                  <li><a href="#step-2">
                      <h4>2</h4>
                      <h5>Requirements</h5><small>Server info</small></a></li>
                  <li><a href="#step-3">
                      <h4>3</h4>
                      <h5>Installation</h5><small>Congratulations</small></a></li>
                  <li class="pb-0"><a href="#step-4">
                      <h4>4</h4>
                      <h5> Done <i class="fa fa-thumbs-o-up"></i></h5><small>Complete.. !</small></a></li>
                  <li>                           <img src="assets/images/login/icon.png" alt="looginpage" style="max-height: 230px; margin-top: 30px;"></li>
                </ul>
                	<div class="container">
		<div class="main-cont">
			<div class="row">
				<div class="col-sm-8 offset-sm-2">
					<div class="wizard-title" style="margin-bottom: 40px;">
						<h2>
							Welcome to the JOOJ Talk installer!
						</h2>
						<p>
							Installing <b>JOOJ Talk</b> quick easy. In just a few steps, you get a modern social media sharing platform
						</p>
					</div>
 <div id="step-1">

<div class="main-cont-inner" id="license-agreements-page">
	<div class="wizard-title">
		<h2>
			<svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 90c44.3 0 86 17.3 117.4 48.6C404.7 170 422 211.7 422 256s-17.3 86-48.6 117.4C342 404.7 300.3 422 256 422s-86-17.3-117.4-48.6C107.3 342 90 300.3 90 256s17.3-86 48.6-117.4C170 107.3 211.7 90 256 90m0-42C141.1 48 48 141.1 48 256s93.1 208 208 208 208-93.1 208-208S370.9 48 256 48z"/><path d="M277 360h-42V235h42v125zm0-166h-42v-42h42v42z"/></svg>
			Terms of use (License Agreement)
		</h2>
	</div>
	<div class="cont-body">
		<div class="terms-of-use">
		<div class="createdby">
				<h6>Created by: JOOJ Team - <a href="https://jooj.us/" target="_blank">JOOJ.us</a></h6>
			</div>
			<div class="agreement-def-title">
				<p>
					In order to proceed with the installation of your site, you must first read and confirm that you agree to the terms of use of our product.
				</p>
			</div>

			<table class="table">
				<thead>
					<th>
						You are allowed to:
					</th>
					<th>
						You are not allowed to:
					</th>
				</thead>
				<tbody>
					<tr>
						<td>
							<span class="allowed">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 48C141.6 48 48 141.6 48 256s93.6 208 208 208 208-93.6 208-208S370.4 48 256 48zm-42.7 318.9L106.7 260.3l29.9-29.9 76.8 76.8 162.1-162.1 29.9 29.9-192.1 191.9z"/></svg>
							</span>
							Private use
						</td>
						<td>
							<span class="denied">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 90c44.3 0 86 17.3 117.4 48.6C404.7 170 422 211.7 422 256s-17.3 86-48.6 117.4C342 404.7 300.3 422 256 422s-86-17.3-117.4-48.6C107.3 342 90 300.3 90 256s17.3-86 48.6-117.4C170 107.3 211.7 90 256 90m0-42C141.1 48 48 141.1 48 256s93.1 208 208 208 208-93.1 208-208S370.9 48 256 48z"/><path d="M360 330.9L330.9 360 256 285.1 181.1 360 152 330.9l74.9-74.9-74.9-74.9 29.1-29.1 74.9 74.9 74.9-74.9 29.1 29.1-74.9 74.9z"/></svg>
							</span>
							Resell
						</td>
					</tr>
					<tr>
						<td>
							<span class="allowed">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 48C141.6 48 48 141.6 48 256s93.6 208 208 208 208-93.6 208-208S370.4 48 256 48zm-42.7 318.9L106.7 260.3l29.9-29.9 76.8 76.8 162.1-162.1 29.9 29.9-192.1 191.9z"/></svg>
							</span>
							Modification
						</td>
						<td>
							<span class="denied">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 90c44.3 0 86 17.3 117.4 48.6C404.7 170 422 211.7 422 256s-17.3 86-48.6 117.4C342 404.7 300.3 422 256 422s-86-17.3-117.4-48.6C107.3 342 90 300.3 90 256s17.3-86 48.6-117.4C170 107.3 211.7 90 256 90m0-42C141.1 48 48 141.1 48 256s93.1 208 208 208 208-93.1 208-208S370.9 48 256 48z"/><path d="M360 330.9L330.9 360 256 285.1 181.1 360 152 330.9l74.9-74.9-74.9-74.9 29.1-29.1 74.9 74.9 74.9-74.9 29.1 29.1-74.9 74.9z"/></svg>
							</span>
							Distribute
						</td>
					</tr>
					<tr>
						<td>
							<span class="allowed">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 48C141.6 48 48 141.6 48 256s93.6 208 208 208 208-93.6 208-208S370.4 48 256 48zm-42.7 318.9L106.7 260.3l29.9-29.9 76.8 76.8 162.1-162.1 29.9 29.9-192.1 191.9z"/></svg>
							</span>
							Delete sections as you see fit
						</td>
						<td>
							<span class="denied">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 90c44.3 0 86 17.3 117.4 48.6C404.7 170 422 211.7 422 256s-17.3 86-48.6 117.4C342 404.7 300.3 422 256 422s-86-17.3-117.4-48.6C107.3 342 90 300.3 90 256s17.3-86 48.6-117.4C170 107.3 211.7 90 256 90m0-42C141.1 48 48 141.1 48 256s93.1 208 208 208 208-93.1 208-208S370.9 48 256 48z"/><path d="M360 330.9L330.9 360 256 285.1 181.1 360 152 330.9l74.9-74.9-74.9-74.9 29.1-29.1 74.9 74.9 74.9-74.9 29.1 29.1-74.9 74.9z"/></svg>
							</span>
							Trade this product in any way without permission
						</td>
					</tr>
					<tr>
						<td>
							<span class="allowed">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 48C141.6 48 48 141.6 48 256s93.6 208 208 208 208-93.6 208-208S370.4 48 256 48zm-42.7 318.9L106.7 260.3l29.9-29.9 76.8 76.8 162.1-162.1 29.9 29.9-192.1 191.9z"/></svg>
							</span>
							Translate to your choice of language
						</td>
					</tr>
				</tbody>
			</table>
			<div class="next-action">
				<div class="agreement-action">
					<div class="agree">
						<input type="checkbox" id="license-agreement-checkbox" data-onchange="license_agreement">
						<label for="license-agreement-checkbox"> I agree to the terms of use and privacy policy</label>
					</div>
					<button data-anchor="?p=requirements" id="continue" class="btn btn-primary" disabled="true">
						Continue
					</button>
				</div>
			</div>
		</div>
	</div>
</div>
</div>