<div class="timeline-placeholder" style="padding-top: 10px;">
	<div class="icon">
		<div class="icon__bg_img">
		<img src="{%config theme_url%}/statics/img/Mention-bro.png">
		</div>
	</div>
	<div class="pl-message">
		<h4>
			<?php echo cl_translate("No posts yet!"); ?>
		</h4>
		<p>
			<?php echo cl_translate("It looks like there are no posts on your feed yet. All your posts and publications of people you follow will be displayed here."); ?>
		</p>
	</div>
	<div class="c2action-single">
		<button class="btn btn-custom main-inline lg" data-toggle="modal" data-target="#add_new_post">
			<?php echo cl_translate("Create my first post"); ?>
		</button>
	</div>
</div>