<div class="cp-app-container" data-app="timezone">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3> <?php echo cl_translate('TimeZone settings'); ?></h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>"> <i data-feather="home"></i></a></li>
                        <li class="breadcrumb-item"> <?php echo cl_translate('TimeZone settings'); ?></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="d-block">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card" style="padding: 15px;">
                        <div class="card-header">
                            <h5>
                                <?php echo cl_translate('Manage TimeZone settings'); ?>
                            </h5>
                        </div>
                        <div class="card-body">
                            <form class="form" data-an="form">
                                <div class="form-group" data-an="timezone-input">
                                    <label>
                                        Timezone
                                    </label>
                                    <div class="input-group b-15">
                                        <select name="timezone" class="form-select form-control-primary" data-size="10">
                                            <?php foreach ($cl["timezones"] as $tzn => $tzc) : ?>
                                                <option value="<?php echo ($tzn); ?>" <?php if ($cl['config']['timezone'] == $tzn) {
                                                                                            echo ('selected');
                                                                                        } ?>>
                                                    <?php echo ($tzn); ?> / <small><?php echo ($tzc); ?></small>
                                                </option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group no-mb">
                                    <button class="btn btn-primary" type="submit" data-an="submit-ctrl">
                                        <?php echo cl_translate("Save changes"); ?>
                                    </button>
                                </div>
                                <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/timezone/scripts/app_master_script'); ?>