<div class="timeline-header__botline selectable">
<div class="lp w-[5%]">
	
</div>
	<div class="cp auto-x">
		<a href="" class="h-laptop">
			<img src="/themes/default/statics/img/logo.svg" alt="Logo" style="visibility: visible;">
			<span class="logo-text">Cointweets</span>
		</a>
	</div>
	<div class="rp middle">
		<div style="display: flex;" class="nav-link-holde">
			<a href="javascript:void(0);" onclick="SMColibri.display_settings();">
				<span class="dropdown-item-icon">
					<img class="h-[18px] w-[18px] mr-1 ml-1" src="/themes/default/statics/ikons/display.svg" alt="">
				</span>
			</a>
			<button class="go-options dropleft show mr-1 ml-1" data-toggle="modal" data-target="#searchbox-dialog">
				<?php echo cl_icon('search'); ?>
			</button>
		</div>
	</div>
</div>