<div class="timeline-header__botline selectable">
<div class="lp w-[5%]">
	
</div>
	<div class="cp auto-x">
		<a href="" class="h-laptop">
			<img src="/themes/default/statics/img/logo.svg" alt="Logo" style="visibility: visible;">
			<span class="logo-text">Cointweets</span>
		</a>
	</div>
	<div class="rp middle">			
		<button class="go-options dropleft show mr-1 ml-1" data-toggle="modal" data-target="#searchbox-dialog">
			<?php echo cl_icon('search'); ?>
		</button>
	</div>
</div>