
<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
	<div class="h-laptop">
		<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
			<div class="mobile-bottom-navbar-inner">
				<div class="avatar-menu">
					<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
				</div>

			</div>
		</div>
	</div>
<?php endif; ?>
<div class="timeline-container" data-app="advertisements">
	<div class="timeline-header symbol_header" data-el="tl-header">
		<?php echo cl_template('common/bot_line'); ?>
		<div class="lp" style="display: inline-flex; align-items:center; padding-top:10px;">
			<div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
				<span class="go-back" onclick="SMColibri.go_back();">
				<?php echo cl_ikon('arrow-left'); ?>
					</span>
				<a href="<?php echo cl_link('ads'); ?>">
					<?php echo cl_translate('Advertisement'); ?>
				</a>
			</div>
		</div>
	</div>
	<div class="timeline-posts-container">
		<div class="timeline-posts-ls">
		<?php foreach ($cl["ads_ls"] as $cl['li']): ?>
				<?php echo cl_template("timeline/ad"); ?>
			<?php endforeach; ?>
		</div>
	</div>
</div>