

<div class="post-list-item-content" style="display: flex; border: 1px solid #e0e0e0; border-radius: 5px; padding: 10px; margin:10px;">
    <div class="avatar" style="width: 45px; height: 45px;">
        <?php if ($cl['li']['symbol_id'] == 0): ?>
            <a class="block-link" data-spa="true">
                <div class="avatar-holder">
                    <img class="lozad" style="border-radius: 10em;" data-src="<?php echo ($cl['li']['owner']['avatar']); ?>">
                </div>
            </a>
        <?php else: ?>
            <?php if ($cl['li']['owner']['id'] == 1): ?>
                <a class="block-link" data-spa="true">
                    <div class="avatar-holder">
                        <img class="lozad" data-src="<?php echo ($cl['li']['page']['avatar']); ?>">
                    </div>
                </a>
            <?php else: ?>
                <!-- For post page coauthor -->
                <div class="">
                    <a class="block-link" data-spa="true">
                        <div class="avatar-holder">
                            <img class="lozad" data-src="<?php echo ($cl['li']['owner']['avatar']); ?>">
                        </div>
                    </a>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <div class="publication-data" style="padding-left: 15px;">
        <div class="publication-data-inner">
            <div class="publisher-info">
                <!-- For post -->
                <?php if ($cl['li']['symbol_id'] == 0): ?>
                    <div class="lp">

                        <a data-spa="true" data-uinfo-lbox="<?php echo $cl['li']['owner']['id']; ?>" data-toggle="popover" data-placement="bottom">
                            <b>
                                <span class="user-name-holder">
                                    <?php echo $cl['li']['owner']['name']; ?>
                                </span>
                                <p class="<?php if ($cl['li']['owner']['verified'] == '1')
                                                echo 'verified-badge'; ?>" style="display:inline-block;"></p>
                            </b>
                        </a>
                        <span class="uname">
                            @<?php echo $cl['li']['owner']['username']; ?>
                        </span>

                        <span class="point">&#183;</span>

                        <span class="posted-time">
                            <time><?php echo $cl['li']['time']; ?></time>
                            <?php if (not_empty($cl['li']['edited'])): ?>
                                <span
                                    title="<?php echo cl_translate("Edited"); ?>: <?php echo cl_date("h:i A - M d, Y", $cl['li']['edited']); ?>">
                                    &nbsp; (E)
                                </span>
                            <?php endif; ?>
                        </span>
                    </div>
                <?php else: ?>
                    <!-- For Page -->
                    <div class="lp">
                        <!-- For post page admin -->
                        <?php if ($cl['li']['owner']['id'] == 1): ?>
                            <a data-sinfo-lbox="<?php echo $cl['li']['page']['id']; ?>" data-toggle="popover"
                                data-placement="bottom">
                                <b>
                                    <span class="user-name-holder">
                                        <?php echo $cl['li']['page']['name']; ?>
                                    </span>
                                    <p class="<?php if ($cl['li']['owner']['verified'] == '1')
                                                    echo 'verified-badge'; ?>" style="display:inline-block;"></p>
                                </b>
                            </a>
                            <span class="uname">
                                $<?php echo $cl['li']['page']['username']; ?>
                            </span>
                            <span class="point">&#183;</span>

                            <span class="posted-time">
                                <time><?php echo $cl['li']['time']; ?></time>
                                <?php if (not_empty($cl['li']['edited'])): ?>
                                    <span
                                        title="<?php echo cl_translate("Edited"); ?>: <?php echo cl_date("h:i A - M d, Y", $cl['li']['edited']); ?>">
                                        &nbsp; (E)
                                    </span>
                                <?php endif; ?>
                            </span>
                        <?php else: ?>
                            <!-- For post page coauthor -->
                            <div class="flex items-center ">
                                <div>
                                    <a data-spa="true" data-uinfo-lbox="<?php echo $cl['li']['owner']['id']; ?>" data-toggle="popover"
                                        data-placement="bottom">
                                        <b>
                                            <span class="user-name-holder">
                                                <?php echo $cl['li']['owner']['name']; ?>
                                            </span>
                                            <p class="<?php if ($cl['li']['owner']['verified'] == '1')
                                                            echo 'verified-badge'; ?>" style="display:inline-block;"></p>
                                        </b>
                                    </a>
                                    <span class="uname">
                                        @<?php echo $cl['li']['owner']['username']; ?>
                                    </span>
                                </div>

                                <!-- <span class="point">&</span> -->

                                <!-- <div class="px-2">
                            
                            <a href="<?php echo cl_link(cl_strf("symbol/%s", $cl['li']['page']['username'])); ?>" 
                                data-sinfo-lbox="<?php echo $cl['li']['page']['id']; ?>" data-toggle="popover"
                                data-placement="bottom">
                                <b>
                                    <span class="user-name-holder">
                                        <?php echo $cl['li']['page']['name']; ?>
                                    </span>
                                    <p class="<?php if ($cl['li']['page']['verified'] == '1')
                                                    echo 'verified-badge'; ?>" style="display:inline-block;"></p>
                                </b>
                            </a>
                            <span class="uname">
                                $<?php echo $cl['li']['page']['username']; ?>
                            </span>
                            </div> -->
                                <span class="point px-2">&#183;</span>

                                <span class="posted-time">
                                    <time><?php echo $cl['li']['time']; ?></time>
                                    <?php if (not_empty($cl['li']['edited'])): ?>
                                        <span
                                            title="<?php echo cl_translate("Edited"); ?>: <?php echo cl_date("h:i A - M d, Y", $cl['li']['edited']); ?>">
                                            &nbsp; (E)
                                        </span>
                                    <?php endif; ?>
                                </span>
                            </div>
                        <?php endif; ?>

                    </div>
                <?php endif; ?>
            </div>                                    

            <div class="publication-content">
                <?php if (not_empty($cl['li']['text'])): ?>
                    <?php
                        $cl['li']['text'] = cl_rn2br($cl['li']['text']);
                        $cl['li']['text'] = cl_strip_brs($cl['li']['text']);
                    ?>
                    <script>
                        jQuery(document).ready(function($) {

                            $('div.publication-text').find('a[href*="/search/"]').addClass('hash');
                        })
                    </script>
                    <div class="publication-text">
                        <p class="pub-text">
                            <?php echo ($cl['li']['text']); ?>
                        </p>
                    </div>
                <?php endif; ?>

                <?php if ($cl['li']['type'] == 'image' && not_empty($cl['li']['media'])): ?>
                    <?php if (count($cl['li']['media']) == 1): ?>
                        <div class="lozad-media">
                            <div class="publication-image">
                                <a class="fbox-media2" data-btn='<?php echo cl_template('timeline/likes'); ?>'
                                    data-fancybox="gallery" data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                    <img class="lozad"
                                        data-src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'], '')); ?>"
                                        alt="Picture">
                                </a>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="publication-images-collage">
                            <?php foreach ($cl['li']['media'] as $i => $row): ?>
                                <a class="fbox-media2"
                                    data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                    data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                    <div class="image-collage-item">
                                        <div class="lozad-media">
                                            <div class="publication-image">
                                                <img class="d-block w-100 lozad"
                                                    data-src='<?php echo cl_get_media($row['x']['image_thumb']); ?>'
                                                    alt="Image">
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                <?php elseif ($cl['li']['type'] == 'video' && not_empty($cl['li']['media'])): ?>
                    <div class="lozad-media">
                        <div class="publication-image">
                            <a data-type="html5video" class="fbox-media2"
                                data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                <img class="lozad"
                                    src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['x']['poster_thumb'], '')); ?>"
                                    alt="Video">
                                <div class="video-icon">
                                    <span>
                                        <?php echo cl_ikon("play"); ?>
                                    </span>
                                </div>
                            </a>
                        </div>
                    </div>

                <?php elseif ($cl['li']['type'] == 'audio' && not_empty($cl['li']['media'])): ?>
                    <div class="publication-audio" style="margin-top:15px;">
                        <div class="cl-plyr-audio">
                            <audio controls preload="metadata" class="plyr">
                                <source
                                    src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'], '')); ?>"
                                    type="audio/mp3">
                                <source
                                    src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'], '')); ?>"
                                    type="audio/mpeg">
                                <source
                                    src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'], '')); ?>"
                                    type="audio/wav">
                            </audio>
                        </div>
                    </div>

                <?php elseif ($cl['li']['type'] == 'document' && not_empty($cl['li']['media'])): ?>
                    <div class="publication-document">
                        <a  target="_blank"
                            class="document-file">
                            <div class="document-file__icon">
                                <?php echo cl_icon("description"); ?>
                            </div>
                            <div class="document-file__body">
                                <?php echo ($cl['li']['media'][0]['x']["filename"]); ?>
                            </div>
                            <div class="document-file__type">
                                <?php echo ($cl['li']['media'][0]['x']["file_type"]); ?>-<?php echo cl_translate("FILE"); ?>
                            </div>
                            <div class="document-file__icon">
                                <?php echo cl_icon("open_in_new"); ?>
                            </div>
                        </a>
                    </div>
                <?php elseif ($cl['li']['type'] == 'gif' && not_empty($cl['li']['media'])): ?>
                    <div class="lozad-media">
                        <div class="publication-image">
                            <a class="fbox-media2" data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                <img class="lozad"
                                    data-src="<?php echo fetch_or_get($cl['li']['media'][0]['src'], ''); ?>"
                                    alt="GIF-Image">
                            </a>
                        </div>
                    </div>
                <?php elseif ($cl['li']['type'] == 'poll' && not_empty($cl['li']['poll'])): ?>
                    <div class="publication-poll-data" data-post-poll="<?php echo ($cl['li']['id']); ?>"
                        data-status="<?php echo ($cl['li']['poll']['has_voted']); ?>">
                        <div class="publication-poll-data-inner">
                            <?php foreach ($cl['li']['poll']['options'] as $i => $poll_data): ?>
                                <div class="poll-option-bar"
                                    onclick="SMColibri.vote_poll(<?php echo ($cl['li']['id']); ?>, <?php echo ($i); ?>);"
                                    data-poll-option="<?php echo ($i); ?>">
                                    <div class="bar-icon">
                                        <?php echo cl_ikon("ok-circle"); ?>
                                    </div>
                                    <div class="bar-text">
                                        <p>
                                            <?php echo $poll_data["option"]; ?>
                                        </p>
                                    </div>
                                    <div class="bar-num">
                                        <b>
                                            <?php if (not_empty($cl['li']['poll']['has_voted'])): ?>
                                                <?php echo $poll_data["percentage"]; ?>%
                                            <?php endif; ?>
                                        </b>
                                    </div>

                                    <?php if (not_empty($cl['li']['poll']['has_voted'])): ?>
                                        <span class="bar-slider"
                                            style="width: <?php echo $poll_data["percentage"]; ?>%;"></span>
                                    <?php else: ?>
                                        <span class="bar-slider"></span>
                                    <?php endif; ?>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php elseif (not_empty($cl['li']['og_data'])): ?>
                    <?php if (not_empty($cl['li']['og_data']['video_embed'])): ?>
                        <div class="publication-og-data">
                            <div class="publication-og-data-inner embeded-iframe">
                                <div class="og-image">
                                    <div class="lozad-media">
                                        <a href="<?php echo ($cl['li']['og_data']['video_embed']); ?>" class="fbox-media2"
                                            data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                            data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                            <img class="lozad" data-src="<?php echo ($cl['li']['og_data']['image']); ?>"
                                                alt="Video">
                                            <div class="og-icon">
                                                <span>
                                                    <?php echo cl_ikon("play"); ?>
                                                </span>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="og-url-data">
                                    <h5>
                                        <?php echo ($cl['li']['og_data']['title']); ?>
                                    </h5>
                                    <?php if (not_empty($cl['li']['og_data']['description'])): ?>
                                        <p>
                                            <?php echo ($cl['li']['og_data']['description']); ?>
                                        </p>
                                    <?php else: ?>
                                        <p>
                                            <a target="_blank" href="<?php echo ($cl['li']['og_data']['video_embed']); ?>">
                                                <?php echo ($cl['li']['og_data']['video_embed']); ?>
                                            </a>
                                        </p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php elseif (not_empty($cl['li']['og_data']['google_maps_embed'])): ?>
                        <div class="publication-og-data">
                            <div class="publication-og-data-inner embeded-iframe">
                                <div class="og-image">
                                    <div class="lozad-media">
                                        <a href="<?php echo ($cl['li']['og_data']['url']); ?>" class="fbox-media">
                                            <img class="lozad" data-src="<?php echo ($cl['li']['og_data']['image']); ?>"
                                                alt="Video">
                                            <div class="og-icon no-ml">
                                                <span>
                                                    <?php echo cl_ikon("location"); ?>
                                                </span>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="og-url-data">
                                    <h5>
                                        <?php echo ($cl['li']['og_data']['title']); ?>
                                    </h5>

                                    <?php if (not_empty($cl['li']['og_data']['description'])): ?>
                                        <p>
                                            <?php echo ($cl['li']['og_data']['description']); ?>
                                        </p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="publication-og-data">
                            <div class="publication-og-data-inner link">
                                <?php if (not_empty($cl['li']['og_data']['image'])): ?>
                                    <a href="<?php echo ($cl['li']['og_data']['image']); ?>" class="fbox-media2"
                                        data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                        data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                        <div class="og-image">
                                            <img src="<?php echo ($cl['li']['og_data']['image']); ?>" alt="IMG">
                                        </div>
                                    </a>
                                <?php endif; ?>

                                <div class="og-url-data">
                                    <h5>
                                        <?php echo ($cl['li']['og_data']['title']); ?>
                                    </h5>
                                    <p>
                                        <?php echo ($cl['li']['og_data']['description']); ?>
                                    </p>
                                    <a href="<?php echo ($cl['li']['og_data']['url']); ?>" target="_blank">
                                        <span class="pup-link-icon">
                                            <?php echo cl_ikon('pub-icon'); ?>
                                        </span><span class="pup-link-icon-a">
                                            <?php echo ($cl['li']['og_data']['url']); ?>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>