

<div class="post-list-item-content" style="display: flex; border: 1px solid var(--smc-main-border-color); border-radius: 5px; padding: 10px; margin:10px;">
    <div class="publisher-avatar" style = "max-width: 35px; min-width:35px;">
        <?php if ($cl['li']['symbol_id'] == 0): ?>
            <a class="block-link" data-spa="true">
                <div style="width:22px; height:22px; margin-top:-5px;" class="avatar-holder">
                    <img class="lozad" style="border-radius: 10em; width:45px;" data-src="<?php echo ($cl['li']['owner']['avatar']); ?>">
                </div>
            </a>
        <?php else: ?>
            <?php if ($cl['li']['owner']['id'] == 1): ?>
                <a class="block-link" data-spa="true">
                    <div style="width:22px; height:22px; margin-top:-5px;" class="avatar-holder">
                        <img class="lozad" style="border-radius: 10em; width:45px;" data-src="<?php echo ($cl['li']['page']['avatar']); ?>">
                    </div>
                </a>
            <?php else: ?>
                <!-- For post page coauthor -->
                    <a class="block-link" data-spa="true">
                        <div style="width:22px; height:22px; margin-top:-5px;" class="avatar-holder">
                            <img style="border-radius: 10em; width:45px;" class="lozad" data-src="<?php echo ($cl['li']['owner']['avatar']); ?>">
                        </div>
                    </a>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <div class="publication-data">
        <div class="publication-data-inner">
            <div class="publisher-info">
                <!-- For post -->
                    <div class="lp">

                        <a data-spa="true" data-uinfo-lbox="<?php echo $cl['li']['owner']['id']; ?>" data-toggle="popover" data-placement="bottom">
                            <b>
                                <span class="user-name-holder">
                                    <?php echo $cl['li']['owner']['name']; ?>
                                </span>
                                <p class="<?php if ($cl['li']['owner']['verified'] == '1')
                                                echo 'verified-badge'; ?>" style="display:inline-block;"></p>
                            </b>
                        </a>
                        <span class="uname">
                            @<?php echo $cl['li']['owner']['username']; ?>
                        </span>

                        <span class="point">&#183;</span>

                        <span class="posted-time">
                            <time><?php echo $cl['li']['time']; ?></time>
                            <?php if (not_empty($cl['li']['edited'])): ?>
                                <span
                                    title="<?php echo cl_translate("Edited"); ?>: <?php echo cl_date("h:i A - M d, Y", $cl['li']['edited']); ?>">
                                    &nbsp; (E)
                                </span>
                            <?php endif; ?>
                        </span>
                    </div>
                
            </div>                                    

            <div class="publication-content">
                <?php if (not_empty($cl['li']['text'])): ?>
                    <?php
                        $cl['li']['text'] = cl_rn2br($cl['li']['text']);
                        $cl['li']['text'] = cl_strip_brs($cl['li']['text']);
                    ?>
                    <script>
                        jQuery(document).ready(function($) {

                            $('div.publication-text').find('a[href*="/search/"]').addClass('hash');
                        })
                    </script>
                    
                    <!-- Edited By Kevin. 9/20 -->
                                    <div class="publication-text">
										<p style="margin-left:-34px; margin-top:10px;" class="pub-text">
											<?php
											// Sample text from $cl['li']['text']
											$text = $cl['li']['text'];

											// Regular expression to find <a> tags containing text starting with $ (like $abc)
											$pattern = '/(<a[^>]*>\s*\$([a-zA-Z]+)\s*<\/a>)/';

											// Use preg_replace_callback to replace matches with an image tag
											$modified_text = preg_replace_callback($pattern, function($matches) {
												// Extract the word inside the <a> tag without the $ sign
												$symbol = strtolower($matches[2]);

												// Create the image tag
												$image_tag = '<img src="/themes/default/statics/img/symbol_imgs/' . $symbol . '.png" style="height: 16px; padding-right: 2px; display:inline; position:relative; bottom:2px;" alt="' . $symbol . '">';

												// Return the image tag followed by the original <a> tag (e.g., (LLAP.png)<a>$LLAP</a>)
												return $image_tag . $matches[1];
											}, $text);

											// Output the modified text
											echo $modified_text;
											?>
										</p>
									</div>
                <?php endif; ?>

                <?php if ($cl['li']['type'] == 'image' && not_empty($cl['li']['media'])): ?>
                    <?php if (count($cl['li']['media']) == 1): ?>
                        <div class="lozad-media">
                            <div class="publication-image">
                                <a class="fbox-media2" data-btn='<?php echo cl_template('timeline/likes'); ?>'
                                    data-fancybox="gallery" data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                    <img class="lozad"
                                        data-src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'], '')); ?>"
                                        alt="Picture">
                                </a>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="publication-images-collage">
                            <?php foreach ($cl['li']['media'] as $i => $row): ?>
                                <a class="fbox-media2"
                                    data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                    data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                    <div class="image-collage-item">
                                        <div class="lozad-media">
                                            <div class="publication-image">
                                                <img class="d-block w-100 lozad"
                                                    data-src='<?php echo cl_get_media($row['x']['image_thumb']); ?>'
                                                    alt="Image">
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                <?php elseif ($cl['li']['type'] == 'video' && not_empty($cl['li']['media'])): ?>
                    <div class="lozad-media">
                        <div class="publication-image">
                            <a data-type="html5video" class="fbox-media2"
                                data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                <img class="lozad"
                                    src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['x']['poster_thumb'], '')); ?>"
                                    alt="Video">
                                <div class="video-icon">
                                    <span>
                                        <?php echo cl_ikon("play"); ?>
                                    </span>
                                </div>
                            </a>
                        </div>
                    </div>

                <?php elseif ($cl['li']['type'] == 'audio' && not_empty($cl['li']['media'])): ?>
                    <div class="publication-audio" style="margin-top:15px;">
                        <div class="cl-plyr-audio">
                            <audio controls preload="metadata" class="plyr">
                                <source
                                    src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'], '')); ?>"
                                    type="audio/mp3">
                                <source
                                    src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'], '')); ?>"
                                    type="audio/mpeg">
                                <source
                                    src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'], '')); ?>"
                                    type="audio/wav">
                            </audio>
                        </div>
                    </div>

                <?php elseif ($cl['li']['type'] == 'document' && not_empty($cl['li']['media'])): ?>
                    <div class="publication-document">
                        <a  target="_blank"
                            class="document-file">
                            <div class="document-file__icon">
                                <?php echo cl_icon("description"); ?>
                            </div>
                            <div class="document-file__body">
                                <?php echo ($cl['li']['media'][0]['x']["filename"]); ?>
                            </div>
                            <div class="document-file__type">
                                <?php echo ($cl['li']['media'][0]['x']["file_type"]); ?>-<?php echo cl_translate("FILE"); ?>
                            </div>
                            <div class="document-file__icon">
                                <?php echo cl_icon("open_in_new"); ?>
                            </div>
                        </a>
                    </div>
                <?php elseif ($cl['li']['type'] == 'gif' && not_empty($cl['li']['media'])): ?>
                    <div class="lozad-media">
                        <div class="publication-image">
                            <a class="fbox-media2" data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                <img class="lozad"
                                    data-src="<?php echo fetch_or_get($cl['li']['media'][0]['src'], ''); ?>"
                                    alt="GIF-Image">
                            </a>
                        </div>
                    </div>
                <?php elseif ($cl['li']['type'] == 'poll' && not_empty($cl['li']['poll'])): ?>
                    <div class="publication-poll-data" data-post-poll="<?php echo ($cl['li']['id']); ?>"
                        data-status="<?php echo ($cl['li']['poll']['has_voted']); ?>">
                        <div class="publication-poll-data-inner">
                            <?php foreach ($cl['li']['poll']['options'] as $i => $poll_data): ?>
                                <div class="poll-option-bar"
                                    onclick="SMColibri.vote_poll(<?php echo ($cl['li']['id']); ?>, <?php echo ($i); ?>);"
                                    data-poll-option="<?php echo ($i); ?>">
                                    <div class="bar-icon">
                                        <?php echo cl_ikon("ok-circle"); ?>
                                    </div>
                                    <div class="bar-text">
                                        <p>
                                            <?php echo $poll_data["option"]; ?>
                                        </p>
                                    </div>
                                    <div class="bar-num">
                                        <b>
                                            <?php if (not_empty($cl['li']['poll']['has_voted'])): ?>
                                                <?php echo $poll_data["percentage"]; ?>%
                                            <?php endif; ?>
                                        </b>
                                    </div>

                                    <?php if (not_empty($cl['li']['poll']['has_voted'])): ?>
                                        <span class="bar-slider"
                                            style="width: <?php echo $poll_data["percentage"]; ?>%;"></span>
                                    <?php else: ?>
                                        <span class="bar-slider"></span>
                                    <?php endif; ?>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php elseif (not_empty($cl['li']['og_data'])): ?>
                    <?php if (not_empty($cl['li']['og_data']['video_embed'])): ?>
                        <div class="publication-og-data">
                            <div class="publication-og-data-inner embeded-iframe">
                                <div class="og-image">
                                    <div class="lozad-media">
                                        <a href="<?php echo ($cl['li']['og_data']['video_embed']); ?>" class="fbox-media2"
                                            data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                            data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                            <img class="lozad" data-src="<?php echo ($cl['li']['og_data']['image']); ?>"
                                                alt="Video">
                                            <div class="og-icon">
                                                <span>
                                                    <?php echo cl_ikon("play"); ?>
                                                </span>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="og-url-data">
                                    <h5>
                                        <?php echo ($cl['li']['og_data']['title']); ?>
                                    </h5>
                                    <?php if (not_empty($cl['li']['og_data']['description'])): ?>
                                        <p>
                                            <?php echo ($cl['li']['og_data']['description']); ?>
                                        </p>
                                    <?php else: ?>
                                        <p>
                                            <a target="_blank" href="<?php echo ($cl['li']['og_data']['video_embed']); ?>">
                                                <?php echo ($cl['li']['og_data']['video_embed']); ?>
                                            </a>
                                        </p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php elseif (not_empty($cl['li']['og_data']['google_maps_embed'])): ?>
                        <div class="publication-og-data">
                            <div class="publication-og-data-inner embeded-iframe">
                                <div class="og-image">
                                    <div class="lozad-media">
                                        <a href="<?php echo ($cl['li']['og_data']['url']); ?>" class="fbox-media">
                                            <img class="lozad" data-src="<?php echo ($cl['li']['og_data']['image']); ?>"
                                                alt="Video">
                                            <div class="og-icon no-ml">
                                                <span>
                                                    <?php echo cl_ikon("location"); ?>
                                                </span>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="og-url-data">
                                    <h5>
                                        <?php echo ($cl['li']['og_data']['title']); ?>
                                    </h5>

                                    <?php if (not_empty($cl['li']['og_data']['description'])): ?>
                                        <p>
                                            <?php echo ($cl['li']['og_data']['description']); ?>
                                        </p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="publication-og-data">
                            <div class="publication-og-data-inner link">
                                <?php if (not_empty($cl['li']['og_data']['image'])): ?>
                                    <a href="<?php echo ($cl['li']['og_data']['image']); ?>" class="fbox-media2"
                                        data-btn='<?php echo cl_template('timeline/likes'); ?>' data-fancybox="gallery"
                                        data-info='<?php echo cl_template('timeline/right_col'); ?>'>
                                        <div class="og-image">
                                            <img src="<?php echo ($cl['li']['og_data']['image']); ?>" alt="IMG">
                                        </div>
                                    </a>
                                <?php endif; ?>

                                <div class="og-url-data">
                                    <h5>
                                        <?php echo ($cl['li']['og_data']['title']); ?>
                                    </h5>
                                    <p>
                                        <?php echo ($cl['li']['og_data']['description']); ?>
                                    </p>
                                    <a href="<?php echo ($cl['li']['og_data']['url']); ?>" target="_blank">
                                        <span class="pup-link-icon">
                                            <?php echo cl_ikon('pub-icon'); ?>
                                        </span><span class="pup-link-icon-a">
                                            <?php echo ($cl['li']['og_data']['url']); ?>
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<style>
   
  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-text {
  width: 100%;
  /* overflow: hidden; */
  display: block;
  line-height: 0px;
  margin-bottom: 10px;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-text
  p.pub-text {
  font-size: 15px;
  line-height: 20px;
  font-weight: 400;
  padding: 0;
  margin: 0;
  color: var(--smc-main-text-color);
  word-break: break-word;
  display: block;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-text
  p.pub-text
  a.inline-link {
  display: inline;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.lozad-media {
  width: 100%;
  display: block;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-image {
  width: 100%;
  border: 1px solid var(--smc-main-border-color);
  display: block;
  border-radius: var(--smc-main-border-rad1);
  overflow: hidden;
  background: #e6ecf0;
  position: relative;
  position: static;
  margin-top: 6px;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-image
  img.lozad {
  width: 100%;
  object-fit: cover;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-image
  img.lozad:not([data-loaded]) {
  visibility: hidden;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-image
  a.fbox-media2 {
  position: relative;
  display: block;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-image
  a.fbox-media2
  div.video-icon {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-image
  a.fbox-media2
  div.video-icon
  span {
  width: 45px;
  height: 45px;
  background: var(--smc-main-uiel-color);
  border-radius: 10em;
  padding: 5px;
  box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 10px 0px;
  border: 3px solid #fff;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-image
  a.fbox-media2
  div.video-icon
  span
  svg {
  width: 100%;
  height: 100%;
  fill: #fff;
  margin-left: 2px;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-images-collage {
  display: flex;
  gap: 2px;
  justify-content: center;
  flex-direction: row;
  flex-wrap: wrap;
  margin-top: 6px;
}

  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-images-collage
  a.fbox-media2
  div.publication-image {
  margin-top: 0px;
  max-height: 140px;
  border-radius: 0px;
}

  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-images-collage
  a.fbox-media2 {
  flex: 2 1 auto;
  width: 40%;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-images-collage
  a.fbox-media2
  div.image-collage-item {
  display: block;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-images-collage
  a.fbox-media2
  div.image-collage-item
  div.publication-image {
  border-radius: var(--smc-main-border-rad2);
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-audio
  audio {
  width: 100%;
  outline: 0;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data {
  width: 100%;
  display: block;
  line-height: 0;
  margin-bottom: 10px;
  overflow: hidden;
  background: var(--smc-main-bg-color);
  border-radius: var(--smc-main-border-rad1);
  border: 1px solid var(--smc-main-border-color);
  position: relative;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner {
  width: 100%;
  overflow: hidden;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe {
  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe
  div.og-image {
  width: 100%;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe
  div.og-image
  a {
  display: block;
  width: 100%;
  position: relative;
  text-decoration: none;
  line-height: 0;
  min-height: 200px;
  max-height: 300px;
  overflow: hidden;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe
  div.og-image
  a
  img {
  width: 100%;
  display: block;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe
  div.og-image
  a
  div.og-icon {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe
  div.og-image
  a
  div.og-icon
  span {
  width: 45px;
  height: 45px;
  background: var(--smc-main-uiel-color);
  border-radius: 10em;
  padding: 5px;
  box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 10px 0px;
  border: 3px solid #fff;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe
  div.og-image
  a
  div.og-icon
  span
  svg {
  width: 100%;
  height: 100%;
  fill: #fff;
  margin-left: 2px;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe
  div.og-image
  a
  div.og-icon.no-ml
  span
  svg {
  margin-left: 0px;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.embeded-iframe
  div.og-url-data
  p {
  margin-bottom: 0px;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.link {
  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.link
  div.og-image {
  width: 100%;
  overflow: hidden;
  border-bottom: 1px solid var(--smc-main-border-color);
  background: var(--smc-main-ehbg-color);
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner.link
  div.og-image
  img {
  width: 100%;
  display: block;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner
  div.og-url-data {
  flex: 1;
  padding: 15px;
  overflow: hidden;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner
  div.og-url-data
  h5,

  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner
  div.og-url-data
  p,

  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner
  div.og-url-data
  a {
  width: 100%;
  display: block;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner
  div.og-url-data
  h5 {
  padding: 0;
  margin: 0 0 15px 0;
  font-size: 16px;
  line-height: 1.4;
  color: var(--smc-main-text-color);
  word-wrap: break-word;
  font-weight: 700;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner
  div.og-url-data
  p {
  font-size: 15px;
  color: var(--smc-main-text-color-2);
  line-height: 1.4;
  padding: 0;
  margin: 0 0 15px 0;
  word-wrap: break-word;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-og-data
  div.publication-og-data-inner
  div.og-url-data
  a {
  overflow-wrap: break-word;
  color: var(--smc-main-text-color-2);
  font-weight: 400;
  font-size: 14px;
  line-height: 20px;
  cursor: pointer;
  line-height: 0;
  display: inline-block;
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
  width: 220px;
  text-decoration: none;
}

/* .pub-text .inline-link {
    display: none!important;
} */

.pub-text .inline-link.hash {
  display: inline-block !important;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data {
  width: 100%;
  display: block;
  line-height: 0;
  overflow: hidden;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner {
  width: 100%;
  display: block;
  line-height: 0;
  overflow: hidden;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner
  div.poll-option-bar {
  width: 100%;
  max-width: 100%;
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
  align-items: center;
  height: 30px;
  padding: 20px 15px;
  background: rgba(29, 161, 242, 0.1);
  margin-bottom: 10px;
  border-radius: 30px;
  cursor: pointer;
  overflow: hidden;
  position: relative;
  z-index: 1;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner
  div.poll-option-bar
  div.bar-icon {
  width: 22px;
  height: 22px;
  line-height: 0;
  min-height: 20px;
  min-width: 20px;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner
  div.poll-option-bar
  div.bar-icon
  svg {
  width: 100%;
  height: 100%;
  stroke: var(--smc-main-uiel-color);
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner
  div.poll-option-bar
  div.bar-text {
  flex-grow: 1;
  padding-left: 15px;
  padding-right: 15px;
  overflow: hidden;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner
  div.poll-option-bar
  div.bar-text
  p {
  padding: 0;
  margin: 0;
  display: block;
  width: 100%;
  max-width: 100%;
  font-size: 14px;
  line-height: 14px;
  color: var(--smc-main-text-color);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner
  div.poll-option-bar
  div.bar-num
  b {
  font-size: 14px;
  line-height: 14px;
  color: var(--smc-main-uiel-color);
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner
  div.poll-option-bar:last-child {
  margin-bottom: 0px;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data
  div.publication-poll-data-inner
  div.poll-option-bar
  span.bar-slider {
  display: block;
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  background: rgba(29, 161, 242, 0.2);
  max-width: 100%;
  min-width: 10px;
  border-radius: 0px;
  z-index: 3;
}


  div.post-list-item-content
  div.publication-data
  div.publication-data-inner
  div.publication-content
  div.publication-poll-data[data-status="1"]
  div.publication-poll-data-inner
  div.poll-option-bar {
  cursor: default;
}

</style>