<div class="modal fade" data-app="cl-account-info" tabindex="-1" role="dialog" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form" id="cl-account-info-vue-app" v-on:submit="submit_form($event)">
                <div class="modal-header">
                    <div class="main---mh--block">
                        <h5 class="modal-title">
                            <?php echo cl_translate("Download my information"); ?>
                        </h5>
                        <span class="dismiss-modal" data-dismiss="modal">
                            <?php echo cl_ikon('close'); ?>
                        </span>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="popup-modal-form"> 
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="form-check">
                                    <input v-model="form_data.my_info" type="checkbox" class="form-check-input">
                                    <label class="form-check-label">
                                        <span>
                                            <?php echo cl_translate("My information"); ?>
                                        </span>

                                        <p class="form-info-label">
                                            <?php echo cl_translate("My information"); ?>
                                        </p>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="form-check">
                                    <input v-model="form_data.following" type="checkbox" class="form-check-input">
                                    <label class="form-check-label">
                                        <span>
                                            <?php echo cl_translate("Followings"); ?>
                                        </span>
                                        <p class="form-info-label">
                                            <?php echo cl_translate("List of people I follow"); ?>
                                        </p>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="form-check">
                                    <input v-model="form_data.followers" type="checkbox" class="form-check-input">
                                    <label class="form-check-label">
                                        <span>
                                            <?php echo cl_translate("Followers"); ?>
                                        </span>
                                        <p class="form-info-label">
                                            <?php echo cl_translate("List of people who follow me"); ?>
                                        </p>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="form-check">
                                    <input v-model="form_data.posts" type="checkbox" class="form-check-input">
                                    <label class="form-check-label">
                                        <span>
                                            <?php echo cl_translate("Posts"); ?>
                                        </span>
                                        <p class="form-info-label">
                                            <?php echo cl_translate("List of my publications and replies"); ?>
                                        </p>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="form-check">
                                    <input v-model="form_data.bookmarks" type="checkbox" class="form-check-input">
                                    <label class="form-check-label">
                                        <span>
                                            <?php echo cl_translate("Saved posts"); ?>
                                        </span>
                                        <p class="form-info-label">
                                            <?php echo cl_translate("List of my bookmarks"); ?>
                                        </p>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group no-mb">
                            <p class="form-info-label">
                                <?php echo cl_translate("Check the boxes in the options to select the account information you want to download"); ?>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button v-if="submitting != true" v-bind:disabled="is_invalid_form" type="submit" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Download info"); ?>
                    </button>
                    <button v-else disabled="true" type="button" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Please wait"); ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>