<div class="cp-app-container" data-app="sitemap">
<div class="container-fluid">        
            <div class="page-title">
              <div class="row">
                <div class="col-6">
                  <h3>   <?php echo cl_translate('Sitemap'); ?></h3>
                </div>
                <div class="col-6">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>">                                    <i data-feather="home"></i></a></li>
                    <li class="breadcrumb-item">  <?php echo cl_translate('Sitemap'); ?></li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
    <div class="container-fluid">
            <div class="row">
              <div class="col-sm-12">
              <div class="card" data-an="info-content">
                  <div class="card-header">
                    <h5>
                      <?php echo cl_translate('Generate sitemap'); ?>
                    </h5>
                </div>
   
  
               <div class="card-body">
                    <form class="form" data-an="form">
                        <div class="alert alert-dark dark alert-dismissible fade show" role="alert">
                               
                                    <p>
                                      <i class="icon-info-alt"></i>   <?php echo('Please note that the process of creating a site map can take several minutes or even more, depending on the amount of content on your site, so after clicking the button update the site map, wait until the process is complete without leaving the page, otherwise, the process will fail!'); ?>
                                    </p>
                               
                         
                        </div>
                        <div class="alert alert-dark dark alert-dismissible fade show" role="alert">
                               
                                   <p>
                                        A sitemap is created by splitting CML files into small parts, connecting them through one file, which is an index file, this file that you need to specify when registering your site with search engines. (Submitting your sitemap to Google, etc..)
                                    </p>
                                    <hr>
                                    <p>
                                        Here is the url to this file: <a href="<?php echo cl_link('sitemap/sitemap-index.xml'); ?>" target="_blank"><?php echo cl_link('sitemap/sitemap-index.xml'); ?></a>
                                    </p>
                         
                        </div>
                        <div class="form-group">
                            <?php if (not_empty($cl['config']['sitemap_update'])): ?>
                                <h5>
                                    <span>
                                        <?php echo cl_translate('Last sitemap update'); ?>
                                    </span>
                                    <time data-an="last-sitemap-date">
                                        (<?php echo date('d F, Y - h:m', $cl['config']['sitemap_update']); ?>)
                                    </time>    
                                </h5>
                            <?php else: ?>
                                <h5>
                                    <span><?php echo cl_translate('Last sitemap update'); ?></span>
                                    <time data-an="last-sitemap-date">(00/00/0000 - 00:00)</time>
                                </h5>
                            <?php endif; ?>
                        </div>
                         <div class="row">
                            <div class="col-sm-12 no-mb">
                            <button class="btn btn-primary" type="submit" data-an="submit-ctrl">
                                <?php echo cl_translate("Update sitemap!"); ?>
                           </button>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<?php echo cl_template('cpanel/assets/sitemap/scripts/app_master_script'); ?>