
<div class="cp-app-container" data-app="users">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3> <?php echo cl_translate('pages_create'); ?></h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>"> <i
                                    data-feather="home"></i></a></li>
                        <li class="breadcrumb-item"> <?php echo cl_translate('pages_create'); ?></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            <?php echo cl_translate('pages_create'); ?>
                        </h5>
                    </div>
                    <form class="form mega-inline"  data-an="form" method="post" action="">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group" data-an="name-input">
                                    <label>
                                        <?php echo cl_translate('title_page'); ?>
                                    </label>
                                    <div class="input-group"><span class="input-group-text"><i
                                                class="icofont icofont-pencil-alt-5"></i></span>
                                        <input value="" name="fname" id="fname" type="text" class="form-control"
                                            placeholder="<?php echo cl_translate('enter_the_name_of_your_page'); ?>">
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group" data-an="title-input">
                                    <label for="username">
                                        <?php echo cl_translate('symbols'); ?>
                                    </label>
                                    <div class="input-group"><span class="input-group-text"><i
                                                class="icofont icofont-pencil-alt-5"></i></span>
                                        <input value="" name="username" id="username" type="text" class="form-control"
                                            placeholder="<?php echo cl_translate('enter_the_symbol_of_your_page'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                            <div class="form-group" data-an="email-input">
                                    <label for="email">
                                    <?php echo cl_translate('E-mail address'); ?>
                                    </label>
                                    <div class="input-group"><span class="input-group-text">@</span>
                                        <input value="" name="email" id="email" class="form-control" placeholder="<?php echo cl_translate('enter_the_email_of_your_page'); ?>">
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group" data-an="title-input">
                                    <label for="website">
                                        <?php echo cl_translate('website'); ?>
                                    </label>
                                    <div class="input-group"><span class="input-group-text"><i
                                                class="icofont icofont-pencil-alt-5"></i></span>
                                        <input value="" name="website" id="website" type="text" class="form-control"
                                            placeholder="<?php echo cl_translate('enter_the_url_of_your_page'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" data-an="description-input">
                                    <label for="about">
                                    <?php echo cl_translate('about'); ?>
                                    </label>
                                    <div class="form-line">
                                        <textarea  name="about" id="about" class="form-control" rows="2" placeholder="<?php echo cl_translate('enter_the_about_of_your_page'); ?>"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <button data-an="submit-ctrl" type="submit" class="btn btn-primary">
                                <?php echo cl_translate("Create"); ?>
                                </button>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                               
                        <div class="alert alert-light dark" role="alert" style="margin-top: 15px; margin-bottom: 15px;">
                      <p>After creating the page, you can add other data. Upload avatar, cover</p>
                    </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/pages_create/scripts/app_master_script'); ?>