<div class="timeline-placeholder" style="padding-top: 0px;">
	<div class="pl-message">
		<h4>
			<?php echo ($cl['prof_user']['name']); ?>
		</h4>
		<h4>
			$<?php echo ($cl['prof_user']['username']); ?>
		</h4>
		<p>
			<?php echo $cl['prof_user']['country_name']; ?>
		</p>
		<p>
			<?php echo $cl['prof_user']['joined']; ?>
		</p>
		<p>
			<?php echo $cl['symbol']['email']; ?>
		</p>
		<p>
			<?php echo $cl['symbol']['about']; ?>
		</p>
	</div>
</div>