<div class="timeline-placeholder">
	<div class="pl-message">
		<h4>
			<?php echo ($cl['prof_user']['name']); ?>
		</h4>
		<h4>
			$<?php echo ($cl['prof_user']['username']); ?>
		</h4>
		<p>
			<?php echo $cl['prof_user']['id']; ?>
		</p>
		<p>
			<?php echo $cl['prof_user']['country_name']; ?>
		</p>
		<p>
			<?php echo $cl['prof_user']['joined']; ?>
		</p>
		<p>
			<?php echo $cl['symbol']['email']; ?>
		</p>
		<p>
			<?php echo $cl['symbol']['about']; ?>
		</p>
		<p>
			<?php echo $cl['symbol']['symbol_fetch']; ?>
		</p>
		<?php foreach($cl['prof_user']['questions'] as $cl['question']): ?>
			<p><?php echo $cl['question']['title']; ?> : <?php echo $cl['question']['answer']; ?></p>
		<?php endforeach; ?>
	</div>
</div>