<div class="timeline-placeholder" style="padding-top: 0px;">
	
	<div class="icon">
		<div class="icon__bg">
			<?php echo cl_icon('thumb_up'); ?>
		</div>
	</div>

	<div class="pl-message">
		<h4 class="flex justify-center">
			<?php echo cl_translate("No favourite posts yet!"); ?>
		</h4>
		<p>
			<?php echo cl_translate("No favorite posts for this coin yet. Like posts about this coin, and they'll appear here if selected by our algorithm."); ?>
		</p>
	</div>
	<div class="c2action-single">
		<a href="<?php echo cl_link('/'); ?>">
			<button class="btn btn-custom main-inline lg">
				<?php echo cl_translate("Go to the homepage"); ?>
			</button>
		</a>
	</div>
</div>