<div class="cp-app-container" data-app="ads-settings">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3> <?php echo cl_translate('advertising_setting'); ?></h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>"> <i data-feather="home"></i></a></li>
                        <li class="breadcrumb-item"> <?php echo cl_translate('advertising_setting'); ?></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="d-block" id="vue-cpanel-users-app">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card" style="padding: 15px;">
                        <div class="card-header">
                            <h5>
                                <?php echo cl_translate(' Manage advertising system settings'); ?>
                            </h5>
                        </div>


                        <form class="form" data-an="form">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group" data-an="ad_conversion_rate-input">
                                            <label>
                                                Ad conversion rate
                                            </label>
                                            <div class="input-group"><span class="input-group-text"><i class="icofont icofont-pencil-alt-5"></i></span>
                                                <input value="{%config ad_conversion_rate%}" name="ad_conversion_rate" type="text" class="form-control" placeholder="E. g. 0.05">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-sm-12">
                                        <div class="form-group" data-an="advertising_system-input">
                                            <label>
                                                Advertising system
                                            </label>
                                            <div class="input-group"><span class="input-group-text"><i class="icofont icofont-toggle-on"></i></span>
                                                <select name="advertising_system" class="form-select form-control-primary">
                                                    <option value="on" <?php if ($cl['config']['advertising_system'] == 'on') {
                                                                            echo ('selected');
                                                                        } ?>>
                                                        <?php echo cl_translate('Enabled'); ?>
                                                    </option>
                                                    <option value="off" <?php if ($cl['config']['advertising_system'] == 'off') {
                                                                            echo ('selected');
                                                                        } ?>>
                                                        <?php echo cl_translate('Disabled'); ?>
                                                    </option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 no-mb">
                                        <button class="btn btn-primary" type="submit" data-an="submit-ctrl">
                                            Save changes
                                        </button>
                                    </div>
                                </div>
                                <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php echo cl_template('cpanel/assets/ads_settings/scripts/app_master_script'); ?>