<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
	<div class="h-laptop">
		<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
			<div class="mobile-bottom-navbar-inner">
				<div class="avatar-menu">
					<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
				</div>

			</div>
		</div>
	</div>
<?php endif; ?>
<div class="timeline-container" data-app="err404">
	<div class="timeline-header symbol_header" data-el="tl-header">
		<?php echo cl_template('common/bot_line'); ?>
		<div class="lp" style="display: inline-flex; align-items:center; padding-top:10px;">
			<div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
				<span class="go-back" onclick="SMColibri.go_back();">
					<?php echo cl_ikon('arrow-left'); ?>
				</span>
				<a href="<?php echo cl_link("404"); ?>" data-spa="true">
					<?php echo cl_translate('Error 404'); ?>
				</a>
			</div>
		</div>
	</div>
	<div class="timeline-placeholder" style="padding-top:10px;">
		<div class="icon">
			<div class="icon__bg_img">
				<img src="{%config theme_url%}/statics/img/404-erro.png">
			</div>
		</div>
		<div class="pl-message">
			<h4>
				<?php echo cl_translate('Page not found!'); ?>
			</h4>
			<p>
				<?php echo cl_translate("Sorry, we cannot find the page you are looking for.<br>You can either return to the previous page, or return to the homepage or visit our {@link@} page if you have questions about this error.", array(
					'link' => cl_html_el('a', 'F.Q.A', array('href' => cl_link('faqs')))
				)); ?>
			</p>
		</div>
		<div class="c2action-single">
			<a href="<?php echo cl_link('/'); ?>" data-spa="true">
				<button class="btn btn-custom main-inline lg">
					<?php echo cl_translate("Go to your feed"); ?>
				</button>
			</a>
		</div>
	</div>
</div>