<div class="timeline-container" data-app="err404">
	<div class="timeline-header" data-el="tl-header">
		<div class="timeline-header__botline">
			<div class="lp">
				<div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
					<span class="go-back" onclick="SMColibri.go_back();">
						<?php echo cl_ikon('arrow-left'); ?>
					</span>
					<a href="<?php echo cl_link("404"); ?>" data-spa="true">
						<?php echo cl_translate('Error 404'); ?>
					</a>
				</div>
			</div>
			<div class="cp">

			</div>
		</div>

	</div>
	<div class="timeline-placeholder" style="padding-top:10px;">
		<div class="icon">
			<div class="icon__bg_img">
				<img src="{%config theme_url%}/statics/img/404-erro.png">
			</div>
		</div>
		<div class="pl-message">
			<h4>
				<?php echo cl_translate('Page not found!'); ?>
			</h4>
			<p>
				<?php echo cl_translate("Sorry, we cannot find the page you are looking for.<br>You can either return to the previous page, or return to the homepage or visit our {@link@} page if you have questions about this error.", array(
					'link' => cl_html_el('a', 'F.Q.A', array('href' => cl_link('faqs')))
				)); ?>
			</p>
		</div>
		<div class="c2action-single">
			<a href="<?php echo cl_link('/'); ?>" data-spa="true">
				<button class="btn btn-custom main-inline lg">
					<?php echo cl_translate("Go to your feed"); ?>
				</button>
			</a>
		</div>
	</div>
</div>