<div class="cp-app-container" data-app="google-ads">
    <div class="container-fluid">
        <div class="page-title">
            <div class="row">
                <div class="col-6">
                    <h3> <?php echo cl_translate("Google AdSense"); ?></h3>
                </div>
                <div class="col-6">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"> <a href="<?php echo cl_link('admin_panel'); ?>"> <i data-feather="home"></i></a></li>
                        <li class="breadcrumb-item"> <?php echo cl_translate("Google AdSense"); ?></li>

                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            <?php echo cl_translate("Manage (Google AdSense) system settings"); ?>
                        </h5>
                    </div>

                    <form class="form mega-inline" data-an="form">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group" data-an="google_ad_horiz-input">
                                        <label>
                                            <?php echo cl_translate("Horizontal ads banner"); ?>
                                        </label>
                                        <div class="form-line">
                                            <textarea name="google_ad_horiz" class="form-control" rows="2" placeholder="<?php echo cl_translate("Enter a JS for horizontal ads banner"); ?>" spellcheck="false">{%config google_ad_horiz%}</textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group" data-an="google_ad_vert-input">
                                        <label>
                                            <?php echo cl_translate("Vertical ads banner"); ?>
                                        </label>
                                        <div class="form-line">
                                            <textarea name="google_ad_vert" class="form-control" rows="2" placeholder="<?php echo cl_translate("Enter a JS for vertical ads banner"); ?>" spellcheck="false">{%config google_ad_vert%}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 no-mb">
                                    <button class="btn btn-primary" type="submit" data-an="submit-ctrl">
                                        <?php echo cl_translate("Save changes"); ?>
                                    </button>
                                </div>
                            </div>
                            <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/google_ads/scripts/app_master_script'); ?>