<?php 
# @*************************************************************************@
# @ Software author: JOOJ Team (JOOJ.us)                                    @
# @ Author_url 1: https://jooj.us                                           @
# @ Author_url 2: http://jooj.us/twitter-clone                              @
# @ Author E-mail: sales@jooj.us                                            @
# @*************************************************************************@
# @ JOOJ Talk - The Ultimate Modern Social Media Sharing Platform           @
# @ Copyright (c) 2020 - 2023 JOOJ Talk. All rights reserved.               @
# @*************************************************************************@


$cl                 = array();
$applications       = array(
	"main"          => true,
    "home"          => true,
	"guest"         => true,
	"404"           => true,
	"auth"          => true,
	"logout"        => true,
	"settings"      => true,
    "profile"       => true,
    "connections"   => true,
    "watchings"   => true,
    "suggested"     => true,
    "trending"      => true,
    "symbols"      => true,
    "search"        => true,
    "explore"       => true,
    "chats"         => true,
    "conversation"  => true,
    "thread"        => true,
    "tmedia"        => true,
    "feed"          => true,
    "bookmarks"     => true,
    "stat_pages"    => true,
    "notifications" => true,
    "affiliates"    => true,
    "ads"           => true,
    "cpanel"        => true,
    "oauth"         => true,
    "err404"        => true,
    "confirm_reg"   => true,
    "confirm_email" => true,
    "wallet"        => true,
    "err500"        => true,
    "swift"         => true,
    "ad_item"       => true,
    "download_info" => true,
    "edit_post"     => true,
    "edit_post_blue"     => true,
    "start_up"      => true,
    "custom_apps"   => true,
    "wallet_banktrans" => true,
    "premium_account" => true,
    "premium_features" => true,
    "blue_account" => true,
    "blue_features" => true,
    "wallet_add" => true,
    "wallet_send" => true,
    "spa_load"      => true,
    "pages_symbol" => true,
    "symbol" => true,
    "page_settings" => true
);

$cl['profile_report_types'] = array(
    '1' => 'This user using this account for smap',
    '2' => 'This user pretended to be someone',
    '3' => 'This user posting inappropriate content',
    '4' => 'This is a fake account',
    '5' => 'This is a fraudulent account',
    '6' => 'Other',
);

$cl['symbol_report_types'] = array(
  '1' => 'This coin using this account for smap',
  '2' => 'This coin pretended to be someone',
  '3' => 'This coin posting inappropriate content',
  '4' => 'This is a deleted coin',
  '5' => 'This is a fraudulent coin',
  '6' => 'Other',
);

$cl['post_report_types'] = array(
    '1' => 'This is spam',
    '2' => 'Misleading or fraudulent',
    '3' => 'Publication of private information',
    '4' => 'Threats of violence or physical harm',
    '5' => 'I am not interested in this post',
    '6' => 'Other'
);

$cl['site_currencies'] = array(
    'usd' => array(
        'name' => 'United states dollar',
        'symbol' => '$'
    ),
    'eur' => array(
        'name' => 'EU Euro',
        'symbol' => '€'
    ),
    'rub' => array(
        'name' => 'Russian ruble',
        'symbol' => '₽'
    ),
    'brl' => array(
        'name' => 'Brazilian real',
        'symbol' => 'R$'
    ),
    'gbp' => array(
        'name' => 'Pound sterling',
        'symbol' => '£'
    ),
    'tl' => array(
        'name' => 'Turkish lira',
        'symbol' => '₺'
    ),
    'inr' => array(
        'name' => 'Indian rupee',
        'symbol' => '₹'
    ),
    'jpy' => array(
        'name' => 'Japanese yen',
        'symbol' => '¥'
    ),
    'ghs' => array(
        'name' => 'Ghanaian cedi',
        'symbol' => 'GH₵'
    ),
    'ngn' => array(
        'name' => 'Nigerian naira',
        'symbol' => '₦'
    ),
    'zar' => array(
        'name' => 'South African rand',
        'symbol' => 'ZAR'
    ),
    'sgd' => array(
        'name' => 'Singapore Dollar',
        'symbol' => 'S$'
    ),
    'aud' => array(
        'name' => 'Australian Dollar',
        'symbol' => 'A$'
    ),
    'cad' => array(
        'name' => 'Canadian Dollar',
        'symbol' => 'C$'
    ),
    'hkd' => array(
        'name' => 'Hong Kong Dollar',
        'symbol' => 'HK$'
    ),
    'myr' => array(
        'name' => 'Malaysian Ringgit',
        'symbol' => 'MYR'
    ),
);

$cl["ui_rand_colors"] = array(
    "#9857BC", 
    "#1ABC9C",
    "#F1C40F",
    "#F39C12",
    "#2ECC71",
    "#C0392B",
    "#34495E",
    "#B49255",
    "#3498DB",
    "#EC87BF",
    "#873202",
    "#8E44AD",
    "#34495E",
    "#95A5A6",
    "#2980B9"
);

$cl["color_schemes"] = array(
    "default" => array(
        "name" => "Default",
        "color" => "#1DA1F2",
        "icon" => "whale"
    ),
    "yellow" => array(
        "name" => "Yellow",
        "color" => "#FDAD1F",
        "icon" => "lemon"
    ),
    "pink" => array(
        "name" => "Pink",
        "color" => "#E0245E",
        "icon" => "tomato"
    ),
    "purple" => array(
        "name" => "Purple",
        "color" => "#794BC4",
        "icon" => "grape"
    ),
    "orange" => array(
        "name" => "Orange",
        "color" => "#F45D22",
        "icon" => "orange"
    ),
    "green" => array(
        "name" => "Green",
        "color" => "#2FBF63",
        "icon" => "avocado"
    )
);

$cl["bg_colors"] = array(
  "default" => array(
      "name" => "Default",
      "color" => "#fff",
      "icon" => "white-mode"
  ),
  "dark" => array(
      "name" => "Dark",
      "color" => "#15202b",
      "icon" => "dim-mode"
),
    "black" => array(
        "name" => "Black",
        "color" => "#000",
        "icon" => "black-mode"
    )
);

$cl["media_mime_types"] = array(
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/webp',
    'video/mp4',
    'video/quicktime',
    'video/3gpp',
    'video/x-flv',
    'video/mpeg',
    'audio/wav',
    'audio/x-wav',
    'audio/mpeg',
    'video/ogg',
    'video/webm',
    'video/x-ms-wmv',
    'video/3gpp2',
    'application/pdf',
    'text/html',
    'application/xhtml+xml',
    'application/vnd.oasis.opendocument.text',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.oasis.opendocument.spreadsheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/plain'
);

$cl['countries'] = array(
    '1' => 'United States',
    '2' => 'Canada',
    '3' => 'Afghanistan',
    '4' => 'Albania',
    '5' => 'Algeria',
    '6' => 'American Samoa',
    '7' => 'Andorra',
    '8' => 'Angola',
    '9' => 'Anguilla',
    '10' => 'Antarctica',
    '11' => 'Antigua and/or Barbuda',
    '12' => 'Argentina',
    '13' => 'Armenia',
    '14' => 'Aruba',
    '15' => 'Australia',
    '16' => 'Austria',
    '17' => 'Azerbaijan',
    '18' => 'Bahamas',
    '19' => 'Bahrain',
    '20' => 'Bangladesh',
    '21' => 'Barbados',
    '22' => 'Belarus',
    '23' => 'Belgium',
    '24' => 'Belize',
    '25' => 'Benin',
    '26' => 'Bermuda',
    '27' => 'Bhutan',
    '28' => 'Bolivia',
    '29' => 'Bosnia and Herzegovina',
    '30' => 'Botswana',
    '31' => 'Bouvet Island',
    '32' => 'Brazil',
    '34' => 'Brunei Darussalam',
    '35' => 'Bulgaria',
    '36' => 'Burkina Faso',
    '37' => 'Burundi',
    '38' => 'Cambodia',
    '39' => 'Cameroon',
    '40' => 'Cape Verde',
    '41' => 'Cayman Islands',
    '42' => 'Central African Republic',
    '43' => 'Chad',
    '44' => 'Chile',
    '45' => 'China',
    '46' => 'Christmas Island',
    '47' => 'Cocos (Keeling) Islands',
    '48' => 'Colombia',
    '49' => 'Comoros',
    '50' => 'Congo',
    '51' => 'Cook Islands',
    '52' => 'Costa Rica',
    '53' => 'Croatia (Hrvatska)',
    '54' => 'Cuba',
    '55' => 'Cyprus',
    '56' => 'Czech Republic',
    '57' => 'Denmark',
    '58' => 'Djibouti',
    '59' => 'Dominica',
    '60' => 'Dominican Republic',
    '61' => 'East Timor',
    '62' => 'Ecuador',
    '63' => 'Egypt',
    '64' => 'El Salvador',
    '65' => 'Equatorial Guinea',
    '66' => 'Eritrea',
    '67' => 'Estonia',
    '68' => 'Ethiopia',
    '69' => 'Falkland Islands (Malvinas)',
    '70' => 'Faroe Islands',
    '71' => 'Fiji',
    '72' => 'Finland',
    '73' => 'France',
    '74' => 'France, Metropolitan',
    '75' => 'French Guiana',
    '76' => 'French Polynesia',
    '77' => 'French Southern Territories',
    '78' => 'Gabon',
    '79' => 'Gambia',
    '80' => 'Georgia',
    '81' => 'Germany',
    '82' => 'Ghana',
    '83' => 'Gibraltar',
    '84' => 'Greece',
    '85' => 'Greenland',
    '86' => 'Grenada',
    '87' => 'Guadeloupe',
    '88' => 'Guam',
    '89' => 'Guatemala',
    '90' => 'Guinea',
    '91' => 'Guinea-Bissau',
    '92' => 'Guyana',
    '93' => 'Haiti',
    '94' => 'Heard and Mc Donald Islands',
    '95' => 'Honduras',
    '96' => 'Hong Kong',
    '97' => 'Hungary',
    '98' => 'Iceland',
    '99' => 'India',
    '100' => 'Indonesia',
    '101' => 'Iran (Islamic Republic of)',
    '102' => 'Iraq',
    '103' => 'Ireland',
    '104' => 'Israel',
    '105' => 'Italy',
    '106' => 'Ivory Coast',
    '107' => 'Jamaica',
    '108' => 'Japan',
    '109' => 'Jordan',
    '110' => 'Kazakhstan',
    '111' => 'Kenya',
    '112' => 'Kiribati',
    '113' => 'Korea, Democratic People\'s Republic of',
    '114' => 'Korea, Republic of',
    '115' => 'Kosovo',
    '116' => 'Kuwait',
    '117' => 'Kyrgyzstan',
    '118' => 'Lao People\'s Democratic Republic',
    '119' => 'Latvia',
    '120' => 'Lebanon',
    '121' => 'Lesotho',
    '122' => 'Liberia',
    '123' => 'Libyan Arab Jamahiriya',
    '124' => 'Liechtenstein',
    '125' => 'Lithuania',
    '126' => 'Luxembourg',
    '127' => 'Macau',
    '128' => 'Macedonia',
    '129' => 'Madagascar',
    '130' => 'Malawi',
    '131' => 'Malaysia',
    '132' => 'Maldives',
    '133' => 'Mali',
    '134' => 'Malta',
    '135' => 'Marshall Islands',
    '136' => 'Martinique',
    '137' => 'Mauritania',
    '138' => 'Mauritius',
    '139' => 'Mayotte',
    '140' => 'Mexico',
    '141' => 'Micronesia, Federated States of',
    '142' => 'Moldova, Republic of',
    '143' => 'Monaco',
    '144' => 'Mongolia',
    '145' => 'Montenegro',
    '146' => 'Montserrat',
    '147' => 'Morocco',
    '148' => 'Mozambique',
    '149' => 'Myanmar',
    '150' => 'Namibia',
    '151' => 'Nauru',
    '152' => 'Nepal',
    '153' => 'Netherlands',
    '154' => 'Netherlands Antilles',
    '155' => 'New Caledonia',
    '156' => 'New Zealand',
    '157' => 'Nicaragua',
    '158' => 'Niger',
    '159' => 'Nigeria',
    '160' => 'Niue',
    '161' => 'Norfork Island',
    '162' => 'Northern Mariana Islands',
    '163' => 'Norway',
    '164' => 'Oman',
    '165' => 'Pakistan',
    '166' => 'Palau',
    '167' => 'Panama',
    '168' => 'Papua New Guinea',
    '169' => 'Paraguay',
    '170' => 'Peru',
    '171' => 'Philippines',
    '172' => 'Pitcairn',
    '173' => 'Poland',
    '174' => 'Portugal',
    '175' => 'Puerto Rico',
    '176' => 'Qatar',
    '177' => 'Reunion',
    '178' => 'Romania',
    '179' => 'Russian Federation',
    '180' => 'Rwanda',
    '181' => 'Saint Kitts and Nevis',
    '182' => 'Saint Lucia',
    '183' => 'Saint Vincent and the Grenadines',
    '184' => 'Samoa',
    '185' => 'San Marino',
    '186' => 'Sao Tome and Principe',
    '187' => 'Saudi Arabia',
    '188' => 'Senegal',
    '189' => 'Serbia',
    '190' => 'Seychelles',
    '191' => 'Sierra Leone',
    '192' => 'Singapore',
    '193' => 'Slovakia',
    '194' => 'Slovenia',
    '195' => 'Solomon Islands',
    '196' => 'Somalia',
    '197' => 'South Africa',
    '198' => 'South Georgia South Sandwich Islands',
    '199' => 'Spain',
    '200' => 'Sri Lanka',
    '201' => 'St. Helena',
    '202' => 'St. Pierre and Miquelon',
    '203' => 'Sudan',
    '204' => 'Suriname',
    '205' => 'Svalbarn and Jan Mayen Islands',
    '206' => 'Swaziland',
    '207' => 'Sweden',
    '208' => 'Switzerland',
    '209' => 'Syrian Arab Republic',
    '210' => 'Taiwan',
    '211' => 'Tajikistan',
    '212' => 'Tanzania, United Republic of',
    '213' => 'Thailand',
    '214' => 'Togo',
    '215' => 'Tokelau',
    '216' => 'Tonga',
    '217' => 'Trinidad and Tobago',
    '218' => 'Tunisia',
    '219' => 'Turkey',
    '220' => 'Turkmenistan',
    '221' => 'Turks and Caicos Islands',
    '222' => 'Tuvalu',
    '223' => 'Uganda',
    '224' => 'Ukraine',
    '225' => 'United Arab Emirates',
    '226' => 'United Kingdom',
    '227' => 'United States minor outlying islands',
    '228' => 'Uruguay',
    '229' => 'Uzbekistan',
    '230' => 'Vanuatu',
    '231' => 'Vatican City State',
    '232' => 'Venezuela',
    '233' => 'Vietnam',
    '238' => 'Yemen',
    '239' => 'Yugoslavia',
    '241' => 'Zambia',
    '242' => 'Zimbabwe'
);

$cl['country_codes'] = array(
    '1' => 'us',
    '2' => 'ca',
    '3' => 'af',
    '4' => 'al',
    '5' => 'dz',
    '6' => 'as',
    '7' => 'ad',
    '8' => 'ao',
    '9' => 'ai',
    '10' => 'aq',
    '11' => 'ag',
    '12' => 'ar',
    '13' => 'am',
    '14' => 'aw',
    '15' => 'au',
    '16' => 'at',
    '17' => 'az',
    '18' => 'bs',
    '19' => 'bh',
    '20' => 'bd',
    '21' => 'bb',
    '22' => 'by',
    '23' => 'be',
    '24' => 'bz',
    '25' => 'bj',
    '26' => 'bm',
    '27' => 'bt',
    '28' => 'bo',
    '29' => 'ba',
    '30' => 'bw',
    '31' => 'bv',
    '32' => 'br',
    '34' => 'bn',
    '35' => 'bg',
    '36' => 'bf',
    '37' => 'bi',
    '38' => 'kh',
    '39' => 'cm',
    '40' => 'cv',
    '41' => 'ky',
    '42' => 'cf',
    '43' => 'td',
    '44' => 'cl',
    '45' => 'cn',
    '46' => 'cx',
    '47' => 'cc',
    '48' => 'co',
    '49' => 'cm',
    '50' => 'cg',
    '51' => 'ck',
    '52' => 'cr',
    '53' => 'hr',
    '54' => 'cu',
    '55' => 'cy',
    '56' => 'cz',
    '57' => 'dk',
    '58' => 'dj',
    '59' => 'dm',
    '60' => 'do',
    '61' => 'tl',
    '62' => 'ec',
    '63' => 'eg',
    '64' => 'sv',
    '65' => 'gq',
    '66' => 'er',
    '67' => 'ee',
    '68' => 'et',
    '69' => 'fk',
    '70' => 'fo',
    '71' => 'fj',
    '72' => 'fi',
    '73' => 'fr',
    '74' => 'fr',
    '75' => 'gf',
    '76' => 'pf',
    '77' => 'tf',
    '78' => 'ga',
    '79' => 'gm',
    '80' => 'ge',
    '81' => 'de',
    '82' => 'gh',
    '83' => 'gi',
    '84' => 'gr',
    '85' => 'gl',
    '86' => 'gd',
    '87' => 'gp',
    '88' => 'gu',
    '89' => 'gt',
    '90' => 'gn',
    '91' => 'gw',
    '92' => 'gy',
    '93' => 'ht',
    '94' => 'hm',
    '95' => 'hn',
    '96' => 'hk',
    '97' => 'hu',
    '98' => 'is',
    '99' => 'in',
    '100' => 'id',
    '101' => 'ir',
    '102' => 'iq',
    '103' => 'ie',
    '104' => 'il',
    '105' => 'it',
    '106' => 'ci',
    '107' => 'jm',
    '108' => 'jp',
    '109' => 'jo',
    '110' => 'kz',
    '111' => 'ke',
    '112' => 'ki',
    '113' => 'kp',
    '114' => 'kr',
    '115' => 'al',
    '116' => 'kw',
    '117' => 'kg',
    '118' => 'la',
    '119' => 'lv',
    '120' => 'lb',
    '121' => 'ls',
    '122' => 'lr',
    '123' => 'ly',
    '124' => 'li',
    '125' => 'lt',
    '126' => 'lu',
    '127' => 'mo',
    '128' => 'mk',
    '129' => 'mg',
    '130' => 'mw',
    '131' => 'my',
    '132' => 'mv',
    '133' => 'ml',
    '134' => 'mt',
    '135' => 'mh',
    '136' => 'mq',
    '137' => 'mr',
    '138' => 'mu',
    '139' => 'yt',
    '140' => 'mx',
    '141' => 'fm',
    '142' => 'md',
    '143' => 'mk',
    '144' => 'mn',
    '145' => 'me',
    '146' => 'ms',
    '147' => 'ma',
    '148' => 'mz',
    '149' => 'mm',
    '150' => 'na',
    '151' => 'nr',
    '152' => 'np',
    '153' => 'nl',
    '154' => 'nl',
    '155' => 'nc',
    '156' => 'nz',
    '157' => 'ni',
    '158' => 'ne',
    '159' => 'ng',
    '160' => 'nu',
    '161' => 'nf',
    '162' => 'mp',
    '163' => 'no',
    '164' => 'om',
    '165' => 'pk',
    '166' => 'pw',
    '167' => 'pa',
    '168' => 'pg',
    '169' => 'py',
    '170' => 'cn',
    '171' => 'ph',
    '172' => 'pn',
    '173' => 'pl',
    '174' => 'pt',
    '175' => 'pr',
    '176' => 'qa',
    '177' => 're',
    '178' => 'ro',
    '179' => 'ru',
    '180' => 'rw',
    '181' => 'kn',
    '182' => 'lc',
    '183' => 'vc',
    '184' => 'ws',
    '185' => 'sm',
    '186' => 'st',
    '187' => 'sa',
    '188' => 'sn',
    '189' => 'rs',
    '190' => 'sc',
    '191' => 'sl',
    '192' => 'sg',
    '193' => 'sk',
    '194' => 'si',
    '195' => 'sb',
    '196' => 'so',
    '197' => 'za',
    '198' => 'gs',
    '199' => 'es',
    '200' => 'lk',
    '201' => 'sh',
    '202' => 'pm',
    '203' => 'sd',
    '204' => 'sr',
    '205' => 'sj',
    '206' => 'sz',
    '207' => 'se',
    '208' => 'ch',
    '209' => 'sy',
    '210' => 'tw',
    '211' => 'tj',
    '212' => 'tz',
    '213' => 'th',
    '214' => 'tg',
    '215' => 'tk',
    '216' => 'to',
    '217' => 'tt',
    '218' => 'tn',
    '219' => 'tr',
    '220' => 'tm',
    '221' => 'tc',
    '222' => 'tv',
    '223' => 'ug',
    '224' => 'ua',
    '225' => 'ae',
    '226' => 'gb',
    '227' => 'um',
    '228' => 'uy',
    '229' => 'uz',
    '230' => 'vu',
    '231' => 'va',
    '232' => 've',
    '233' => 'vn',
    '238' => 'ye',
    '239' => 'rs',
    '240' => 'zm',
    '242' => 'zw'
);

$cl['language_codes'] = array (
  'afrikaans' => array (
    'name' => 'Afrikaans',
    'code' => 'af',
  ),
  'albanian' => array (
    'name' => 'Albanian - shqip',
    'code' => 'sq',
  ),
  'amharic' => array (
    'name' => 'Amharic - አማርኛ',
    'code' => 'am',
  ),
  'aragonese' => array (
    'name' => 'Aragonese - aragonés',
    'code' => 'an',
  ),
  'armenian' => array (
    'name' => 'Armenian - հայերեն',
    'code' => 'hy',
  ),
  'asturian' => array (
    'name' => 'Asturian - asturianu',
    'code' => 'ast',
  ),
  'azerbaijani' => array (
    'name' => 'Azerbaijani - azərbaycan dili',
    'code' => 'az',
  ),
  'basque' => array (
    'name' => 'Basque - euskara',
    'code' => 'eu',
  ),
  'belarusian' => array (
    'name' => 'Belarusian - беларуская',
    'code' => 'be',
  ),
  'bengali' => array (
    'name' => 'Bengali - বাংলা',
    'code' => 'bn',
  ),
  'bosnian' => array (
    'name' => 'Bosnian - bosanski',
    'code' => 'bs',
  ),
  'breton' => array (
    'name' => 'Breton - brezhoneg',
    'code' => 'br',
  ),
  'bulgarian' => array (
    'name' => 'Bulgarian - български',
    'code' => 'bg',
  ),
  'catalan' => array (
    'name' => 'Catalan - català',
    'code' => 'ca',
  ),
  'central_kurdish' => array (
    'name' => 'Central Kurdish - کوردی (دەستنوسی عەرەبی)',
    'code' => 'ckb',
  ),
  'chinese' => array (
    'name' => 'Chinese - 中文',
    'code' => 'zh',
  ),
  'corsican' => array (
    'name' => 'Corsican',
    'code' => 'co',
  ),
  'croatian' => array (
    'name' => 'Croatian - hrvatski',
    'code' => 'hr',
  ),
  'czech' => array (
    'name' => 'Czech - čeština',
    'code' => 'cs',
  ),
  'danish' => array (
    'name' => 'Danish - dansk',
    'code' => 'da',
  ),
  'esperanto' => array (
    'name' => 'Esperanto - esperanto',
    'code' => 'eo',
  ),
  'estonian' => array (
    'name' => 'Estonian - eesti',
    'code' => 'et',
  ),
  'faroese' => array (
    'name' => 'Faroese - føroyskt',
    'code' => 'fo',
  ),
  'filipino' => array (
    'name' => 'Filipino',
    'code' => 'fil',
  ),
  'finnish' => array (
    'name' => 'Finnish - suomi',
    'code' => 'fi',
  ),
  'galician' => array (
    'name' => 'Galician - galego',
    'code' => 'gl',
  ),
  'georgian' => array (
    'name' => 'Georgian - ქართული',
    'code' => 'ka',
  ),
  'greek' => array (
    'name' => 'Greek - Ελληνικά',
    'code' => 'el',
  ),
  'guarani' => array (
    'name' => 'Guarani',
    'code' => 'gn',
  ),
  'gujarati' => array (
    'name' => 'Gujarati - ગુજરાતી',
    'code' => 'gu',
  ),
  'hausa' => array (
    'name' => 'Hausa',
    'code' => 'ha',
  ),
  'hawaiian' => array (
    'name' => 'Hawaiian - ʻŌlelo Hawaiʻi',
    'code' => 'haw',
  ),
  'hebrew' => array (
    'name' => 'Hebrew - עברית',
    'code' => 'he',
  ),
  'hindi' => array (
    'name' => 'Hindi - हिन्दी',
    'code' => 'hi',
  ),
  'hungarian' => array (
    'name' => 'Hungarian - magyar',
    'code' => 'hu',
  ),
  'icelandic' => array (
    'name' => 'Icelandic - íslenska',
    'code' => 'is',
  ),
  'indonesian' => array (
    'name' => 'Indonesian - Indonesia',
    'code' => 'id',
  ),
  'interlingua' => array (
    'name' => 'Interlingua',
    'code' => 'ia',
  ),
  'irish' => array (
    'name' => 'Irish - Gaeilge',
    'code' => 'ga',
  ),
  'japanese' => array (
    'name' => 'Japanese - 日本語',
    'code' => 'ja',
  ),
  'kannada' => array (
    'name' => 'Kannada - ಕನ್ನಡ',
    'code' => 'kn',
  ),
  'kazakh' => array (
    'name' => 'Kazakh - қазақ тілі',
    'code' => 'kk',
  ),
  'khmer' => array (
    'name' => 'Khmer - ខ្មែរ',
    'code' => 'km',
  ),
  'korean' => array (
    'name' => 'Korean - 한국어',
    'code' => 'ko',
  ),
  'kurdish' => array (
    'name' => 'Kurdish - Kurdî',
    'code' => 'ku',
  ),
  'kyrgyz' => array (
    'name' => 'Kyrgyz - кыргызча',
    'code' => 'ky',
  ),
  'lao' => array (
    'name' => 'Lao - ລາວ',
    'code' => 'lo',
  ),
  'latin' => array (
    'name' => 'Latin',
    'code' => 'la',
  ),
  'latvian' => array (
    'name' => 'Latvian - latviešu',
    'code' => 'lv',
  ),
  'lingala' => array (
    'name' => 'Lingala - lingála',
    'code' => 'ln',
  ),
  'lithuanian' => array (
    'name' => 'Lithuanian - lietuvių',
    'code' => 'lt',
  ),
  'macedonian' => array (
    'name' => 'Macedonian - македонски',
    'code' => 'mk',
  ),
  'malay' => array (
    'name' => 'Malay - Bahasa Melayu',
    'code' => 'ms',
  ),
  'malayalam' => array (
    'name' => 'Malayalam - മലയാളം',
    'code' => 'ml',
  ),
  'maltese' => array (
    'name' => 'Maltese - Malti',
    'code' => 'mt',
  ),
  'marathi' => array (
    'name' => 'Marathi - मराठी',
    'code' => 'mr',
  ),
  'mongolian' => array (
    'name' => 'Mongolian - монгол',
    'code' => 'mn',
  ),
  'nepali' => array (
    'name' => 'Nepali - नेपाली',
    'code' => 'ne',
  ),
  'norwegian' => array (
    'name' => 'Norwegian',
    'code' => 'no',
  ),
  'occitan' => array (
    'name' => 'Occitan',
    'code' => 'oc',
  ),
  'oriya' => array (
    'name' => 'Oriya - ଓଡ଼ିଆ',
    'code' => 'or',
  ),
  'oromo' => array (
    'name' => 'Oromo - Oromoo',
    'code' => 'om',
  ),
  'pashto' => array (
    'name' => 'Pashto - پښتو',
    'code' => 'ps',
  ),
  'persian' => array (
    'name' => 'Persian - فارسی',
    'code' => 'fa',
  ),
  'polish' => array (
    'name' => 'Polish - polski',
    'code' => 'pl',
  ),
  'punjabi' => array (
    'name' => 'Punjabi - ਪੰਜਾਬੀ',
    'code' => 'pa',
  ),
  'quechua' => array (
    'name' => 'Quechua',
    'code' => 'qu',
  ),
  'romanian' => array (
    'name' => 'Romanian - română',
    'code' => 'ro',
  ),
  'romansh' => array (
    'name' => 'Romansh - rumantsch',
    'code' => 'rm',
  ),
  'scottish_gaelic' => array (
    'name' => 'Scottish Gaelic',
    'code' => 'gd',
  ),
  'serbian' => array (
    'name' => 'Serbian - српски',
    'code' => 'sr',
  ),
  'serbo' => array (
    'name' => 'Serbo - Croatian',
    'code' => 'sh',
  ),
  'shona' => array (
    'name' => 'Shona - chiShona',
    'code' => 'sn',
  ),
  'sindhi' => array (
    'name' => 'Sindhi',
    'code' => 'sd',
  ),
  'sinhala' => array (
    'name' => 'Sinhala - සිංහල',
    'code' => 'si',
  ),
  'slovak' => array (
    'name' => 'Slovak - slovenčina',
    'code' => 'sk',
  ),
  'slovenian' => array (
    'name' => 'Slovenian - slovenščina',
    'code' => 'sl',
  ),
  'somali' => array (
    'name' => 'Somali - Soomaali',
    'code' => 'so',
  ),
  'southern_sotho' => array (
    'name' => 'Southern Sotho',
    'code' => 'st',
  ),
  'sundanese' => array (
    'name' => 'Sundanese',
    'code' => 'su',
  ),
  'swahili' => array (
    'name' => 'Swahili - Kiswahili',
    'code' => 'sw',
  ),
  'swedish' => array (
    'name' => 'Swedish - svenska',
    'code' => 'sv',
  ),
  'tajik' => array (
    'name' => 'Tajik - тоҷикӣ',
    'code' => 'tg',
  ),
  'tamil' => array (
    'name' => 'Tamil - தமிழ்',
    'code' => 'ta',
  ),
  'tatar' => array (
    'name' => 'Tatar',
    'code' => 'tt',
  ),
  'telugu' => array (
    'name' => 'Telugu - తెలుగు',
    'code' => 'te',
  ),
  'thai' => array (
    'name' => 'Thai - ไทย',
    'code' => 'th',
  ),
  'tigrinya' => array (
    'name' => 'Tigrinya - ትግርኛ',
    'code' => 'ti',
  ),
  'tongan' => array (
    'name' => 'Tongan - lea fakatonga',
    'code' => 'to',
  ),
  'turkmen' => array (
    'name' => 'Turkmen',
    'code' => 'tk',
  ),
  'twi' => array (
    'name' => 'Twi',
    'code' => 'tw',
  ),
  'urdu' => array (
    'name' => 'Urdu - اردو',
    'code' => 'ur',
  ),
  'uyghur' => array (
    'name' => 'Uyghur',
    'code' => 'ug',
  ),
  'uzbek' => array (
    'name' => 'Uzbek - o‘zbek',
    'code' => 'uz',
  ),
  'vietnamese' => array (
    'name' => 'Vietnamese - Tiếng Việt',
    'code' => 'vi',
  ),
  'walloon' => array (
    'name' => 'Walloon - wa',
    'code' => 'wa',
  ),
  'welsh' => array (
    'name' => 'Welsh - Cymraeg',
    'code' => 'cy',
  ),
  'western_frisian' => array (
    'name' => 'Western Frisian',
    'code' => 'fy',
  ),
  'xhosa' => array (
    'name' => 'Xhosa',
    'code' => 'xh',
  ),
  'yiddish' => array (
    'name' => 'Yiddish',
    'code' => 'yi',
  ),
  'yoruba' => array (
    'name' => 'Yoruba - Èdè Yorùbá',
    'code' => 'yo',
  ),
  'zulu' => array (
    'name' => 'Zulu - isiZulu',
    'code' => 'zu',
  )
);

$cl['timezones'] = array(
    'UTC' => 'UTC — Coordinated Universal Time',
    'America/Adak' => '(GMT-10:00) America/Adak (Hawaii-Aleutian Standard Time)',
    'America/Atka' => '(GMT-10:00) America/Atka (Hawaii-Aleutian Standard Time)',
    'America/Anchorage' => '(GMT-9:00) America/Anchorage (Alaska Standard Time)',
    'America/Juneau' => '(GMT-9:00) America/Juneau (Alaska Standard Time)',
    'America/Nome' => '(GMT-9:00) America/Nome (Alaska Standard Time)',
    'America/Yakutat' => '(GMT-9:00) America/Yakutat (Alaska Standard Time)',
    'America/Dawson' => '(GMT-8:00) America/Dawson (Pacific Standard Time)',
    'America/Ensenada' => '(GMT-8:00) America/Ensenada (Pacific Standard Time)',
    'America/Los_Angeles' => '(GMT-8:00) America/Los_Angeles (Pacific Standard Time)',
    'America/Tijuana' => '(GMT-8:00) America/Tijuana (Pacific Standard Time)',
    'America/Vancouver' => '(GMT-8:00) America/Vancouver (Pacific Standard Time)',
    'America/Whitehorse' => '(GMT-8:00) America/Whitehorse (Pacific Standard Time)',
    'Canada/Pacific' => '(GMT-8:00) Canada/Pacific (Pacific Standard Time)',
    'Canada/Yukon' => '(GMT-8:00) Canada/Yukon (Pacific Standard Time)',
    'Mexico/BajaNorte' => '(GMT-8:00) Mexico/BajaNorte (Pacific Standard Time)',
    'America/Boise' => '(GMT-7:00) America/Boise (Mountain Standard Time)',
    'America/Cambridge_Bay' => '(GMT-7:00) America/Cambridge_Bay (Mountain Standard Time)',
    'America/Chihuahua' => '(GMT-7:00) America/Chihuahua (Mountain Standard Time)',
    'America/Dawson_Creek' => '(GMT-7:00) America/Dawson_Creek (Mountain Standard Time)',
    'America/Denver' => '(GMT-7:00) America/Denver (Mountain Standard Time)',
    'America/Edmonton' => '(GMT-7:00) America/Edmonton (Mountain Standard Time)',
    'America/Hermosillo' => '(GMT-7:00) America/Hermosillo (Mountain Standard Time)',
    'America/Inuvik' => '(GMT-7:00) America/Inuvik (Mountain Standard Time)',
    'America/Mazatlan' => '(GMT-7:00) America/Mazatlan (Mountain Standard Time)',
    'America/Phoenix' => '(GMT-7:00) America/Phoenix (Mountain Standard Time)',
    'America/Shiprock' => '(GMT-7:00) America/Shiprock (Mountain Standard Time)',
    'America/Yellowknife' => '(GMT-7:00) America/Yellowknife (Mountain Standard Time)',
    'Canada/Mountain' => '(GMT-7:00) Canada/Mountain (Mountain Standard Time)',
    'Mexico/BajaSur' => '(GMT-7:00) Mexico/BajaSur (Mountain Standard Time)',
    'America/Belize' => '(GMT-6:00) America/Belize (Central Standard Time)',
    'America/Cancun' => '(GMT-6:00) America/Cancun (Central Standard Time)',
    'America/Chicago' => '(GMT-6:00) America/Chicago (Central Standard Time)',
    'America/Costa_Rica' => '(GMT-6:00) America/Costa_Rica (Central Standard Time)',
    'America/El_Salvador' => '(GMT-6:00) America/El_Salvador (Central Standard Time)',
    'America/Guatemala' => '(GMT-6:00) America/Guatemala (Central Standard Time)',
    'America/Knox_IN' => '(GMT-6:00) America/Knox_IN (Central Standard Time)',
    'America/Managua' => '(GMT-6:00) America/Managua (Central Standard Time)',
    'America/Menominee' => '(GMT-6:00) America/Menominee (Central Standard Time)',
    'America/Merida' => '(GMT-6:00) America/Merida (Central Standard Time)',
    'America/Mexico_City' => '(GMT-6:00) America/Mexico_City (Central Standard Time)',
    'America/Monterrey' => '(GMT-6:00) America/Monterrey (Central Standard Time)',
    'America/Rainy_River' => '(GMT-6:00) America/Rainy_River (Central Standard Time)',
    'America/Rankin_Inlet' => '(GMT-6:00) America/Rankin_Inlet (Central Standard Time)',
    'America/Regina' => '(GMT-6:00) America/Regina (Central Standard Time)',
    'America/Swift_Current' => '(GMT-6:00) America/Swift_Current (Central Standard Time)',
    'America/Tegucigalpa' => '(GMT-6:00) America/Tegucigalpa (Central Standard Time)',
    'America/Winnipeg' => '(GMT-6:00) America/Winnipeg (Central Standard Time)',
    'Canada/Central' => '(GMT-6:00) Canada/Central (Central Standard Time)',
    'Canada/East-Saskatchewan' => '(GMT-6:00) Canada/East-Saskatchewan (Central Standard Time)',
    'Canada/Saskatchewan' => '(GMT-6:00) Canada/Saskatchewan (Central Standard Time)',
    'Chile/EasterIsland' => '(GMT-6:00) Chile/EasterIsland (Easter Is. Time)',
    'Mexico/General' => '(GMT-6:00) Mexico/General (Central Standard Time)',
    'America/Atikokan' => '(GMT-5:00) America/Atikokan (Eastern Standard Time)',
    'America/Bogota' => '(GMT-5:00) America/Bogota (Colombia Time)',
    'America/Cayman' => '(GMT-5:00) America/Cayman (Eastern Standard Time)',
    'America/Coral_Harbour' => '(GMT-5:00) America/Coral_Harbour (Eastern Standard Time)',
    'America/Detroit' => '(GMT-5:00) America/Detroit (Eastern Standard Time)',
    'America/Fort_Wayne' => '(GMT-5:00) America/Fort_Wayne (Eastern Standard Time)',
    'America/Grand_Turk' => '(GMT-5:00) America/Grand_Turk (Eastern Standard Time)',
    'America/Guayaquil' => '(GMT-5:00) America/Guayaquil (Ecuador Time)',
    'America/Havana' => '(GMT-5:00) America/Havana (Cuba Standard Time)',
    'America/Indianapolis' => '(GMT-5:00) America/Indianapolis (Eastern Standard Time)',
    'America/Iqaluit' => '(GMT-5:00) America/Iqaluit (Eastern Standard Time)',
    'America/Jamaica' => '(GMT-5:00) America/Jamaica (Eastern Standard Time)',
    'America/Lima' => '(GMT-5:00) America/Lima (Peru Time)',
    'America/Louisville' => '(GMT-5:00) America/Louisville (Eastern Standard Time)',
    'America/Montreal' => '(GMT-5:00) America/Montreal (Eastern Standard Time)',
    'America/Nassau' => '(GMT-5:00) America/Nassau (Eastern Standard Time)',
    'America/New_York' => '(GMT-5:00) America/New_York (Eastern Standard Time)',
    'America/Nipigon' => '(GMT-5:00) America/Nipigon (Eastern Standard Time)',
    'America/Panama' => '(GMT-5:00) America/Panama (Eastern Standard Time)',
    'America/Pangnirtung' => '(GMT-5:00) America/Pangnirtung (Eastern Standard Time)',
    'America/Port-au-Prince' => '(GMT-5:00) America/Port-au-Prince (Eastern Standard Time)',
    'America/Resolute' => '(GMT-5:00) America/Resolute (Eastern Standard Time)',
    'America/Thunder_Bay' => '(GMT-5:00) America/Thunder_Bay (Eastern Standard Time)',
    'America/Toronto' => '(GMT-5:00) America/Toronto (Eastern Standard Time)',
    'Canada/Eastern' => '(GMT-5:00) Canada/Eastern (Eastern Standard Time)',
    'America/Caracas' => '(GMT-4:-30) America/Caracas (Venezuela Time)',
    'America/Anguilla' => '(GMT-4:00) America/Anguilla (Atlantic Standard Time)',
    'America/Antigua' => '(GMT-4:00) America/Antigua (Atlantic Standard Time)',
    'America/Aruba' => '(GMT-4:00) America/Aruba (Atlantic Standard Time)',
    'America/Asuncion' => '(GMT-4:00) America/Asuncion (Paraguay Time)',
    'America/Barbados' => '(GMT-4:00) America/Barbados (Atlantic Standard Time)',
    'America/Blanc-Sablon' => '(GMT-4:00) America/Blanc-Sablon (Atlantic Standard Time)',
    'America/Boa_Vista' => '(GMT-4:00) America/Boa_Vista (Amazon Time)',
    'America/Campo_Grande' => '(GMT-4:00) America/Campo_Grande (Amazon Time)',
    'America/Cuiaba' => '(GMT-4:00) America/Cuiaba (Amazon Time)',
    'America/Curacao' => '(GMT-4:00) America/Curacao (Atlantic Standard Time)',
    'America/Dominica' => '(GMT-4:00) America/Dominica (Atlantic Standard Time)',
    'America/Eirunepe' => '(GMT-4:00) America/Eirunepe (Amazon Time)',
    'America/Glace_Bay' => '(GMT-4:00) America/Glace_Bay (Atlantic Standard Time)',
    'America/Goose_Bay' => '(GMT-4:00) America/Goose_Bay (Atlantic Standard Time)',
    'America/Grenada' => '(GMT-4:00) America/Grenada (Atlantic Standard Time)',
    'America/Guadeloupe' => '(GMT-4:00) America/Guadeloupe (Atlantic Standard Time)',
    'America/Guyana' => '(GMT-4:00) America/Guyana (Guyana Time)',
    'America/Halifax' => '(GMT-4:00) America/Halifax (Atlantic Standard Time)',
    'America/La_Paz' => '(GMT-4:00) America/La_Paz (Bolivia Time)',
    'America/Manaus' => '(GMT-4:00) America/Manaus (Amazon Time)',
    'America/Marigot' => '(GMT-4:00) America/Marigot (Atlantic Standard Time)',
    'America/Martinique' => '(GMT-4:00) America/Martinique (Atlantic Standard Time)',
    'America/Moncton' => '(GMT-4:00) America/Moncton (Atlantic Standard Time)',
    'America/Montserrat' => '(GMT-4:00) America/Montserrat (Atlantic Standard Time)',
    'America/Port_of_Spain' => '(GMT-4:00) America/Port_of_Spain (Atlantic Standard Time)',
    'America/Porto_Acre' => '(GMT-4:00) America/Porto_Acre (Amazon Time)',
    'America/Porto_Velho' => '(GMT-4:00) America/Porto_Velho (Amazon Time)',
    'America/Puerto_Rico' => '(GMT-4:00) America/Puerto_Rico (Atlantic Standard Time)',
    'America/Rio_Branco' => '(GMT-4:00) America/Rio_Branco (Amazon Time)',
    'America/Santiago' => '(GMT-4:00) America/Santiago (Chile Time)',
    'America/Santo_Domingo' => '(GMT-4:00) America/Santo_Domingo (Atlantic Standard Time)',
    'America/St_Barthelemy' => '(GMT-4:00) America/St_Barthelemy (Atlantic Standard Time)',
    'America/St_Kitts' => '(GMT-4:00) America/St_Kitts (Atlantic Standard Time)',
    'America/St_Lucia' => '(GMT-4:00) America/St_Lucia (Atlantic Standard Time)',
    'America/St_Thomas' => '(GMT-4:00) America/St_Thomas (Atlantic Standard Time)',
    'America/St_Vincent' => '(GMT-4:00) America/St_Vincent (Atlantic Standard Time)',
    'America/Thule' => '(GMT-4:00) America/Thule (Atlantic Standard Time)',
    'America/Tortola' => '(GMT-4:00) America/Tortola (Atlantic Standard Time)',
    'America/Virgin' => '(GMT-4:00) America/Virgin (Atlantic Standard Time)',
    'Antarctica/Palmer' => '(GMT-4:00) Antarctica/Palmer (Chile Time)',
    'Atlantic/Bermuda' => '(GMT-4:00) Atlantic/Bermuda (Atlantic Standard Time)',
    'Atlantic/Stanley' => '(GMT-4:00) Atlantic/Stanley (Falkland Is. Time)',
    'Brazil/Acre' => '(GMT-4:00) Brazil/Acre (Amazon Time)',
    'Brazil/West' => '(GMT-4:00) Brazil/West (Amazon Time)',
    'Canada/Atlantic' => '(GMT-4:00) Canada/Atlantic (Atlantic Standard Time)',
    'Chile/Continental' => '(GMT-4:00) Chile/Continental (Chile Time)',
    'America/St_Johns' => '(GMT-3:-30) America/St_Johns (Newfoundland Standard Time)',
    'Canada/Newfoundland' => '(GMT-3:-30) Canada/Newfoundland (Newfoundland Standard Time)',
    'America/Araguaina' => '(GMT-3:00) America/Araguaina (Brasilia Time)',
    'America/Bahia' => '(GMT-3:00) America/Bahia (Brasilia Time)',
    'America/Belem' => '(GMT-3:00) America/Belem (Brasilia Time)',
    'America/Buenos_Aires' => '(GMT-3:00) America/Buenos_Aires (Argentine Time)',
    'America/Catamarca' => '(GMT-3:00) America/Catamarca (Argentine Time)',
    'America/Cayenne' => '(GMT-3:00) America/Cayenne (French Guiana Time)',
    'America/Cordoba' => '(GMT-3:00) America/Cordoba (Argentine Time)',
    'America/Fortaleza' => '(GMT-3:00) America/Fortaleza (Brasilia Time)',
    'America/Godthab' => '(GMT-3:00) America/Godthab (Western Greenland Time)',
    'America/Jujuy' => '(GMT-3:00) America/Jujuy (Argentine Time)',
    'America/Maceio' => '(GMT-3:00) America/Maceio (Brasilia Time)',
    'America/Mendoza' => '(GMT-3:00) America/Mendoza (Argentine Time)',
    'America/Miquelon' => '(GMT-3:00) America/Miquelon (Pierre & Miquelon Standard Time)',
    'America/Montevideo' => '(GMT-3:00) America/Montevideo (Uruguay Time)',
    'America/Paramaribo' => '(GMT-3:00) America/Paramaribo (Suriname Time)',
    'America/Recife' => '(GMT-3:00) America/Recife (Brasilia Time)',
    'America/Rosario' => '(GMT-3:00) America/Rosario (Argentine Time)',
    'America/Santarem' => '(GMT-3:00) America/Santarem (Brasilia Time)',
    'America/Sao_Paulo' => '(GMT-3:00) America/Sao_Paulo (Brasilia Time)',
    'Antarctica/Rothera' => '(GMT-3:00) Antarctica/Rothera (Rothera Time)',
    'Brazil/East' => '(GMT-3:00) Brazil/East (Brasilia Time)',
    'America/Noronha' => '(GMT-2:00) America/Noronha (Fernando de Noronha Time)',
    'Atlantic/South_Georgia' => '(GMT-2:00) Atlantic/South_Georgia (South Georgia Standard Time)',
    'Brazil/DeNoronha' => '(GMT-2:00) Brazil/DeNoronha (Fernando de Noronha Time)',
    'America/Scoresbysund' => '(GMT-1:00) America/Scoresbysund (Eastern Greenland Time)',
    'Atlantic/Azores' => '(GMT-1:00) Atlantic/Azores (Azores Time)',
    'Atlantic/Cape_Verde' => '(GMT-1:00) Atlantic/Cape_Verde (Cape Verde Time)',
    'Africa/Abidjan' => '(GMT+0:00) Africa/Abidjan (Greenwich Mean Time)',
    'Africa/Accra' => '(GMT+0:00) Africa/Accra (Ghana Mean Time)',
    'Africa/Bamako' => '(GMT+0:00) Africa/Bamako (Greenwich Mean Time)',
    'Africa/Banjul' => '(GMT+0:00) Africa/Banjul (Greenwich Mean Time)',
    'Africa/Bissau' => '(GMT+0:00) Africa/Bissau (Greenwich Mean Time)',
    'Africa/Casablanca' => '(GMT+0:00) Africa/Casablanca (Western European Time)',
    'Africa/Conakry' => '(GMT+0:00) Africa/Conakry (Greenwich Mean Time)',
    'Africa/Dakar' => '(GMT+0:00) Africa/Dakar (Greenwich Mean Time)',
    'Africa/El_Aaiun' => '(GMT+0:00) Africa/El_Aaiun (Western European Time)',
    'Africa/Freetown' => '(GMT+0:00) Africa/Freetown (Greenwich Mean Time)',
    'Africa/Lome' => '(GMT+0:00) Africa/Lome (Greenwich Mean Time)',
    'Africa/Monrovia' => '(GMT+0:00) Africa/Monrovia (Greenwich Mean Time)',
    'Africa/Nouakchott' => '(GMT+0:00) Africa/Nouakchott (Greenwich Mean Time)',
    'Africa/Ouagadougou' => '(GMT+0:00) Africa/Ouagadougou (Greenwich Mean Time)',
    'Africa/Sao_Tome' => '(GMT+0:00) Africa/Sao_Tome (Greenwich Mean Time)',
    'Africa/Timbuktu' => '(GMT+0:00) Africa/Timbuktu (Greenwich Mean Time)',
    'America/Danmarkshavn' => '(GMT+0:00) America/Danmarkshavn (Greenwich Mean Time)',
    'Atlantic/Canary' => '(GMT+0:00) Atlantic/Canary (Western European Time)',
    'Atlantic/Faeroe' => '(GMT+0:00) Atlantic/Faeroe (Western European Time)',
    'Atlantic/Faroe' => '(GMT+0:00) Atlantic/Faroe (Western European Time)',
    'Atlantic/Madeira' => '(GMT+0:00) Atlantic/Madeira (Western European Time)',
    'Atlantic/Reykjavik' => '(GMT+0:00) Atlantic/Reykjavik (Greenwich Mean Time)',
    'Atlantic/St_Helena' => '(GMT+0:00) Atlantic/St_Helena (Greenwich Mean Time)',
    'Europe/Belfast' => '(GMT+0:00) Europe/Belfast (Greenwich Mean Time)',
    'Europe/Dublin' => '(GMT+0:00) Europe/Dublin (Greenwich Mean Time)',
    'Europe/Guernsey' => '(GMT+0:00) Europe/Guernsey (Greenwich Mean Time)',
    'Europe/Isle_of_Man' => '(GMT+0:00) Europe/Isle_of_Man (Greenwich Mean Time)',
    'Europe/Jersey' => '(GMT+0:00) Europe/Jersey (Greenwich Mean Time)',
    'Europe/Lisbon' => '(GMT+0:00) Europe/Lisbon (Western European Time)',
    'Europe/London' => '(GMT+0:00) Europe/London (Greenwich Mean Time)',
    'Africa/Algiers' => '(GMT+1:00) Africa/Algiers (Central European Time)',
    'Africa/Bangui' => '(GMT+1:00) Africa/Bangui (Western African Time)',
    'Africa/Brazzaville' => '(GMT+1:00) Africa/Brazzaville (Western African Time)',
    'Africa/Ceuta' => '(GMT+1:00) Africa/Ceuta (Central European Time)',
    'Africa/Douala' => '(GMT+1:00) Africa/Douala (Western African Time)',
    'Africa/Kinshasa' => '(GMT+1:00) Africa/Kinshasa (Western African Time)',
    'Africa/Lagos' => '(GMT+1:00) Africa/Lagos (Western African Time)',
    'Africa/Libreville' => '(GMT+1:00) Africa/Libreville (Western African Time)',
    'Africa/Luanda' => '(GMT+1:00) Africa/Luanda (Western African Time)',
    'Africa/Malabo' => '(GMT+1:00) Africa/Malabo (Western African Time)',
    'Africa/Ndjamena' => '(GMT+1:00) Africa/Ndjamena (Western African Time)',
    'Africa/Niamey' => '(GMT+1:00) Africa/Niamey (Western African Time)',
    'Africa/Porto-Novo' => '(GMT+1:00) Africa/Porto-Novo (Western African Time)',
    'Africa/Tunis' => '(GMT+1:00) Africa/Tunis (Central European Time)',
    'Africa/Windhoek' => '(GMT+1:00) Africa/Windhoek (Western African Time)',
    'Arctic/Longyearbyen' => '(GMT+1:00) Arctic/Longyearbyen (Central European Time)',
    'Atlantic/Jan_Mayen' => '(GMT+1:00) Atlantic/Jan_Mayen (Central European Time)',
    'Europe/Amsterdam' => '(GMT+1:00) Europe/Amsterdam (Central European Time)',
    'Europe/Andorra' => '(GMT+1:00) Europe/Andorra (Central European Time)',
    'Europe/Belgrade' => '(GMT+1:00) Europe/Belgrade (Central European Time)',
    'Europe/Berlin' => '(GMT+1:00) Europe/Berlin (Central European Time)',
    'Europe/Bratislava' => '(GMT+1:00) Europe/Bratislava (Central European Time)',
    'Europe/Brussels' => '(GMT+1:00) Europe/Brussels (Central European Time)',
    'Europe/Budapest' => '(GMT+1:00) Europe/Budapest (Central European Time)',
    'Europe/Copenhagen' => '(GMT+1:00) Europe/Copenhagen (Central European Time)',
    'Europe/Gibraltar' => '(GMT+1:00) Europe/Gibraltar (Central European Time)',
    'Europe/Ljubljana' => '(GMT+1:00) Europe/Ljubljana (Central European Time)',
    'Europe/Luxembourg' => '(GMT+1:00) Europe/Luxembourg (Central European Time)',
    'Europe/Madrid' => '(GMT+1:00) Europe/Madrid (Central European Time)',
    'Europe/Malta' => '(GMT+1:00) Europe/Malta (Central European Time)',
    'Europe/Monaco' => '(GMT+1:00) Europe/Monaco (Central European Time)',
    'Europe/Oslo' => '(GMT+1:00) Europe/Oslo (Central European Time)',
    'Europe/Paris' => '(GMT+1:00) Europe/Paris (Central European Time)',
    'Europe/Podgorica' => '(GMT+1:00) Europe/Podgorica (Central European Time)',
    'Europe/Prague' => '(GMT+1:00) Europe/Prague (Central European Time)',
    'Europe/Rome' => '(GMT+1:00) Europe/Rome (Central European Time)',
    'Europe/San_Marino' => '(GMT+1:00) Europe/San_Marino (Central European Time)',
    'Europe/Sarajevo' => '(GMT+1:00) Europe/Sarajevo (Central European Time)',
    'Europe/Skopje' => '(GMT+1:00) Europe/Skopje (Central European Time)',
    'Europe/Stockholm' => '(GMT+1:00) Europe/Stockholm (Central European Time)',
    'Europe/Tirane' => '(GMT+1:00) Europe/Tirane (Central European Time)',
    'Europe/Vaduz' => '(GMT+1:00) Europe/Vaduz (Central European Time)',
    'Europe/Vatican' => '(GMT+1:00) Europe/Vatican (Central European Time)',
    'Europe/Vienna' => '(GMT+1:00) Europe/Vienna (Central European Time)',
    'Europe/Warsaw' => '(GMT+1:00) Europe/Warsaw (Central European Time)',
    'Europe/Zagreb' => '(GMT+1:00) Europe/Zagreb (Central European Time)',
    'Europe/Zurich' => '(GMT+1:00) Europe/Zurich (Central European Time)',
    'Africa/Blantyre' => '(GMT+2:00) Africa/Blantyre (Central African Time)',
    'Africa/Bujumbura' => '(GMT+2:00) Africa/Bujumbura (Central African Time)',
    'Africa/Cairo' => '(GMT+2:00) Africa/Cairo (Eastern European Time)',
    'Africa/Gaborone' => '(GMT+2:00) Africa/Gaborone (Central African Time)',
    'Africa/Harare' => '(GMT+2:00) Africa/Harare (Central African Time)',
    'Africa/Johannesburg' => '(GMT+2:00) Africa/Johannesburg (South Africa Standard Time)',
    'Africa/Kigali' => '(GMT+2:00) Africa/Kigali (Central African Time)',
    'Africa/Lubumbashi' => '(GMT+2:00) Africa/Lubumbashi (Central African Time)',
    'Africa/Lusaka' => '(GMT+2:00) Africa/Lusaka (Central African Time)',
    'Africa/Maputo' => '(GMT+2:00) Africa/Maputo (Central African Time)',
    'Africa/Maseru' => '(GMT+2:00) Africa/Maseru (South Africa Standard Time)',
    'Africa/Mbabane' => '(GMT+2:00) Africa/Mbabane (South Africa Standard Time)',
    'Africa/Tripoli' => '(GMT+2:00) Africa/Tripoli (Eastern European Time)',
    'Asia/Amman' => '(GMT+2:00) Asia/Amman (Eastern European Time)',
    'Asia/Beirut' => '(GMT+2:00) Asia/Beirut (Eastern European Time)',
    'Asia/Damascus' => '(GMT+2:00) Asia/Damascus (Eastern European Time)',
    'Asia/Gaza' => '(GMT+2:00) Asia/Gaza (Eastern European Time)',
    'Asia/Istanbul' => '(GMT+2:00) Asia/Istanbul (Eastern European Time)',
    'Asia/Jerusalem' => '(GMT+2:00) Asia/Jerusalem (Israel Standard Time)',
    'Asia/Nicosia' => '(GMT+2:00) Asia/Nicosia (Eastern European Time)',
    'Asia/Tel_Aviv' => '(GMT+2:00) Asia/Tel_Aviv (Israel Standard Time)',
    'Europe/Athens' => '(GMT+2:00) Europe/Athens (Eastern European Time)',
    'Europe/Bucharest' => '(GMT+2:00) Europe/Bucharest (Eastern European Time)',
    'Europe/Chisinau' => '(GMT+2:00) Europe/Chisinau (Eastern European Time)',
    'Europe/Helsinki' => '(GMT+2:00) Europe/Helsinki (Eastern European Time)',
    'Europe/Istanbul' => '(GMT+2:00) Europe/Istanbul (Eastern European Time)',
    'Europe/Kaliningrad' => '(GMT+2:00) Europe/Kaliningrad (Eastern European Time)',
    'Europe/Kiev' => '(GMT+2:00) Europe/Kiev (Eastern European Time)',
    'Europe/Mariehamn' => '(GMT+2:00) Europe/Mariehamn (Eastern European Time)',
    'Europe/Minsk' => '(GMT+2:00) Europe/Minsk (Eastern European Time)',
    'Europe/Nicosia' => '(GMT+2:00) Europe/Nicosia (Eastern European Time)',
    'Europe/Riga' => '(GMT+2:00) Europe/Riga (Eastern European Time)',
    'Europe/Simferopol' => '(GMT+2:00) Europe/Simferopol (Eastern European Time)',
    'Europe/Sofia' => '(GMT+2:00) Europe/Sofia (Eastern European Time)',
    'Europe/Tallinn' => '(GMT+2:00) Europe/Tallinn (Eastern European Time)',
    'Europe/Tiraspol' => '(GMT+2:00) Europe/Tiraspol (Eastern European Time)',
    'Europe/Uzhgorod' => '(GMT+2:00) Europe/Uzhgorod (Eastern European Time)',
    'Europe/Vilnius' => '(GMT+2:00) Europe/Vilnius (Eastern European Time)',
    'Europe/Zaporozhye' => '(GMT+2:00) Europe/Zaporozhye (Eastern European Time)',
    'Africa/Addis_Ababa' => '(GMT+3:00) Africa/Addis_Ababa (Eastern African Time)',
    'Africa/Asmara' => '(GMT+3:00) Africa/Asmara (Eastern African Time)',
    'Africa/Asmera' => '(GMT+3:00) Africa/Asmera (Eastern African Time)',
    'Africa/Dar_es_Salaam' => '(GMT+3:00) Africa/Dar_es_Salaam (Eastern African Time)',
    'Africa/Djibouti' => '(GMT+3:00) Africa/Djibouti (Eastern African Time)',
    'Africa/Kampala' => '(GMT+3:00) Africa/Kampala (Eastern African Time)',
    'Africa/Khartoum' => '(GMT+3:00) Africa/Khartoum (Eastern African Time)',
    'Africa/Mogadishu' => '(GMT+3:00) Africa/Mogadishu (Eastern African Time)',
    'Africa/Nairobi' => '(GMT+3:00) Africa/Nairobi (Eastern African Time)',
    'Antarctica/Syowa' => '(GMT+3:00) Antarctica/Syowa (Syowa Time)',
    'Asia/Aden' => '(GMT+3:00) Asia/Aden (Arabia Standard Time)',
    'Asia/Baghdad' => '(GMT+3:00) Asia/Baghdad (Arabia Standard Time)',
    'Asia/Bahrain' => '(GMT+3:00) Asia/Bahrain (Arabia Standard Time)',
    'Asia/Kuwait' => '(GMT+3:00) Asia/Kuwait (Arabia Standard Time)',
    'Asia/Qatar' => '(GMT+3:00) Asia/Qatar (Arabia Standard Time)',
    'Europe/Moscow' => '(GMT+3:00) Europe/Moscow (Moscow Standard Time)',
    'Europe/Volgograd' => '(GMT+3:00) Europe/Volgograd (Volgograd Time)',
    'Indian/Antananarivo' => '(GMT+3:00) Indian/Antananarivo (Eastern African Time)',
    'Indian/Comoro' => '(GMT+3:00) Indian/Comoro (Eastern African Time)',
    'Indian/Mayotte' => '(GMT+3:00) Indian/Mayotte (Eastern African Time)',
    'Asia/Tehran' => '(GMT+3:30) Asia/Tehran (Iran Standard Time)',
    'Asia/Baku' => '(GMT+4:00) Asia/Baku (Azerbaijan Time)',
    'Asia/Dubai' => '(GMT+4:00) Asia/Dubai (Gulf Standard Time)',
    'Asia/Muscat' => '(GMT+4:00) Asia/Muscat (Gulf Standard Time)',
    'Asia/Tbilisi' => '(GMT+4:00) Asia/Tbilisi (Georgia Time)',
    'Asia/Yerevan' => '(GMT+4:00) Asia/Yerevan (Armenia Time)',
    'Europe/Samara' => '(GMT+4:00) Europe/Samara (Samara Time)',
    'Indian/Mahe' => '(GMT+4:00) Indian/Mahe (Seychelles Time)',
    'Indian/Mauritius' => '(GMT+4:00) Indian/Mauritius (Mauritius Time)',
    'Indian/Reunion' => '(GMT+4:00) Indian/Reunion (Reunion Time)',
    'Asia/Kabul' => '(GMT+4:30) Asia/Kabul (Afghanistan Time)',
    'Asia/Aqtau' => '(GMT+5:00) Asia/Aqtau (Aqtau Time)',
    'Asia/Aqtobe' => '(GMT+5:00) Asia/Aqtobe (Aqtobe Time)',
    'Asia/Ashgabat' => '(GMT+5:00) Asia/Ashgabat (Turkmenistan Time)',
    'Asia/Ashkhabad' => '(GMT+5:00) Asia/Ashkhabad (Turkmenistan Time)',
    'Asia/Dushanbe' => '(GMT+5:00) Asia/Dushanbe (Tajikistan Time)',
    'Asia/Karachi' => '(GMT+5:00) Asia/Karachi (Pakistan Time)',
    'Asia/Oral' => '(GMT+5:00) Asia/Oral (Oral Time)',
    'Asia/Samarkand' => '(GMT+5:00) Asia/Samarkand (Uzbekistan Time)',
    'Asia/Tashkent' => '(GMT+5:00) Asia/Tashkent (Uzbekistan Time)',
    'Asia/Yekaterinburg' => '(GMT+5:00) Asia/Yekaterinburg (Yekaterinburg Time)',
    'Indian/Kerguelen' => '(GMT+5:00) Indian/Kerguelen (French Southern & Antarctic Lands Time)',
    'Indian/Maldives' => '(GMT+5:00) Indian/Maldives (Maldives Time)',
    'Asia/Calcutta' => '(GMT+5:30) Asia/Calcutta (India Standard Time)',
    'Asia/Colombo' => '(GMT+5:30) Asia/Colombo (India Standard Time)',
    'Asia/Kolkata' => '(GMT+5:30) Asia/Kolkata (India Standard Time)',
    'Asia/Katmandu' => '(GMT+5:45) Asia/Katmandu (Nepal Time)',
    'Antarctica/Mawson' => '(GMT+6:00) Antarctica/Mawson (Mawson Time)',
    'Antarctica/Vostok' => '(GMT+6:00) Antarctica/Vostok (Vostok Time)',
    'Asia/Almaty' => '(GMT+6:00) Asia/Almaty (Alma-Ata Time)',
    'Asia/Bishkek' => '(GMT+6:00) Asia/Bishkek (Kirgizstan Time)',
    'Asia/Dacca' => '(GMT+6:00) Asia/Dacca (Bangladesh Time)',
    'Asia/Dhaka' => '(GMT+6:00) Asia/Dhaka (Bangladesh Time)',
    'Asia/Novosibirsk' => '(GMT+6:00) Asia/Novosibirsk (Novosibirsk Time)',
    'Asia/Omsk' => '(GMT+6:00) Asia/Omsk (Omsk Time)',
    'Asia/Qyzylorda' => '(GMT+6:00) Asia/Qyzylorda (Qyzylorda Time)',
    'Asia/Thimbu' => '(GMT+6:00) Asia/Thimbu (Bhutan Time)',
    'Asia/Thimphu' => '(GMT+6:00) Asia/Thimphu (Bhutan Time)',
    'Indian/Chagos' => '(GMT+6:00) Indian/Chagos (Indian Ocean Territory Time)',
    'Asia/Rangoon' => '(GMT+6:30) Asia/Rangoon (Myanmar Time)',
    'Indian/Cocos' => '(GMT+6:30) Indian/Cocos (Cocos Islands Time)',
    'Antarctica/Davis' => '(GMT+7:00) Antarctica/Davis (Davis Time)',
    'Asia/Bangkok' => '(GMT+7:00) Asia/Bangkok (Indochina Time)',
    'Asia/Ho_Chi_Minh' => '(GMT+7:00) Asia/Ho_Chi_Minh (Indochina Time)',
    'Asia/Hovd' => '(GMT+7:00) Asia/Hovd (Hovd Time)',
    'Asia/Jakarta' => '(GMT+7:00) Asia/Jakarta (West Indonesia Time)',
    'Asia/Krasnoyarsk' => '(GMT+7:00) Asia/Krasnoyarsk (Krasnoyarsk Time)',
    'Asia/Phnom_Penh' => '(GMT+7:00) Asia/Phnom_Penh (Indochina Time)',
    'Asia/Pontianak' => '(GMT+7:00) Asia/Pontianak (West Indonesia Time)',
    'Asia/Saigon' => '(GMT+7:00) Asia/Saigon (Indochina Time)',
    'Asia/Vientiane' => '(GMT+7:00) Asia/Vientiane (Indochina Time)',
    'Indian/Christmas' => '(GMT+7:00) Indian/Christmas (Christmas Island Time)',
    'Antarctica/Casey' => '(GMT+8:00) Antarctica/Casey (Western Standard Time (Australia))',
    'Asia/Brunei' => '(GMT+8:00) Asia/Brunei (Brunei Time)',
    'Asia/Choibalsan' => '(GMT+8:00) Asia/Choibalsan (Choibalsan Time)',
    'Asia/Chongqing' => '(GMT+8:00) Asia/Chongqing (China Standard Time)',
    'Asia/Chungking' => '(GMT+8:00) Asia/Chungking (China Standard Time)',
    'Asia/Harbin' => '(GMT+8:00) Asia/Harbin (China Standard Time)',
    'Asia/Hong_Kong' => '(GMT+8:00) Asia/Hong_Kong (Hong Kong Time)',
    'Asia/Irkutsk' => '(GMT+8:00) Asia/Irkutsk (Irkutsk Time)',
    'Asia/Kashgar' => '(GMT+8:00) Asia/Kashgar (China Standard Time)',
    'Asia/Kuala_Lumpur' => '(GMT+8:00) Asia/Kuala_Lumpur (Malaysia Time)',
    'Asia/Kuching' => '(GMT+8:00) Asia/Kuching (Malaysia Time)',
    'Asia/Macao' => '(GMT+8:00) Asia/Macao (China Standard Time)',
    'Asia/Macau' => '(GMT+8:00) Asia/Macau (China Standard Time)',
    'Asia/Makassar' => '(GMT+8:00) Asia/Makassar (Central Indonesia Time)',
    'Asia/Manila' => '(GMT+8:00) Asia/Manila (Philippines Time)',
    'Asia/Shanghai' => '(GMT+8:00) Asia/Shanghai (China Standard Time)',
    'Asia/Singapore' => '(GMT+8:00) Asia/Singapore (Singapore Time)',
    'Asia/Taipei' => '(GMT+8:00) Asia/Taipei (China Standard Time)',
    'Asia/Ujung_Pandang' => '(GMT+8:00) Asia/Ujung_Pandang (Central Indonesia Time)',
    'Asia/Ulaanbaatar' => '(GMT+8:00) Asia/Ulaanbaatar (Ulaanbaatar Time)',
    'Asia/Ulan_Bator' => '(GMT+8:00) Asia/Ulan_Bator (Ulaanbaatar Time)',
    'Asia/Urumqi' => '(GMT+8:00) Asia/Urumqi (China Standard Time)',
    'Australia/Perth' => '(GMT+8:00) Australia/Perth (Western Standard Time (Australia))',
    'Australia/West' => '(GMT+8:00) Australia/West (Western Standard Time (Australia))',
    'Australia/Eucla' => '(GMT+8:45) Australia/Eucla (Central Western Standard Time (Australia))',
    'Asia/Dili' => '(GMT+9:00) Asia/Dili (Timor-Leste Time)',
    'Asia/Jayapura' => '(GMT+9:00) Asia/Jayapura (East Indonesia Time)',
    'Asia/Pyongyang' => '(GMT+9:00) Asia/Pyongyang (Korea Standard Time)',
    'Asia/Seoul' => '(GMT+9:00) Asia/Seoul (Korea Standard Time)',
    'Asia/Tokyo' => '(GMT+9:00) Asia/Tokyo (Japan Standard Time)',
    'Asia/Yakutsk' => '(GMT+9:00) Asia/Yakutsk (Yakutsk Time)',
    'Australia/Adelaide' => '(GMT+9:30) Australia/Adelaide (Central Standard Time (South Australia))',
    'Australia/Broken_Hill' => '(GMT+9:30) Australia/Broken_Hill (Central Standard Time (South Australia/New South Wales))',
    'Australia/Darwin' => '(GMT+9:30) Australia/Darwin (Central Standard Time (Northern Territory))',
    'Australia/North' => '(GMT+9:30) Australia/North (Central Standard Time (Northern Territory))',
    'Australia/South' => '(GMT+9:30) Australia/South (Central Standard Time (South Australia))',
    'Australia/Yancowinna' => '(GMT+9:30) Australia/Yancowinna (Central Standard Time (South Australia/New South Wales))',
    'Antarctica/DumontDUrville' => '(GMT+10:00) Antarctica/DumontDUrville (Dumont-d\'Urville Time)',
    'Asia/Sakhalin' => '(GMT+10:00) Asia/Sakhalin (Sakhalin Time)',
    'Asia/Vladivostok' => '(GMT+10:00) Asia/Vladivostok (Vladivostok Time)',
    'Australia/ACT' => '(GMT+10:00) Australia/ACT (Eastern Standard Time (New South Wales))',
    'Australia/Brisbane' => '(GMT+10:00) Australia/Brisbane (Eastern Standard Time (Queensland))',
    'Australia/Canberra' => '(GMT+10:00) Australia/Canberra (Eastern Standard Time (New South Wales))',
    'Australia/Currie' => '(GMT+10:00) Australia/Currie (Eastern Standard Time (New South Wales))',
    'Australia/Hobart' => '(GMT+10:00) Australia/Hobart (Eastern Standard Time (Tasmania))',
    'Australia/Lindeman' => '(GMT+10:00) Australia/Lindeman (Eastern Standard Time (Queensland))',
    'Australia/Melbourne' => '(GMT+10:00) Australia/Melbourne (Eastern Standard Time (Victoria))',
    'Australia/NSW' => '(GMT+10:00) Australia/NSW (Eastern Standard Time (New South Wales))',
    'Australia/Queensland' => '(GMT+10:00) Australia/Queensland (Eastern Standard Time (Queensland))',
    'Australia/Sydney' => '(GMT+10:00) Australia/Sydney (Eastern Standard Time (New South Wales))',
    'Australia/Tasmania' => '(GMT+10:00) Australia/Tasmania (Eastern Standard Time (Tasmania))',
    'Australia/Victoria' => '(GMT+10:00) Australia/Victoria (Eastern Standard Time (Victoria))',
    'Australia/LHI' => '(GMT+10:30) Australia/LHI (Lord Howe Standard Time)',
    'Australia/Lord_Howe' => '(GMT+10:30) Australia/Lord_Howe (Lord Howe Standard Time)',
    'Asia/Magadan' => '(GMT+11:00) Asia/Magadan (Magadan Time)',
    'Antarctica/McMurdo' => '(GMT+12:00) Antarctica/McMurdo (New Zealand Standard Time)',
    'Antarctica/South_Pole' => '(GMT+12:00) Antarctica/South_Pole (New Zealand Standard Time)',
    'Asia/Anadyr' => '(GMT+12:00) Asia/Anadyr (Anadyr Time)',
    'Asia/Kamchatka' => '(GMT+12:00) Asia/Kamchatka (Petropavlovsk-Kamchatski Time)'
);