<div class="modal display-settings-modal" tabindex="-1" role="dialog" data-app="display-settings-app">
    <div class="modal-dialog" role="document" id="cl-display-settings-vue-app">
        <div class="modal-content">
            <div class="modal-header">
                <div class="main---mh--block">
                    <h5 class="modal-title">
                        <?php echo cl_translate("Display settings"); ?>
                    </h5>
                    <span class="dismiss-modal" data-dismiss="modal">
                        <?php echo cl_ikon('close'); ?>
                    </span>
                </div>
            </div>
            <div class="modal-body">
                <div class="display-settings">
                    <div class="display-settings__header">
                        <h4>
                            <?php echo cl_translate("Change display view"); ?>
                        </h4>
                        <p>
                            <?php echo cl_translate("Please log in or sign up to customize your view. ", array('name' => $cl['config']['name'])); ?>
                        </p>
                    </div>
                </div>
            </div>
            <div class="modal-footer flex">
                <button class="btn btn-custom main-inline lg" data-toggle="modal" data-target="#loginModal">
                    <?php echo cl_translate("Login"); ?>
                </button>
                <button class="btn btn-custom main-inline lg" data-toggle="modal" data-target="#signupModal">
                    <?php echo cl_translate("Sign up"); ?>
                </button>
            </div>
        </div>
    </div>
</div>
