<div class="modal display-settings-modal" tabindex="-1" role="dialog" data-app="display-settings-app">
    <div class="modal-dialog" role="document" id="cl-display-settings-vue-app">
        <div class="modal-content">
            <div class="modal-header">
                <div class="main---mh--block">
                    <h5 class="modal-title">
                        <?php echo cl_translate("Display settings"); ?>
                    </h5>
                    <span class="dismiss-modal" data-dismiss="modal">
                        <?php echo cl_ikon('close'); ?>
                    </span>
                </div>
            </div>
            <div class="modal-body">
                <div class="display-settings">
                    <div class="display-settings__header">
                        <h4>
                            <?php echo cl_translate("Change display view"); ?>
                        </h4>
                        <p>
                            <?php echo cl_translate("Please log in or sign up to customize your view. ", array('name' => $cl['config']['name'])); ?>
                        </p>
                    </div>
                </div>
            </div>
            <div class="modal-footer flex">
                <button class="btn btn-custom main-inline lg" data-toggle="modal" data-target="#loginModal">
                    <?php echo cl_translate("Login"); ?>
                </button>
                <button class="btn btn-custom main-inline lg" data-toggle="modal" data-target="#signupModal">
                    <?php echo cl_translate("Sign up"); ?>
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    "use strict";

    jQuery(document).ready(function($) {
        new Vue({
            el: "#cl-display-settings-vue-app",
            data: {
                active_bg: "<?php echo($cl['display_set']['background']) ?>",
                active_color: "<?php echo($cl['display_set']['color_scheme']) ?>",
                submitting: false,
                color_schemes: <?php echo cl_minify_js(json($cl["color_schemes"], true)); ?>
            },
            methods: {
                change_color: function(color = "default") {
                    var _app_ = this;

                    _app_.active_color = color;

                    $("body").attr("data-skin", color);
                    $('meta[name="theme-color"]').attr("content", _app_.color_schemes[color].color);
                },
                change_bg: function(bg = false) {
                    var _app_ = this;

                    _app_.active_bg = bg;

                    $("body").attr("data-bg", bg);     
                },
                save_changes: function() {
                    var _app_ = this;

                    $.ajax({
                        url: '<?php echo cl_link("native_api/main/save_display_settings"); ?>',
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            color: _app_.active_color,
                            bg: _app_.active_bg
                        },
                        beforeSend: function() {
                            _app_.submitting = true;
                        }
                    }).done(function(data) {
                        if (data.status != 200) {
                            SMColibri.errorMSG();
                        }
                        else{
                            SMColibri.display_settings("hide");
                        }
                    }).always(function() {
                        _app_.submitting = false;
                    });
                }
            }
        });
    });
</script>