<script>
	"use strict";

	$(document).ready(function($) {
		var _app  = $('[data-app="users"]');
		var _data = _app.find('form[data-an="form"]');

		_data.on('submit', function(event) {
			event.preventDefault();

			var _form = $(this);
			
			_form.ajaxSubmit({
				url: '<?php echo cl_link("native_api/cpanel/create_symbol"); ?>',
				type: 'POST',
				dataType: 'json',
				beforeSend: function() {
					_form.find('small.invalid-feedback').remove();
					_form.find('[data-an="submit-ctrl"]').attr('disabled', 'true').text("Please wait");
				},
				success: function(data) {
					if (data.status == 200) {
						cl_bs_notify("New Symbol created successfully!", 3000);
					}
					else {
						cl_bs_notify("The symbol already exists!", 3000);
					}
				},
				complete: function() {
					_form.find('[data-an="submit-ctrl"]').removeAttr('disabled').text("Create");
				}
			});
		});
	});
</script>