<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
	<div class="h-laptop">
		<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
			<div class="mobile-bottom-navbar-inner">
				<div class="avatar-menu">
					<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
				</div>

			</div>
		</div>
	</div>
<?php endif; ?>
<div class="timeline-container" data-app="err500">
	<div class="timeline-header symbol_header" data-el="tl-header">
		<?php echo cl_template('common/bot_line'); ?>
		<div class="lp" style="display: inline-flex; align-items:center; padding-top:10px;">
			<div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
				<span class="go-back" onclick="SMColibri.go_back();">
					<?php echo cl_ikon('arrow-left'); ?>
				</span>
				<a href="<?php echo cl_link("500"); ?>" data-spa="true">
					<?php echo cl_translate('Error 500'); ?>
				</a>
			</div>
		</div>
	</div>
	<div class="timeline-placeholder" style="padding-top:10px;">
		<div class="icon">
			<div class="icon__bg_img">
			<img src="{%config theme_url%}/statics/img/500-error.png">
			</div>
		</div>
		<div class="pl-message">
			<?php if (not_empty($cl["err_msg"])): ?>
				<h4>
					<?php echo $cl["err_msg"]["title"]; ?>
				</h4>
				<p>
					<?php echo $cl["err_msg"]["desc"]; ?>
				</p>
			<?php else: ?>
				<h4>
					<?php echo cl_translate('Server error 500!'); ?>
				</h4>
				<p>
					<?php echo cl_translate("There was a technical error while trying to process your request. Please go back to the main page or contact us by {@site_email@}", array(
						"site_email" => cl_html_el('a', $cl['config']['email'], array('href' => cl_strf("mailto:%s", $cl['config']['email'])))
					)); ?>
				</p>
			<?php endif; ?>
		</div>
		<div class="c2action-single">
			<a href="<?php echo cl_link('/'); ?>" data-spa="true">
				<button class="btn btn-custom main-outline lg">
					<?php echo cl_translate("Go to your feed"); ?>
				</button>
			</a>
		</div>
	</div>
</div>