<div class="timeline-container" data-app="stat_pages">
	<div class="timeline-header" data-el="tl-header">
		<div class="timeline-header__botline">
			<div class="lp">
				<div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
					<span class="go-back" onclick="SMColibri.go_back();">
						<?php echo cl_ikon('arrow-left'); ?>
					</span>
					<a href="<?php echo cl_link('privacy_policy'); ?>">
						<?php echo cl_translate('Privacy policy'); ?>
					</a>
				</div>
			</div>
			<div class="cp">

			</div>
			<div class="rp">

			</div>
		</div>
	</div>
	<div class="stat-page-content">
		<?php echo cl_template('privacy_policy/src/source'); ?>
	</div>
</div>