<div class="h-laptop">
		<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
			<div class="mobile-bottom-navbar-inner">
				<div class="avatar-menu">
					<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
				</div>

			</div>
		</div>
	</div>
<div class="timeline-container" data-app="watchings">
	<div class="timeline-header" data-el="tl-header">
		<?php echo cl_template('common/bot_line'); ?>
		<div class="lp" style="display: inline-flex; align-items:center; padding-top:10px;">
			<div class="nav-link-holder" style="display: flex;justify-content: center;align-items: center;">
				<span class="go-back" onclick="SMColibri.go_back();">
					<?php echo cl_ikon('arrow-left'); ?>
				</span>
				<a href="<?php echo ($cl['prof_user']['url']); ?>">
					<?php echo ($cl['prof_user']['name']); ?>
				</a>
			</div>
		</div>
	</div>
	<div class="timeline-navbar">
		<div class="timeline-navbar__item">
			<a href="<?php echo cl_link(cl_strf('symbol/%s/watchers', $cl['prof_user']['raw_sname'])); ?>" data-spa="true">
				<button class="timeline-navbar__item-btn <?php if ($cl['page_tab'] == 'watchers') {	echo 'active'; } ?>">
					<span class="btn-flex-inner">							
						<span class="text">
							<?php echo cl_translate("watchers"); ?> (<?php echo cl_number($cl['prof_user']['followers']); ?>)
						</span>
					</span>
				</button>
				<div class="css-1dbjc4n <?php if ($cl['page_tab'] == 'watchers') { echo ('active'); } ?>"></div>
			</a>
		</div>

		<?php if (not_empty($cl['prof_user']['following'])) : ?>
			<div class="timeline-navbar__item">
				<!-- <a href="<?php echo (cl_strf('%s/following', $cl['prof_user']['url'])); ?>" data-spa="true">
					<button class="timeline-navbar__item-btn <?php if ($cl['page_tab'] == 'following') {
																	echo 'active';
																} ?>">
						<span class="btn-flex-inner">
						
							<span class="text">
								<?php echo cl_translate("Following"); ?> (<?php echo cl_number($cl['prof_user']['following']); ?>)
							</span>
						</span>
					</button>
					<div class="css-1dbjc4n <?php if ($cl['page_tab'] == 'following') {
													echo ('active');
												} ?>"></div>
				</a> -->
			</div>
		<?php else : ?>
			<div class="timeline-navbar__item">
			<!-- <a href="<?php echo (cl_strf('%s/following', $cl['prof_user']['url'])); ?>" data-spa="true">
					<button class="timeline-navbar__item-btn <?php if ($cl['page_tab'] == 'following') {
																	echo 'active';
																} ?>">
						<span class="btn-flex-inner">
							
							<span class="text">
								<?php echo cl_translate("Following"); ?>
							</span>
						</span>
					</button>
					<div class="css-1dbjc4n <?php if ($cl['page_tab'] == 'following') {
													echo ('active');
												} ?>"></div>
				</a> -->
			</div>
		<?php endif; ?>
		<?php if (not_empty($cl['prof_user']['owner'])) : ?>
			<div class="timeline-navbar__item">
				<a href="<?php echo (cl_strf('%s/follow_requests', $cl['prof_user']['url'])); ?>" data-spa="true">
					<button class="timeline-navbar__item-btn <?php if ($cl['page_tab'] == 'follow_requests') {
																	echo 'active';
																} ?>">
						<span class="btn-flex-inner">
							
							<span class="text">
								<?php echo cl_translate("Requests"); ?> (<span data-an="total-requests"><?php echo cl_number($cl['prof_user']['follow_requests']); ?></span>)
							</span>
						</span>
					</button>
					<div class="css-1dbjc4n <?php if ($cl['page_tab'] == 'follow_requests') {
													echo ('active');
												} ?>"></div>
				</a>
			</div>
		<?php endif; ?>
	</div>

	<?php if (not_empty($cl["users_list"])) : ?>
		<div class="timeline-users-container">
			<div class="timeline-user-ls" data-an="connectivity-list">
				<?php if (not_empty($cl["users_list"])) : ?>
					<?php foreach ($cl["users_list"] as $cl['li']) : ?>
						<?php echo cl_template('watchings/includes/list_item'); ?>
					<?php endforeach; ?>
				<?php endif; ?>
			</div>
		</div>
		<?php if (count($cl["users_list"]) >= 25) : ?>
			<div class="timeline-data-loader">
				<button class="btn btn-custom main-outline lg" onclick="CLFollowers.load_more(this);">
					<?php echo cl_translate("Show more"); ?>
				</button>
			</div>
		<?php endif; ?>
		<?php echo cl_template('watchings/scripts/app_master_script'); ?>
	<?php else : ?>
		<?php echo cl_template('watchings/includes/empty_list'); ?>
	<?php endif; ?>
</div>