<div class="timeline-container" data-app="homepage">
	<div class="timeline-header symbol_header" data-el="tl-header">
		<div class="timeline-header__botline">
			<div class="lp w-[5%]">
				<div class="nav-link-holder h-mobile">
					<a href="<?php echo cl_link("/"); ?>" data-spa="true">
						<?php echo cl_translate("Home"); ?>
					</a>
				</div>
			</div>
			<div class="cp auto-x">
				<a href="" class="h-laptop">
					<img src="/themes/default/statics/img/logo.svg" alt="Logo" style="visibility: visible;">
					<span class="logo-text">Cointweets</span>
				</a>
			</div>
			<div class="rp middle">
				<div class="flex nav-link-holde h-laptop">
					<a href="javascript:void(0);" onclick="SMColibri.display_settings();">
						<span class="dropdown-item-icon">
							<img class="h-[18px] w-[18px] mr-4" src="/themes/default/statics/ikons/display.svg" alt="">
						</span>
					</a>
					<button class="go-options dropleft show" onclick='$("#searchBar").slideToggle()'>
						<?php echo cl_icon('search'); ?>
					</button>
				</div>
			</div>
		</div>
		<div class="main-search-bar-container mt-1" id="searchBar" style="display: none;">
			<form class="form" id="vue-main-search-app" v-on:submit="search_onsubmit" autocomplete="off">
				<div class="input-holder">
					<input v-model="search_query" v-on:input="search" type="text" class="form-control"
						placeholder="<?php echo cl_translate("Search for people, hashtags..", array('name' => $cl['config']['name'])); ?>">
					<a href="#">
						<?php echo cl_ikon('search'); ?>
					</a>
					<span class="spinner-icon" v-if="searching">
						<?php echo cl_ikon('spinner-icon'); ?>
					</span>
					<span v-on:click="cancel" class="clear-result" v-else-if="search_result">
						<?php echo cl_ikon('close'); ?>
					</span>
				</div>
				<div class="search-result-holder" v-show="search_result">
					<div class="search-result-body">
						<ul class="result-list" data-an="result"></ul>
					</div>
					<div class="search-result-footer" v-bind:class="{'disabled': (advanced_search != true) }">
						<a v-bind:href="search_page_url" data-spa="true">
							<?php echo cl_translate('Advanced search'); ?>
						</a>
					</div>
				</div>
			</form>
		</div>
		<div class="nav-container-top">
			<ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
				<li role="presentation">
					<a class="nav-link active home_nav_btn" id="home-tab" data-toggle="tab" href="#home" role="tab"
						aria-controls="home" aria-selected="true"><?php echo cl_translate("For You"); ?> <div
							class="css-1dbjc4n"></div></a>
				</li>
				<li role="presentation">
					<a class="nav-link home_nav_btn" id="trending-tab" data-toggle="tab" href="#trending" role="tab"
						aria-controls="trending" aria-selected="false">
						<?php echo cl_translate("Trending"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
				<li role="presentation">
					<a class="nav-link home_nav_btn" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
						aria-controls="profile" aria-selected="false">
						<?php echo cl_translate("Following"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
				<li role="presentation">
					<a class="nav-link home_nav_btn" id="page-tab" data-toggle="tab" href="#page" role="tab"
						aria-controls="page" aria-selected="false">
						<?php echo cl_translate("watchings"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<div class="homepage">
		<div class="main-timeline-pubbox-wrapper h-mobile custom-lineheight">
			<?php $cl['pb_id'] = 1;
			echo cl_template('timeline/pubbox'); ?>
		</div>
		<div class="nav-container nav-container-bottom">
			<ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
				<li role="presentation">
					<a class="nav-link active home_nav_btn" id="home-tab" data-toggle="tab" href="#home" role="tab"
						aria-controls="home" aria-selected="true"><?php echo cl_translate("For You"); ?> <div
							class="css-1dbjc4n"></div></a>
				</li>
				<li role="presentation">
					<a class="nav-link home_nav_btn" id="trending-tab" data-toggle="tab" href="#trending" role="tab"
						aria-controls="trending" aria-selected="false">
						<?php echo cl_translate("Trending"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
				<li role="presentation">
					<a class="nav-link home_nav_btn" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
						aria-controls="profile" aria-selected="false">
						<?php echo cl_translate("Following"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
				<li role="presentation">
					<a class="nav-link home_nav_btn" id="page-tab" data-toggle="tab" href="#page" role="tab"
						aria-controls="page" aria-selected="false">
						<?php echo cl_translate("watchings"); ?>
						<div class="css-1dbjc4n"></div>
					</a>
				</li>
			</ul>
		</div>
		<?php if ($cl["config"]["swift_system_status"] == "on"): ?>
			<div class="homepage__swifts">
				<div class="swifts-slider">
					<div class="swiper" id="homepage-swifts-slider">
						<div class="swiper-wrapper">
							<div class="swiper-slide">
								<div class="swift-item" onclick="SMColibri.PS.new_swift.add_swift();">
									<div class="swift-item__body create-swift">
										<div class="swift-item__avatar">
											<img src="<?php echo ($me['avatar']); ?>" alt="Avatar">
										</div>
										<span class="add-ikon">
											<?php echo cl_ikon("plus"); ?>
										</span>
									</div>
									<div class="swift-item__footer">
										<?php echo cl_translate("Create new swift"); ?>
									</div>
								</div>
							</div>
							<?php if (not_empty($cl["tl_swifts"]) && is_array($cl["tl_swifts"])): ?>
								<?php foreach ($cl["tl_swifts"] as $swift_id => $swift_data): ?>
									<div class="swiper-slide">
										<div data-an="swift-item-<?php echo ($swift_data['id']); ?>" class="swift-item <?php if (not_empty($swift_data['has_unseen'])) {
																															echo ('active');
																														} ?>" onclick="SMColibri.PS.play_swift.show('<?php echo ($swift_id); ?>');">
											<div class="swift-item__body">
												<div class="swift-item__avatar">
													<img src="<?php echo ($swift_data['avatar']); ?>" alt="Avatar">
												</div>
											</div>
											<div class="swift-item__footer">
												<?php if (not_empty($swift_data["is_user"])): ?>
													<?php echo cl_translate("Your swifts"); ?>
												<?php else: ?>
													<?php echo ($swift_data['name']); ?>
												<?php endif; ?>
											</div>
										</div>
									</div>
								<?php endforeach; ?>
							<?php endif; ?>
						</div>
					</div>
					<div class="swifts-slider__footer">
						<div class="swiper-scrollbar" id="homepage-swifts-scrollbar"></div>
					</div>
				</div>
			</div>
		<?php endif; ?>
		<div class="tab-content" id="myTabContent">
			<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
				<?php $count = 0; ?>
				<?php if (not_empty($cl["feed"]) && is_array($cl['feed'])): ?>
					<div class="timeline-posts-container">
						<div class="timeline-posts-ls" data-an="entry-list">
							<?php foreach ($cl["feed"] as $cl['li']): ?>
								<?php $count++; ?>
								<?php echo cl_template('timeline/post'); ?>
								<?php if ($count == 3) {
									echo cl_template('home/follow');
								} ?>
							<?php endforeach; ?>
						</div>
						<?php if (count($cl["feed"]) == 30): ?>
							<div class="timeline-data-loader">
								<button class="btn btn-custom main-outline lg" data-an="load-more">
									<?php echo cl_translate("Show more"); ?>
								</button>
							</div>
						<?php endif; ?>
					</div>
				<?php else: ?>
					<div class="timeline-placeholder">
						<div class="icon">
							<div class="icon__bg">
								<?php echo cl_icon('feed'); ?>
							</div>
						</div>
						<div class="pl-message">
							<h4>
								<?php echo cl_translate("No data to display yet!"); ?>
							</h4>
							<p>
								<?php echo cl_translate("It looks like the site has no content to display yet. All featured posts will be displayed on this page"); ?>
							</p>
						</div>
					</div>
				<?php endif; ?>
			</div>
			<div class="tab-pane fade show active" id="trending" role="tabpanel" aria-labelledby="trending-tab">
				<?php $count = 0; ?>
				<?php if (not_empty($cl["trending"]) && is_array($cl['trending'])): ?>
					<div class="timeline-posts-container">
						<div class="timeline-posts-ls" data-an="entry-list">
							<?php foreach ($cl["trending"] as $cl['li']): ?>
								<?php $count++; ?>
								<?php echo cl_template('timeline/post'); ?>
							<?php endforeach; ?>
						</div>
						<?php if (count($cl["trending"]) == 30): ?>
							<div class="timeline-data-loader">
								<button class="btn btn-custom main-outline lg" data-an="load-more">
									<?php echo cl_translate("Show more"); ?>
								</button>
							</div>
						<?php endif; ?>
					</div>
				<?php else: ?>
					<div class="timeline-placeholder">
						<div class="icon">
							<div class="icon__bg">
								<?php echo cl_icon('feed'); ?>
							</div>
						</div>
						<div class="pl-message">
							<h4>
								<?php echo cl_translate("No data to display yet!"); ?>
							</h4>
							<p>
								<?php echo cl_translate("It looks like the site has no content to display yet. All featured posts will be displayed on this page"); ?>
							</p>
						</div>
					</div>
				<?php endif; ?>
			</div>
			<div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
				<div class="timeline-posts-container" style="margin-top: 0px;">
					<?php $count = 0; ?>
					<?php if (not_empty($cl["tl_feed"])): ?>
						<div class="timeline-posts-ls" data-an="entry-list">
							<?php foreach ($cl["tl_feed"] as $cl["li"]): ?>
								<?php $count++; ?>
								<?php echo cl_template('timeline/post'); ?>
								<?php if ($count == 3) {
									echo cl_template('home/follow_feed');
								} ?>
							<?php endforeach; ?>
						</div>
						<?php if (is_array($cl["tl_feed"]) && count($cl["tl_feed"]) == 30): ?>
							<div class="timeline-data-loader">
								<button class="btn btn-custom main-outline lg" data-an="load-more">
									<?php echo cl_translate("Show more"); ?>
								</button>
							</div>
						<?php endif; ?>


					<?php else: ?>
						<div class="timeline-placeholder">
							<div class="icon">
								<div class="icon__bg">
									<?php echo cl_icon('feed'); ?>
								</div>
							</div>
							<div class="pl-message">
								<h4>
									<?php echo cl_translate("No data to display yet!"); ?>
								</h4>
								<p>
									<?php echo cl_translate("It looks like the site has no content to display yet. All featured posts will be displayed on this page"); ?>
								</p>
							</div>
						</div>
					<?php endif; ?>
				</div>
			</div>
			<div class="tab-pane fade" id="page" role="tabpanel" aria-labelledby="page-tab">
				<div class="timeline-posts-container" style="margin-top: 0px;">
					<?php $count = 0; ?>
					<?php if (not_empty($cl["sm_feed"])): ?>
						<div class="timeline-posts-ls" data-an="entry-list">
							<?php foreach ($cl["sm_feed"] as $cl["li"]): ?>
								<?php $count++; ?>
								<?php echo cl_template('timeline/post'); ?>
								<?php if ($count == 3) {
									echo cl_template('home/follow_feed2');			/* edited to make watching work (button to slide) 2024.9.15*/
								} ?>
							<?php endforeach; ?>
						</div>
						<?php if (is_array($cl["sm_feed"]) && count($cl["sm_feed"]) == 30): ?>
							<div class="timeline-data-loader">
								<button class="btn btn-custom main-outline lg" data-an="load-more">
									<?php echo cl_translate("Show more"); ?>
								</button>
							</div>
						<?php endif; ?>


					<?php else: ?>
						<div class="timeline-placeholder">
							<div class="icon">
								<div class="icon__bg">
									<?php echo cl_icon('feed'); ?>
								</div>
							</div>
							<div class="pl-message">
								<h4>
									<?php echo cl_translate("No data to display yet!"); ?>
								</h4>
								<p>
									<?php echo cl_translate("It looks like the site has no content to display yet. All featured posts will be displayed on this page"); ?>
								</p>
							</div>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
			<div class="h-laptop">
				<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
					<div class="mobile-bottom-navbar-inner">
						<div class="avatar-menu">
							<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
						</div>

					</div>
				</div>
			</div>
		<?php endif; ?>

		<?php if ($cl["config"]["swift_system_status"] == "on"): ?>
			<?php echo cl_template("home/modals/swift_lightbox"); ?>
			<?php echo cl_template("home/modals/swift_pubbox"); ?>
		<?php endif; ?>

		<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
		<?php echo cl_template("home/scripts/app_master_script"); ?>
		<?php echo cl_template('feed/scripts/app_master_script'); ?>
	</div>
</div>
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css" rel="stylesheet" />
<!-- MDB -->
<style>
	body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-header {
		height: 107px;
		/* background-color: var(--smc-main-bg-color-3); header opacity background*/
		backdrop-filter: blur(12px);
	}

	.timeline-header__botline {
		border-bottom: 1px solid var(--smc-main-bg-color-2);
		display: flex;
		justify-content: space-between;
		width: 100%;
		align-items: center;
		padding-left: 16px;
		padding-right: 16px;
	}

	.nav-fill .nav-item .nav-link,
	.nav-justified .nav-item .nav-link {
		width: auto;
		text-decoration: none;
		text-transform: none;
		color: var(--smc-main-text-color-lighten-5);
		font-weight: 500;
		font-size: 18px;
	}

	.nav-tabs .nav-link {
		color: var(--smc-main-text-color-2);
	}

	.nav-tabs .nav-item.show .nav-link,
	.nav-tabs .nav-link.active {
		border-bottom: 0px transparent;
		color: var(--smc-main-text-color);
		font-weight: 700;
		background: transparent;
	}

	.nav-tabs .nav-item.show .nav-link,
	.nav-tabs .nav-link.active div.css-1dbjc4n {
		background-color: rgb(29, 155, 240);
		height: 4px;
		width: 28px;
		border-radius: 9999px;
		text-align: center;
		display: block;
		position: relative;
		bottom: 0;
		margin-left: auto;
		margin-right: auto;
		margin-top: 9px;
		margin-bottom: -7px;
	}

	.left-push-nav {
		display: inline-flex;
	}

	.nav-tabs .nav-link:hover {
		background-color: inherit;
		border: 0px !important;
		border-color: transparent !important;
		transition: none !important;
	}

	.home_nav_btn {
		color: var(--smc-main-text-color-2);
		font-size: 18px !important;
		text-transform: none !important;
	}

	.nav-tabs .nav-link {
		padding: 15px 34px 12px 4px !important;
	}
</style>
<script>
	// Initialise Carousel
	const cardSlider = new Carousel(document.querySelector("#cardSlider"), {
		Dots: false,
		itemtsToShow: 5,
	})
	const cardSlider2 = new Carousel(document.querySelector("#cardSlider2"), {
		Dots: false,
		itemtsToShow: 5,
		/* edited by kevin to make watching work (button to slide) 2024.9.15*/
	})
	const cardSlider3 = new Carousel(document.querySelector("#cardSlider3"), {
		/* edited by kevin to make watching work (button to slide) 2024.9.15*/
		Dots: false,
	})
</script>
<script src="https://cdn.tailwindcss.com"></script>
<script>
	"use strict";

	var offset = 30;

	jQuery(document).ready(function($) {
		var _app = $('div[data-app="homepage"]');
		var feed_ls = _app.find('[data-an="entry-list"]');

		_app.find('button[data-an="load-more"]').on('click', function(event) {
			event.preventDefault();

			var _self = $(this);


			$.ajax({
				url: "<?php echo cl_link("native_api/home/load_more"); ?>",
				type: 'GET',
				dataType: 'json',
				data: {
					offset: offset,
				},
				beforeSend: function() {
					_self.attr('disabled', 'true').text("<?php echo cl_translate("Please wait"); ?>");
				}
			}).done(function(data) {
				if (data.status == 200) {
					feed_ls.append(data.html);

					_self.removeAttr('disabled').text("<?php echo cl_translate("Show more"); ?>");

					offset += 30;
				} else {
					_self.text("<?php echo cl_translate("That is all for now!"); ?>");
				}
			});
		});
	});
</script>
<script>
	new Vue({
		el: "#vue-main-search-app",
		data: {
			searching: false,
			search_query: "",
			advanced_search: false,
			search_result: false
		},
		computed: {
			search_page_url: function() {
				if (this.search_query.length > 2) {
					var search_htags_url = "<?php echo cl_link('search/htags?q={0}'); ?>";
					var search_users_url = "<?php echo cl_link('search/people?q={0}'); ?>";
					var search_symbols_url = "<?php echo cl_link('search/symbols?q={0}'); ?>";
					this.advanced_search = true;

					if (this.search_query.charAt(0) == '#') {
						return search_htags_url.format(this.search_query.replace('#', ''));
					} else if (this.search_query.charAt(0) == '$') {
						return search_symbols_url.format(this.search_query.replace('$', ''));
					} else {
						return search_users_url.format(this.search_query);
					}
				} else {
					this.advanced_search = false;
					return "javascript:void(0);";
				}
			},
			query_type: function() {
				if (this.search_query.charAt(0) == '#') {
					return 'htags';
				} else if (this.search_query.charAt(0) == '$') {
					return 'symbols';
				} else {
					return 'users';
				}
			}
		},
		methods: {
			search_onsubmit: function(e = false) {
				e.preventDefault();
				this.search();
			},
			search: function() {
				if (this.search_query.length > 1) {
					var _app_ = this;
					delay(function() {
						$.ajax({
							url: '<?php echo cl_link('native_api/main/search'); ?>',
							type: 'GET',
							dataType: 'json',
							data: {
								query: _app_.search_query.replace(/^[#\$]/, ''), // Remove # or $ at the beginning
								type: _app_.query_type
							},
							beforeSend: function() {
								_app_.searching = true;
							}
						}).done(function(data) {
							_app_.search_result = true;
							$(_app_.$el).find('[data-an="result"]').html($(data.html));
						}).always(function() {
							_app_.searching = false;
						});
					}, 800);
				} else this.search_result = false;
			},
			cancel: function() {
				var _app_ = this;
				_app_.searching = false;
				_app_.search_query = "";
				_app_.advanced_search = false;
				_app_.search_result = false;

				$(_app_.$el).find('[data-an="result"]').empty('');
			}
		}
	});
</script>