<div class="timeline-container" data-app="symbol">
	<?php

	use Aws\DynamoDb\NumberValue;

	$coin_id = strtoupper($cl['prof_user']['username']);
	$url = "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=" . $coin_id . "&tsyms=USD";
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, array('User-Agent: Mozilla/5.0'));
	$response = curl_exec($ch);
	if ($response === false) {
		echo 'Curl error: ' . curl_error($ch);
		curl_close($ch);
		exit;
	}
	curl_close($ch);
	$data = json_decode($response, true);
	if ($data && isset($data['RAW'][$coin_id]['USD']['PRICE'])) {
		$price = (float) $data['RAW'][$coin_id]['USD']['PRICE'];

		if ($price >= 1) {
			$formatted_price = number_format($price, 2);
		} else {
			$significant_digits = 4;
			$precision = $significant_digits - floor(log10(abs($price))) - 1;
			$formatted_price = number_format($price, $precision, '.', '');
		}

		$cl['coin_one'] = [
			'price' => $formatted_price,
			'high_24h' => number_format((float)$data['RAW'][$coin_id]['USD']['HIGH24HOUR'], 2),
			'low_24h' => number_format((float)$data['RAW'][$coin_id]['USD']['LOW24HOUR'], 2),
			'change_24h' => number_format((float)$data['RAW'][$coin_id]['USD']['CHANGE24HOUR'], 2),
			'change_pct_24h' => number_format((float)$data['RAW'][$coin_id]['USD']['CHANGEPCT24HOUR'], 2)
		];
	} else {
		$cl['coin_one'] = [];
	}
	?>
	<div class="h-laptop">
		<div class="mobile-bottom-navbar2" data-app="mobile-navbar">
			<div class="mobile-bottom-navbar-inner">
				<div class="avatar-menu">
					<a href="#" onclick="SMColibri.toggleSB();"> <?php echo cl_icon('hamburger'); ?></a>
				</div>

			</div>
		</div>
	</div>
	<div class="timeline-header symbol_header" data-el="tl-header">
		<div class="timeline-header__topline">
			<div data-el="timeline-bs-notifs" class="timeline-bs-notifs"></div>
		</div>
		<div class="timeline-header__botline selectable">
			<div class="lp x-16">
				<div class="nav-link-holder h-mobile">
					<a href="" data-spa="true">Coin</a>
				</div>
			</div>
			<div class="cp auto-x">
				<a href="" class="h-laptop">
					<img src="/themes/default/statics/img/logo.svg" alt="Logo" style="visibility: visible;">
					<span class="logo-text">Cointweets</span>
				</a>
			</div>
			<div class="rp middle">
				<div class="nav-link-holde">
					<button class="go-options dropleft show bt-3" onclick='$("#searchBar").slideToggle()'>
						<?php echo cl_icon('search'); ?>
					</button>
				</div>
			</div>
		</div>
		<div class="main-search-bar-container mt-1" id="searchBar" style="display: none;">
			<form class="form" id="vue-main-search-app" v-on:submit="search_onsubmit" autocomplete="off">
				<div class="input-holder">
					<input v-model="search_query" v-on:input="search" type="text" class="form-control"
						placeholder="<?php echo cl_translate("Search for people, hashtags..", array('name' => $cl['config']['name'])); ?>">
					<a href="#">
						<?php echo cl_ikon('search'); ?>
					</a>
					<span class="spinner-icon" v-if="searching">
						<?php echo cl_ikon('spinner-icon'); ?>
					</span>
					<span v-on:click="cancel" class="clear-result" v-else-if="search_result">
						<?php echo cl_ikon('close'); ?>
					</span>
				</div>
				<div class="search-result-holder" v-show="search_result">
					<div class="search-result-body">
						<ul class="result-list" data-an="result"></ul>
					</div>
					<div class="search-result-footer" v-bind:class="{'disabled': (advanced_search != true) }">
						<a v-bind:href="search_page_url" data-spa="true">
							<?php echo cl_translate('Advanced search'); ?>
						</a>
					</div>
				</div>
			</form>
		</div>
		<div class="lp" style="display: inline-flex; align-items:center; padding-top:10px; padding-bottom:10px;">
			<span class="go-back" onclick="SMColibri.go_back();" style="width:auto; height:auto; margin-top:0px; margin-right:10px;">
				<?php echo cl_ikon('arrow-left'); ?>
			</span>
			<div class="nav-link-holder nav-link-holder-symbol">
				<a>
					<?php echo ($cl['prof_user']['name']); ?>
				</a>
				<?php if ($cl['prof_user']['verified'] == '1'): ?>
					<span class="user-name-holder__badge" style="display:inline-block;">
						<?php echo cl_icon("verified_user_badge"); ?>
					</span>
				<?php endif; ?>
			</div>
			<div style="display: none;" id="priceHeader">
				<div style="display:flex;">
					<div style="padding-left: 14px; font-size:large; color:var(--smc-main-text-color); font-weight:bold">
						<?php if (isset($cl['coin_one']) && !empty($cl['coin_one'])) : echo "$" . $cl['coin_one']['price']; ?>
						<?php else : echo "Error" ?>
						<?php endif ?>
					</div>
					<div style="padding-left:10px; font-weight:bold; color: <?php echo (floatval(isset($cl['coin_one']['change_pct_24h']) && $cl['coin_one']['change_pct_24h']) > 0) ? '#06806b' : '#dc3545'; ?>;">
						<?php if (isset($cl['coin_one']) && !empty($cl['coin_one']) && isset($cl['coin_one']['change_pct_24h'])) : ?>
							<?php echo $cl['coin_one']['change_pct_24h']; ?>%(1d)
						<?php else : ?>
							<?php echo "Error"; ?>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
		<div class="profile-activity-navbar noBorder" id="selectionPane" style="display: none;">
			<a>
				<button class="navbar-item-btn btn-top <?php if ($cl['page_tab'] == 'posts') {
															echo ('active');
														} ?>" onclick='select("posts")'>
					<?php echo cl_translate("For You"); ?>
				</button>
				<div class="css-1dbjc4nc1 <?php if ($cl['page_tab'] == 'posts') {
												echo ('active');
											} ?>"></div>
			</a>
			<a style="margin-left: 15px;">
				<button class="navbar-item-btn btn-top <?php if ($cl['page_tab'] == 'media') {
															echo ('active');
														} ?>" onclick='select("about")'>
					<?php echo cl_translate("About"); ?>
				</button>
				<div class="css-1dbjc4nc1 <?php if ($cl['page_tab'] == 'media') {
												echo ('active');
											} ?>"></div>
			</a>
		</div>
	</div>
	<div style="background-color:var(--smc-main-bg-color); position:relative;">
		<div class="timeline-prof-info-area">
			<div class="profile-main-info-holder">
				<div style="display: flex; align-items: center;">
					<div class="profile-name-holder" style="display: inline-flex; align-items: center; margin-bottom:0px; width:50%; vertical-align: middle;">
						<div class="profile-avatar" style="max-width: 70px; max-height:70px;">
							<a href="<?php echo ($cl['prof_user']['avatar']); ?>" class="image-wrapper fbox-media">
								<img src="<?php echo ($cl['prof_user']['avatar']); ?>" alt="Avatar" style="border-radius:50%;">
							</a>
						</div>
						<div style="display: block; padding-left:10px;">
							<h4 style="display: inline-flex;  align-items: center; font-size:25;">
								<span>
									<?php echo ($cl['prof_user']['name']); ?>
								</span>
							</h4>
							<div style="color:var(--smc-main-text-color-2); font-size: 20px;" class="font-semibold pt-4 pb-1">
								$<?php echo ($cl['prof_user']['username']); ?>
							</div>
						</div>
					</div>
					<div class="profile-page-ctrls" style="width: 50%;">
						<?php if (empty($cl['is_admin'])): ?>
							<button class="ctrl-item dropleft ">
								<span class=" flex items-center justify-center border rounded-full h-9 w-9 -mt-1"
									data-toggle="dropdown">
									<div class="w-5 h-5"><?php echo cl_ikon('pr-down'); ?></div>
								</span>
								<div class="dropdown-menu dropdown-icons">
									<a class="dropdown-item" href="<?php echo cl_link(cl_strf('symbol/%s/watchers', $cl['prof_user']['raw_sname'])); ?>">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon("people"); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Show Watchers'); ?>
										</span>
									</a>
									<a data-clipboard-text="<?php $currentDomain = (isset($_SERVER['HTTPS']) ? "https://" : "http://") . $_SERVER['HTTP_HOST'];
															echo (cl_strf('%s/symbol/%s', $currentDomain, $cl['prof_user']['username'])); ?>"
										class="dropdown-item clip-board-copy" href="javascript:void(0);">
										<span class="flex-item dropdown-item-icon">
											<svg viewBox="0 0 24 24" aria-hidden="true"
												class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-1q142lx r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr">
												<g>
													<path
														d="M18.36 5.64c-1.95-1.96-5.11-1.96-7.07 0L9.88 7.05 8.46 5.64l1.42-1.42c2.73-2.73 7.16-2.73 9.9 0 2.73 2.74 2.73 7.17 0 9.9l-1.42 1.42-1.41-1.42 1.41-1.41c1.96-1.96 1.96-5.12 0-7.07zm-2.12 3.53l-7.07 7.07-1.41-1.41 7.07-7.07 1.41 1.41zm-12.02.71l1.42-1.42 1.41 1.42-1.41 1.41c-1.96 1.96-1.96 5.12 0 7.07 1.95 1.96 5.11 1.96 7.07 0l1.41-1.41 1.42 1.41-1.42 1.42c-2.73 2.73-7.16 2.73-9.9 0-2.73-2.74-2.73-7.17 0-9.9z">
													</path>
												</g>
											</svg>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Copy link to Coin page'); ?>
										</span>
									</a>
									<a class="dropdown-item" onclick="SMColibri.PS.profile_report.open();"
										href="javascript:void(0);">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon("flag"); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Report'); ?> $
											<?php echo ($cl['prof_user']['username']); ?>
										</span>
									</a>
								</div>
							</button>
							<?php if (empty($cl['prof_user']['is_blocked'])): ?>
								<?php if (empty($cl['prof_user']['me_blocked'])): ?>
									<?php if ($cl['prof_user']['follow_privacy'] == 'approved'): ?>
										<?php if (not_empty($cl['prof_user']['is_following'])): ?>
											<div>
												<button onclick="SMColibri.req_follow(this);" class="btn btn-custom main-inline md"
													data-action="unfollow" data-user-name="<?php echo ($cl['prof_user']['name']); ?>"
													data-id="<?php echo ($cl['prof_user']['id']); ?>">
													<?php echo cl_translate("Unfollow"); ?>
												</button>
											</div>
										<?php elseif (not_empty($cl['prof_user']['follow_requested'])): ?>
											<div>
												<button onclick="SMColibri.req_follow(this);" class="btn btn-custom main-inline md"
													data-action="cancel" data-user-name="<?php echo ($cl['prof_user']['name']); ?>"
													data-id="<?php echo ($cl['prof_user']['id']); ?>">
													<?php echo cl_translate("Pending"); ?>
												</button>
											</div>
										<?php else: ?>
											<div>
												<button onclick="SMColibri.req_follow(this);" class="btn btn-custom main-outline md"
													data-action="follow" data-user-name="<?php echo ($cl['prof_user']['name']); ?>"
													data-id="<?php echo ($cl['prof_user']['id']); ?>">
													<?php echo cl_translate("watch"); ?>
												</button>
											</div>
										<?php endif; ?>
									<?php else: ?>
										<?php if (not_empty($cl['prof_user']['is_following'])): ?>
											<div>
												<button onclick="SMColibri.watch(this);" class="btn btn-custom main-inline md"
													data-action="unfollow" data-user-name="<?php echo ($cl['prof_user']['name']); ?>"
													data-id="<?php echo ($cl['prof_user']['id']); ?>">
													<?php echo cl_translate("unwatch"); ?>
												</button>
											</div>
										<?php else: ?>
											<div>
												<button onclick="SMColibri.watch(this);" class="btn btn-custom main-outline md" data-action="follow"
													data-user-name="<?php echo ($cl['prof_user']['name']); ?>"
													data-id="<?php echo ($cl['prof_user']['id']); ?>">
													<?php echo cl_translate("watch"); ?>
												</button>
											</div>
										<?php endif; ?>
									<?php endif; ?>
								<?php endif ?>
							<?php endif; ?>
						<?php else : ?>
							<button class="ctrl-item dropleft ">
								<span class=" flex items-center justify-center border rounded-full h-9 w-9 -mt-1"
									data-toggle="dropdown">
									<div class="w-5 h-5"> <?php echo cl_ikon('pr-down'); ?></div>
								</span>
								<div class="dropdown-menu dropdown-icons">
									<a class="dropdown-item" href="<?php echo cl_link(cl_strf('symbol/%s/watchers', $cl['prof_user']['raw_sname'])); ?>">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon("people"); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Show Watchers'); ?>
										</span>
									</a>
									<a data-clipboard-text="<?php $currentDomain = (isset($_SERVER['HTTPS']) ? "https://" : "http://") . $_SERVER['HTTP_HOST'];
															echo (cl_strf('%s/symbol/%s', $currentDomain, $cl['prof_user']['username'])); ?>"
										class="dropdown-item clip-board-copy" href="javascript:void(0);">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon("copy"); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Copy link to Coin page'); ?>
										</span>
									</a>
									<?php if (not_empty($cl['is_logged'])): ?>
										<?php if (not_empty($cl['is_admin'])): ?>
											<div class="dropdown-divider"></div>
											<a class="dropdown-item"
												onclick="SMColibri.delete_account(<?php echo ($cl['prof_user']['id']); ?>);"
												href="javascript:void(0);">
												<span class="flex-item dropdown-item-icon">
													<?php echo cl_icon("delete"); ?>
												</span>
												<span class="flex-item">
													<?php echo cl_translate('Delete'); ?> $
													<?php echo ($cl['prof_user']['username']); ?>
												</span>
											</a>
											<?php if ($cl['prof_user']['active'] == "2"): ?>
												<a class="dropdown-item"
													onclick="SMColibri.unsuspend_account(<?php echo ($cl['prof_user']['id']); ?>);"
													href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_icon("person"); ?>
													</span>
													<span class="flex-item">
														<?php echo cl_translate('Unsuspend'); ?> $
														<?php echo ($cl['prof_user']['username']); ?>
													</span>

												</a>
											<?php else: ?>
												<a class="dropdown-item"
													onclick="SMColibri.suspend_account(<?php echo ($cl['prof_user']['id']); ?>);"
													href="javascript:void(0);">
													<span class="flex-item dropdown-item-icon">
														<?php echo cl_icon("person_off"); ?>
													</span>
													<span class="flex-item">
														<?php echo cl_translate('Suspend'); ?> $
														<?php echo ($cl['prof_user']['username']); ?>
													</span>

												</a>
											<?php endif; ?>
											<div class="dropdown-divider"></div>
										<?php endif; ?>
									<?php endif; ?>
								</div>
							</button>
							<button data-anchor="<?php echo $cl['settings_link']; ?>" class="btn btn-custom main-inline md">
								<?php echo cl_translate("symbol_settings"); ?>
							</button>
						<?php endif ?>
					</div>
				</div>
				<div style="display: flex; text-align:left; align-items:center; padding: 9px 0px">
					<div style="width: 75%; display:flex;">
						<div style="padding-left: 14px; font-size:xx-large; color:var(--smc-main-text-color); font-weight:bold" id='price'>
							<?php if (isset($cl['coin_one']) && !empty($cl['coin_one'])) : echo "$" . $cl['coin_one']['price']; ?>
							<?php else : echo "No Data"; ?>
							<?php endif ?>
						</div>
						<div style="padding-left:10px; font-weight:bold; color: <?php echo (isset($cl['coin_one']['change_pct_24h']) && floatval($cl['coin_one']['change_pct_24h']) > 0) ? '#06806b' : '#dc3545'; ?>;">
							<?php if (isset($cl['coin_one']) && !empty($cl['coin_one']) && isset($cl['coin_one']['change_pct_24h'])) : ?>
								<?php echo $cl['coin_one']['change_pct_24h']; ?>
							<?php else : ?>
								<?php echo "No Data"; ?>
							<?php endif; ?>
							%(1d)
						</div>
					</div>
					<div style="width: 25%; display: flex; padding:10px;">
						<div class="profile-activity-stats-info" style="justify-content: end; margin-bottom: 0px;">
							<div class="stat-holder">
								<?php if (not_empty($cl["can_view"])): ?>
									<a href="<?php echo cl_link(cl_strf('symbol/%s/watchers', $cl['prof_user']['raw_sname'])); ?>"
										class="stat-holder-inner">
									<?php else: ?>
										<a href="javascript:void(0);" class="stat-holder-inner"
											onclick="SMColibri.PS.profile.privacy_alert();">
										<?php endif; ?>
										<b>
											<?php echo cl_number($cl['prof_user']['followers']); ?>
										</b>
										<span>
											<?php echo cl_translate("watcher"); ?>
										</span>
										</a>
							</div>
						</div>
					</div>
				</div>
				<?php if (not_empty($cl["is_logged"])): ?>
					<!-- Start Add Post  -->
					<div class="flex flex-col  w-full ">
						<div class="homepage">
							<div class="main-timeline-pubbox-wrapper custom-lineheight px-3 pt-3 py-2">
								<?php $cl['pb_id'] = 1;
								echo cl_template('timeline/symbolbox'); ?>
							</div>
							<?php if ($cl["config"]["swift_system_status"] == "on"): ?>
								<div class="homepage__swifts hidden">
									<div class="swifts-slider">
										<div class="swiper" id="homepage-swifts-slider">
											<div class="swiper-wrapper">
												<div class="swiper-slide">
													<div class="swift-item" onclick="SMColibri.PS.new_swift.add_swift();">
														<div class="swift-item__body create-swift">
															<div class="swift-item__avatar">
																<img src="<?php echo ($me['avatar']); ?>" alt="Avatar">
															</div>
															<span class="add-ikon">
																<?php echo cl_ikon("plus"); ?>
															</span>
														</div>
														<div class="swift-item__footer">
															<?php echo cl_translate("Create new swift"); ?>
														</div>
													</div>
												</div>
												<?php if (not_empty($cl["tl_swifts"]) && is_array($cl["tl_swifts"])): ?>
													<?php foreach ($cl["tl_swifts"] as $swift_id => $swift_data): ?>
														<div class="swiper-slide">
															<div data-an="swift-item-<?php echo ($swift_data['id']); ?>" class="swift-item <?php if (not_empty($swift_data['has_unseen'])) {
																																				echo ('active');
																																			} ?>" onclick="SMColibri.PS.play_swift.show('<?php echo ($swift_id); ?>');">
																<div class="swift-item__body">
																	<div class="swift-item__avatar">
																		<img src="<?php echo ($swift_data['avatar']); ?>" alt="Avatar">
																	</div>
																</div>
																<div class="swift-item__footer">
																	<?php if (not_empty($swift_data["is_user"])): ?>
																		<?php echo cl_translate("Your swifts"); ?>
																	<?php else: ?>
																		<?php echo ($swift_data['name']); ?>
																	<?php endif; ?>
																</div>
															</div>
														</div>
													<?php endforeach; ?>
												<?php endif; ?>
											</div>
										</div>
										<div class="swifts-slider__footer">
											<div class="swiper-scrollbar" id="homepage-swifts-scrollbar"></div>
										</div>
									</div>
								</div>
							<?php endif; ?>
						</div>
					</div>
				<?php else: ?>
					<div></div>
				<?php endif; ?>
				<?php if (not_empty($cl["can_view"])): ?>
					<div class="profile-activity-navbar">
						<a>
							<button class="navbar-item-btn <?php if ($cl['page_tab'] == 'posts') {
																echo ('active');
															} ?>" onclick='select("posts")'>
								<?php echo cl_translate("For You"); ?>
							</button>
							<div class="css-1dbjc4nc1 <?php if ($cl['page_tab'] == 'posts') {
															echo ('active');
														} ?>"></div>
						</a>
						<a style="margin-left: 15px;">
							<button class="navbar-item-btn <?php if ($cl['page_tab'] == 'media') {
																echo ('active');
															} ?>" onclick='select("about")'>
								<?php echo cl_translate("About"); ?>
							</button>
							<div class="css-1dbjc4nc1 <?php if ($cl['page_tab'] == 'media') {
															echo ('active');
														} ?>"></div>
						</a>
					</div>
				<?php endif; ?>
			</div>
		</div>
		<div class="tab-content">
			<div class="tab-pane fade active show" id="posts">
				<?php if (not_empty($cl['prof_user']['is_blocked']) || not_empty($cl['prof_user']['me_blocked'])): ?>
					<div class="timeline-posts-container">
						<div class="timeline-posts-ls">
							<?php echo cl_template('symbol/includes/blocked_profile'); ?>
						</div>
					</div>
				<?php else: ?>
					<?php if (not_empty($cl["can_view"])): ?>
						<?php if (in_array($cl['page_tab'], array('posts', 'media'))): ?>
							<div class="timeline-posts-container py-2">
								<?php $count = 0; ?>
								<?php if (not_empty($cl["user_posts"]) && is_array($cl["user_posts"])): ?>
									<div class="timeline-posts-ls" data-an="entry-list">
										<?php foreach ($cl["user_posts"] as $cl['li']): ?>
											<?php $count++; ?>
											<?php echo cl_template('timeline/post_symbol'); ?>
											<?php if ($count == 3) {
												echo cl_template('home/follow');
											} ?>
										<?php endforeach; ?>
									</div>
								<?php else: ?>
									<?php echo cl_template('symbol/includes/no_posts'); ?>
								<?php endif; ?>
							</div>
						<?php else: ?>
							<div class="timeline-posts-container">
								<div class="timeline-posts-ls py-2" data-an="entry-list">
									<?php if (not_empty($cl["user_likes"]) && is_array($cl["user_likes"])): ?>
										<?php foreach ($cl["user_likes"] as $cl['li']): ?>
											<?php echo cl_template('timeline/post_symbol'); ?>
											<?php echo cl_template('timeline/post_symbol'); ?>
										<?php endforeach; ?>
									<?php else: ?>
										<?php echo cl_template('symbol/includes/no_posts'); ?>
									<?php endif; ?>
								</div>
							</div>
						<?php endif; ?>
					<?php else: ?>
						<div class="timeline-posts-container">
							<div class="timeline-posts-ls">
								<?php echo cl_template('symbol/includes/private_profile'); ?>
							</div>
						</div>
					<?php endif; ?>
				<?php endif; ?>
			</div>
			<div class="tab-pane fade" id="about">
				<div class="timeline-posts-container">
					<div class="timeline-posts-ls py-2">
						<?php echo cl_template('symbol/includes/about'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<?php echo cl_template('symbol/scripts/app_master_script'); ?>

	<?php if (empty($cl['is_admin'])): ?>
		<?php echo cl_template('symbol/modals/report_profile'); ?>
	<?php endif; ?>

	<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>

</div>
<script src="https://cdn.tailwindcss.com"></script>
<script type="text/javascript">
	new Vue({
		el: "#vue-main-search-app",
		data: {
			searching: false,
			search_query: "",
			advanced_search: false,
			search_result: false
		},
		computed: {
			search_page_url: function() {
				if (this.search_query.length > 2) {
					var search_htags_url = "<?php echo cl_link('search/htags?q={0}'); ?>";
					var search_users_url = "<?php echo cl_link('search/people?q={0}'); ?>";
					var search_symbols_url = "<?php echo cl_link('search/symbols?q={0}'); ?>";
					this.advanced_search = true;

					if (this.search_query.charAt(0) == '#') {
						return search_htags_url.format(this.search_query.replace('#', ''));
					} else if (this.search_query.charAt(0) == '$') {
						return search_symbols_url.format(this.search_query.replace('$', ''));
					} else {
						return search_users_url.format(this.search_query);
					}
				} else {
					this.advanced_search = false;
					return "javascript:void(0);";
				}
			},
			query_type: function() {
				if (this.search_query.charAt(0) == '#') {
					return 'htags';
				} else if (this.search_query.charAt(0) == '$') {
					return 'symbols';
				} else {
					return 'users';
				}
			}
		},
		methods: {
			search_onsubmit: function(e = false) {
				e.preventDefault();
				this.search();
			},
			search: function() {
				if (this.search_query.length > 1) {
					var _app_ = this;
					delay(function() {
						$.ajax({
							url: '<?php echo cl_link('native_api/main/search'); ?>',
							type: 'GET',
							dataType: 'json',
							data: {
								query: _app_.search_query.replace(/^[#\$]/, ''), // Remove # or $ at the beginning
								type: _app_.query_type
							},
							beforeSend: function() {
								_app_.searching = true;
							}
						}).done(function(data) {
							_app_.search_result = true;
							$(_app_.$el).find('[data-an="result"]').html($(data.html));
						}).always(function() {
							_app_.searching = false;
						});
					}, 800);
				} else this.search_result = false;
			},
			cancel: function() {
				var _app_ = this;
				_app_.searching = false;
				_app_.search_query = "";
				_app_.advanced_search = false;
				_app_.search_result = false;

				$(_app_.$el).find('[data-an="result"]').empty('');
			}
		}
	});
	$(function() {
		moveScroller();
	});

	function moveScroller() {
		var $anchor = $("#scroller-anchor");
		var $scroller = $('#scroller');

		var move = function() {
			var y = window.scrollY;
			if (y > 120) $("#priceHeader").slideDown();
			else $("#priceHeader").slideUp();
			if (y > 355) $("#selectionPane").slideDown();
			else $("#selectionPane").slideUp();
			var st = $(window).scrollTop();
			if ($anchor.length === 0) {
				console.error("Anchor element not found");
				return; // Exit the function if the anchor is not found
			}
			var ot = $anchor.offset().top;
			if (st > ot) {
				$scroller.css({
					position: "fixed",
					top: "7px"
				});
			} else {
				$scroller.css({
					position: "relative",
					top: ""
				});
			}
		};
		$(window).scroll(move);
		move();
	}
</script>
<script type="text/javascript">
	$(document).ready(function() {
		$("#verPopover").popover({
			template: '<div class="popover1" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>',
			trigger: 'focus',
			html: true,
			content: `<svg viewBox="0 0 24 24" aria-hidden="true" class="r-1cvl2hr r-4qtqp9 r-yyyyoo r-1yjpyg1 r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr" data-testid="verificationBadge"><g><path d="M22.25 12c0-1.43-.88-2.67-2.19-3.34.46-1.39.2-2.9-.81-3.91s-2.52-1.27-3.91-.81c-.66-1.31-1.91-2.19-3.34-2.19s-2.67.88-3.33 2.19c-1.4-.46-2.91-.2-3.92.81s-1.26 2.52-.8 3.91c-1.31.67-2.2 1.91-2.2 3.34s.89 2.67 2.2 3.34c-.46 1.39-.21 2.9.8 3.91s2.52 1.26 3.91.81c.67 1.31 1.91 2.19 3.34 2.19s2.68-.88 3.34-2.19c1.39.45 2.9.2 3.91-.81s1.27-2.52.81-3.91c1.31-.67 2.19-1.91 2.19-3.34zm-11.71 4.2L6.8 12.46l1.41-1.42 2.26 2.26 4.8-5.23 1.47 1.36-6.2 6.77z"></path></g></svg> <span>	<?php echo cl_translate("verified_account"); ?>  </span> <p> <?php echo cl_translate("verified_account_desc"); ?>	 <?php if ($cl['config']['blue_account_system_status'] == 'on'): ?>
												<?php if ($se["is_blue"] == 1): ?>
																	<a  href="<?php echo cl_link("blue_features"); ?>"
																		data-navitem="blue_features">  <?php echo cl_translate("verified_account_link"); ?> </a> <?php else: ?>	<a href="<?php echo cl_link("blue_account"); ?>" data-spa="true"> <?php echo cl_translate("verified_account_link"); ?></a><?php endif; ?>
				<?php endif; ?></p> `,
			placement: 'bottom'
		});
	});
</script>
<style>
	body {
		font-family: "Roboto", sans-serif;
	}

	body div.popover1 div.popover-body {
		box-shadow: rgba(101, 119, 134, 0.2) 0px 0px 15px, rgba(101, 119, 134, 0.15) 0px 0px 3px 1px;
		background-color: var(--smc-main-bg-color);
		border-radius: 16px;
		display: inline-flex;
		overflow: hidden;
		-moz-box-align: stretch;
		-moz-box-direction: normal;
		-moz-box-orient: vertical;
		align-items: stretch;
		border: 0px solid black;
		box-sizing: border-box;
		display: flex;
		flex-basis: auto;
		flex-direction: column;
		flex-shrink: 0;
		margin: 0px;
		min-height: 0px;
		min-width: 0px;
		padding: 15px;
		position: relative;
		z-index: 0;
		pointer-events: auto;
		width: 360px;
		max-width: 360px;
		justify-content: center;
		align-items: center;
	}

	body div.popover1 div.popover-body svg {
		font-size: 31px;
		height: 1.25em;
		position: relative;
		max-width: 100%;
		display: inline-block;
		pointer-events: auto;
	}

	body div.popover1 div.popover-body span {
		line-height: 28px;
		font-size: 23px;
		margin-top: 12px;
		color: var(--smc-main-text-color);
		font-weight: 700;
	}

	body div.popover1 div.popover-body p {
		margin-top: 12px;
		color: rgb(83, 100, 113);
		font-weight: 400;
		font-size: 15px;
		line-height: 20px;
		overflow-wrap: break-word;
		text-align: center;
	}

	body div.popover1 div.popover-body p a {
		text-decoration: none;
	}

	@media (max-width: 1024px) {
		body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container div.timeline-posts-container {
			margin-top: 3px;
		}

		body div.popover1 div.popover-body {
			width: 280px;
			max-width: 280px;
		}

		.profile-name-holder span.user-name-holder {
			overflow-wrap: break-word;
			min-width: 0px;
			max-width: 295px;
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
			display: inline-block;
		}

		body .nav-link-holder span.user-name-holder {
			overflow-wrap: break-word;
			min-width: 0px;
			max-width: 295px;
			overflow: visible;
			text-overflow: ellipsis;
			white-space: nowrap;
			display: inline-flex;
		}

		@media (max-width: 1024px) {
			body main.main-content-container div.main-content-container-inner div.timeline-container-wrapper div.timeline-container-inner div.timeline-container {
				padding-top: 83px !important;
			}
		}
	}
</style>
<script>
	var state = "posts";
	// Initialise Carousel
	const cardSlider = new Carousel(document.querySelector("#cardSlider"), {
		Dots: false,
	});

	select = (pane) => {
		var posts = document.getElementById("posts");
		var about = document.getElementById("about");
		var selectionPane = document.getElementsByClassName("profile-activity-navbar");
		if (pane === 'posts') {
			if (state === 'posts') return;
			$("#posts").toggleClass("show active");
			$("#about").toggleClass("show active");
			state = "posts";
			for (var i = 0; i < 2; i++) {
				selectionPane[i].getElementsByClassName("css-1dbjc4nc1")[0].classList.add("active");
				selectionPane[i].getElementsByClassName("css-1dbjc4nc1")[1].classList.remove("active");
				selectionPane[i].getElementsByClassName("navbar-item-btn")[0].classList.add("active");
				selectionPane[i].getElementsByClassName("navbar-item-btn")[1].classList.remove("active");
			}
		} else {
			if (state === 'about') return;
			$("#posts").toggleClass("show active");
			$("#about").toggleClass("show active");
			state = 'about';
			for (var i = 0; i < 2; i++) {
				selectionPane[i].getElementsByClassName("css-1dbjc4nc1")[1].classList.add("active");
				selectionPane[i].getElementsByClassName("css-1dbjc4nc1")[0].classList.remove("active");
				selectionPane[i].getElementsByClassName("navbar-item-btn")[1].classList.add("active");
				selectionPane[i].getElementsByClassName("navbar-item-btn")[0].classList.remove("active");
			}
			if (window.scrollY > 400) { // {{ edit_1 }}
				about.scrollIntoView({
					behavior: 'smooth',
					block: 'start'
				});
				window.scrollTo(0, 400);
			}
		}
	}
</script>

<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>

<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>

<?php echo cl_template('feed/scripts/app_master_script'); ?>