
<?php
    global $db;
    $symbol = $cl['li']['symbol'];
    $db        = $db->where('username', $symbol);
    $symbol_data = $db->getOne(T_SYMBOLS);
    if (empty($symbol_data)) { // Check if data is found
        return;
    }
    $symbol_data['avatar']       = cl_get_media($symbol_data['avatar']);
    if(isset($me['id'])){
        $symbol_data['is_following'] = cl_is_watching($me['id'], $symbol_data['id']);
        $symbol_data['follow_requested'] = cl_watch_requested($me['id'], $symbol_data['id']);
    }
?>

<div class="search-result__list-item search-result__list-item_user mt-2">
    <a href="#" >
        <div class="result-item-data">
            <div class="result-item-data__avatar">
                <div class="avatar">
                    <img src="<?php echo($symbol_data['avatar']); ?>" alt="Avatar">
                </div>
            </div>
            <div class="result-item-data__data">
                <div class="result-item-data__topline">
                    <span class="user-name-holder flex">
                        <span class="user-name-holder__name">
                            <?php echo($symbol_data['username']); ?>
                        </span>
                    </span>
                </div>
                <div class="result-item-data__botline">
                    <?php echo($symbol_data['fname']); ?>
                </div>
            </div>
            <?php if(isset($me['id'])): ?>
                <?php if ($symbol_data['is_following']): ?>
                    <button onclick="SMColibri.req_watch_mobile(this);" data-user-name="<?php echo($symbol_data['username']); ?>" class="search-ctrls-item" data-action="unfollow" data-id="<?php echo($symbol_data['id']); ?>">
                        <span class = "icon"><?php echo cl_ikon("minus"); ?></span>
                    </button>
                <?php elseif ($symbol_data['follow_requested']): ?>
                    <button onclick="SMColibri.req_watch_mobile(this);" data-user-name="<?php echo($symbol_data['username']); ?>" class="search-ctrls-item" data-action="cancel" data-id="<?php echo($symbol_data['id']); ?>">
                        <span class = "icon"><?php echo cl_ikon("pr-down"); ?></span>
                    </button>
                <?php else: ?>
                    <button onclick="SMColibri.req_watch_mobile(this);" data-user-name="<?php echo($symbol_data['username']); ?>" class="search-ctrls-item" data-action="follow" data-id="<?php echo($symbol_data['id']); ?>">
                        <span class = "icon"><?php echo cl_ikon("plus"); ?></span>
                    </button>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </a>
</div>
