<div class="search-result__list-item search-result__list-item_htag">
	<a href="<?php echo($cl['li']['url']); ?>" data-spa="true">
		<div class="result-item-data">
			<div class="result-item-data__icon">
				<div class="icon">
				<div class="text-[18px] text-gray-600 font-semibold">$</div>
				</div>
			</div>
			<div class="result-item-data__data">
				<div class="result-item-data__topline">
					<?php echo($cl['li']['hashsymbol']); ?>
				</div>
				<div class="result-item-data__botline">
					<?php echo($cl['li']['total']); ?> <?php echo cl_translate('Posts'); ?>
				</div>
			</div>
		</div>
	</a>
</div>